-- ============================================================
-- AxysEasy — PROPOSTA de Schema: módulo ATIVO (+ tenant_catalogo)
-- Banco: PostgreSQL 14+
-- Status: PROPOSTA p/ validação (2026-06-14). Depois de validada,
--         migra-se para docs/projects/axys-easy/schemas/schema.sql.
--
-- Contratos canônicos (governam este schema):
--   docs/projects/axys-easy/contracts/ativo/easy_modulo_ativo_architecture_contract.md (v0.2)
--   docs/projects/axys-easy/contracts/ativo/modulo_ativo_sumario_executivo.md (v0.2)
-- Memórias de decisão: project_ativos_decisoes, project_catalogo_sem_recriar.
--
-- ESCOPO DESTA PROPOSTA
--   Sobe a ÁRVORE INTEIRA do domínio ativo (todas as tabelas MVP do contrato §6/§8),
--   não só a espinha de terça — decisão Renan: "schema o mais produtivo possível;
--   incluir coluna depois tudo bem, mas nascer completo". O corte "para terça" é de
--   IMPLEMENTAÇÃO (backend/UI), não de schema.
--   Namespace reservado (ativo_docs/pm/diario/fin/licit/repo) NÃO é criado (só comentado).
--
-- DECISÕES APLICADAS (project_ativos_decisoes, 2026-06-14)
--   • Nomes/prefixos do contrato: emp_ atv_ ficha_ par_ atr_ ati_ opa_ ocp_ oci_
--     oin_ oip_ mc_ mci_ mil_ rev_ evt_.
--   • ati_path = TEXT zero-padded ("0001.0002"); índice DERIVADO da árvore
--     (verdade = ati_parent_id + ati_ordem). ltree NÃO usado (extensão ausente).
--   • Preço RESOLVIDO, não persistido: ativo_itens NÃO tem custo. Base SE@edição
--     (catálogo) + LS/BDI do contexto (orcamento_parametros), lazy. Só a emissão
--     congela (ativo_revisoes.rev_snapshot_json).
--   • Isolamento: tenant_uuid nas RAÍZES (empreendimentos, ativos, tenant_catalogo.*);
--     folhas derivam por FK. tenant_uuid SEMPRE preenchido — a Axys tem tenant próprio
--     na app (role interna); modelos do "catálogo de ativos" usam o tenant da Axys.
--     RLS-política DIFERIDA (coluna entra agora; policy depois).
--   • Catálogo consumido COMO ESTÁ (composição é por edição → custo@edição já resolvível).
--   • "Catálogo de ativos" = ÁRVORE ÚNICA (decidido): o modelo é um ATIVO comum marcado
--     atv_is_catalog_source=TRUE (sem schema espelhado, sem duplicação). Drivers ligam-se
--     ao item via TABELA-PONTE ativo.ativo_itens_drivers (N:N) — sem coluna nula em massa.
--   • PKs GENERATED BY DEFAULT (não ALWAYS) → permitem reinsert com id original na
--     RECONSTRUÇÃO (offboarding/arquivamento por tenant). Ver §ARQUIVAMENTO no fim.
--
-- ⚠️ PONTOS A VALIDAR (marcados [VALIDAR] no corpo)
--   • tenant_uuid: Hub é banco SEPARADO (EASY_HUB_DB_URL) → SEM FK física a hub_tenant.
--   • Drivers: desenho fino da regra (drv_regra_json) a detalhar quando o gerador nascer;
--     tabelas criadas como reserva CONCRETA (a pedido), lean e flexíveis por JSONB.
--   • tenant_catalogo.*: espelha catalogo.* — validar colunas finas contra o schema.sql
--     do Catálogo na implementação (contrato §8.14).
--   • §ARQUIVAMENTO (schema arquivo): lifecycle de desconstrução/reconstrução por tenant —
--     possível mover p/ contrato próprio. Incluído aqui como proposta concreta.
--
-- PADRÃO DA CASA (igual ao schema.sql do Catálogo)
--   Prefixo de coluna = abreviatura da tabela; PK INTEGER GENERATED BY DEFAULT AS IDENTITY;
--   TIMESTAMPTZ; valores NUMERIC(14,4); coeficientes NUMERIC(14,10);
--   audit trail: _criado_em/_atualizado_em/_criado_por/_atualizado_por.
-- ============================================================


-- ============================================================
-- SCHEMA: ativo
-- ============================================================
CREATE SCHEMA IF NOT EXISTS ativo;

GRANT USAGE ON SCHEMA ativo TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA ativo
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA ativo
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";


-- ============================================================
-- SCHEMA: tenant_catalogo  (biblioteca técnica própria do tenant)
-- Contrato §3.4 / §8.14 — espelha a FORMA do catalogo, isolado por tenant.
-- ============================================================
CREATE SCHEMA IF NOT EXISTS tenant_catalogo;

GRANT USAGE ON SCHEMA tenant_catalogo TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA tenant_catalogo
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA tenant_catalogo
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";


-- ============================================================
-- TABELA: ativo.empreendimentos          (contrato §8.1)
-- Agrupador PURO de ativos do tenant. Sem ficha, sem motor.
-- Relatório consolidado = WHERE emp_id = X.
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.empreendimentos (
    emp_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_tenant_uuid     UUID    NOT NULL,                  -- RAIZ de isolamento. [VALIDAR] sem FK física (hub é banco externo).
    emp_codigo_interno  TEXT,                              -- código próprio do tenant (nullable)
    emp_nome            TEXT    NOT NULL,
    emp_descricao       TEXT,
    emp_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    emp_atualizado_em   TIMESTAMPTZ,
    emp_criado_por      TEXT,
    emp_atualizado_por  TEXT,

    CONSTRAINT ck_empreendimentos_nome_vazio
        CHECK (btrim(emp_nome) <> '')
);

CREATE INDEX ix_empreendimentos_tenant
    ON ativo.empreendimentos (emp_tenant_uuid);


-- ============================================================
-- TABELA: ativo.ativos                    (contrato §8.2)
-- O objeto técnico real (obra/projeto/edificação/contrato).
-- Núcleo ao qual TUDO se conecta. Pertence a 0..1 empreendimento.
--
-- atv_tenant_uuid: SEMPRE preenchido. A Axys tem tenant próprio (role interna) —
--   modelos do "catálogo de ativos" são ativos desse tenant, não linhas órfãs.
-- atv_is_catalog_source: marca um ativo como FONTE do catálogo de ativos (modelo/
--   template que alimenta o gerador por drivers). Default FALSE. Um ativo comum
--   do tenant nasce FALSE; a Axys (ou futuramente o próprio tenant) marca TRUE
--   para reusá-lo como modelo. Decisão "árvore única": modelo = ativo, sem schema
--   espelhado nem duplicação de tabela.
-- Documentação do ativo (repo-paradigma): NÃO fica em JSONB de cabeçalho (lição do
--   Catálogo: ins_external_path virou dívida → migrou p/ registro catalogo.documentos).
--   Fica em TABELA dedicada ativo.ativo_diversidades_catalog (registro real, sem NULLs).
--   Ver §DOCUMENTOS / DIVERSIDADES adiante.
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.ativos (
    atv_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atv_tenant_uuid     UUID    NOT NULL,                  -- RAIZ de isolamento (inclui o tenant interno da Axys). [VALIDAR] sem FK física.
    atv_emp_id          INTEGER,                           -- 0..1 empreendimento; NULL = obra avulsa
    atv_is_catalog_source BOOLEAN NOT NULL DEFAULT FALSE,  -- TRUE = modelo/fonte do catálogo de ativos (drivers)
    atv_codigo_interno  TEXT,
    atv_tipo            TEXT,                              -- vertical/natureza (obra, projeto, edificação, contrato…)
    atv_nome            TEXT    NOT NULL,
    atv_status          TEXT    NOT NULL DEFAULT 'RASCUNHO',-- rascunho/ativo/arquivado…
    atv_uf              CHAR(2),                           -- UF default (sobreposta no contexto de preço)
    atv_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atv_atualizado_em   TIMESTAMPTZ,
    atv_criado_por      TEXT,
    atv_atualizado_por  TEXT,

    CONSTRAINT fk_ativos_emp
        FOREIGN KEY (atv_emp_id)
        REFERENCES ativo.empreendimentos (emp_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT ck_ativos_nome_vazio
        CHECK (btrim(atv_nome) <> '')
);

CREATE INDEX ix_ativos_tenant
    ON ativo.ativos (atv_tenant_uuid);
CREATE INDEX ix_ativos_emp
    ON ativo.ativos (atv_emp_id);
-- localizar rapidamente os modelos/fontes do catálogo de ativos
CREATE INDEX ix_ativos_catalog_source
    ON ativo.ativos (atv_is_catalog_source)
    WHERE atv_is_catalog_source;


-- ============================================================
-- TABELA: ativo.ativo_ficha_tecnica       (contrato §8.3)
-- Cabeçalho da ficha (1:1 lógico com ativo). Ponto de entrada
-- para parâmetros + atributos (NÃO é tabela de N colunas físicas).
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.ativo_ficha_tecnica (
    ficha_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ficha_atv_id        INTEGER NOT NULL,
    ficha_versao        INTEGER NOT NULL DEFAULT 1,
    ficha_status        TEXT    NOT NULL DEFAULT 'RASCUNHO',
    ficha_criado_em     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ficha_atualizado_em TIMESTAMPTZ,
    ficha_criado_por    TEXT,
    ficha_atualizado_por TEXT,

    CONSTRAINT fk_ficha_atv
        FOREIGN KEY (ficha_atv_id)
        REFERENCES ativo.ativos (atv_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_ficha_atv_versao
        UNIQUE (ficha_atv_id, ficha_versao)
);

CREATE INDEX ix_ficha_atv
    ON ativo.ativo_ficha_tecnica (ficha_atv_id);


-- ============================================================
-- TABELA: ativo.ficha_parametros          (contrato §8.4)
-- LOOKUP/tipo de parâmetro (mesmo padrão de ativo_diversidades_tipo_catalog):
-- vocabulário GLOBAL (semeado pela Axys), entrada que os DRIVERS leem. Cresce por
-- INSERT (é dado/vocabulário curado, não schema). SEM par_tenant_uuid (é p/ todos)
-- e SEM par_meta_json (evoluir = migration, não JSON) — decisão Renan 2026-06-14.
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.ficha_parametros (
    par_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    par_grupo           TEXT    NOT NULL,                  -- AREA, ESTRUTURA, HIDRO…
    par_codigo          TEXT    NOT NULL,                  -- AREA_TERRENO, QTD_SANITARIOS, TEM_SPDA…
    par_descricao       TEXT    NOT NULL,
    par_tipo            TEXT    NOT NULL,                  -- NUMERO | TEXTO | BOOL | DATA | LISTA
    par_unidade         TEXT,                              -- m², un… quando aplicável
    par_ordem           INTEGER NOT NULL DEFAULT 1000,
    par_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    par_atualizado_em   TIMESTAMPTZ,
    par_criado_por      TEXT,
    par_atualizado_por  TEXT,

    CONSTRAINT ck_par_tipo
        CHECK (par_tipo IN ('NUMERO', 'TEXTO', 'BOOL', 'DATA', 'LISTA')),
    CONSTRAINT uq_par_codigo
        UNIQUE (par_codigo)
);

CREATE INDEX ix_par_grupo
    ON ativo.ficha_parametros (par_grupo, par_ordem);


-- ============================================================
-- TABELA: ativo.ficha_atributos           (contrato §8.5)
-- Valores preenchidos por ativo. VALOR EM COLUNAS TIPADAS (indexável),
-- nunca tudo em JSON. Filtragem analítica = view pivotada (não EAV no OLTP).
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.ficha_atributos (
    atr_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atr_ficha_id        INTEGER NOT NULL,
    atr_par_id          INTEGER NOT NULL,
    atr_valor_numero    NUMERIC(18,6),
    atr_valor_texto     TEXT,
    atr_valor_bool      BOOLEAN,
    atr_valor_data      DATE,
    atr_meta_json       JSONB,                             -- só o genuinamente livre (lista/payload de driver)
    atr_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atr_atualizado_em   TIMESTAMPTZ,
    atr_criado_por      TEXT,
    atr_atualizado_por  TEXT,

    CONSTRAINT fk_atr_ficha
        FOREIGN KEY (atr_ficha_id)
        REFERENCES ativo.ativo_ficha_tecnica (ficha_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_atr_par
        FOREIGN KEY (atr_par_id)
        REFERENCES ativo.ficha_parametros (par_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_atr_ficha_par
        UNIQUE (atr_ficha_id, atr_par_id),
    CONSTRAINT ck_atr_meta_obj
        CHECK (atr_meta_json IS NULL OR jsonb_typeof(atr_meta_json) = 'object')
);

CREATE INDEX ix_atr_ficha
    ON ativo.ficha_atributos (atr_ficha_id);
CREATE INDEX ix_atr_par
    ON ativo.ficha_atributos (atr_par_id);


-- ============================================================
-- TABELA: ativo.ativo_itens               (contrato §8.6)  ★ CORAÇÃO ★
-- Árvore canônica: parent_id + ordem ESPARSA + path. Numeração 1.2.3 é
-- RENDER, não dado. NÃO carrega tenant_uuid (deriva via ati_atv_id).
--
-- PREÇO NÃO É COLUNA AQUI. O item guarda o VÍNCULO (origem + cmp_id + qtd)
-- e a camada de AJUSTE reversível (ati_ajuste_json). Custo resolve ao vivo
-- contra a edição do contexto (orcamento_parametros). Sem ati_custo_base.
--
-- ati_cmp_origem: discriminador da FK polimórfica da composição.
--   CATALOGO → catalogo.composicoes | TENANT → tenant_catalogo.composicoes
--   | LOCAL → ativo.orcamento_composicoes (fork). FK resolvida pelo app, NÃO
--   pelo banco (polimórfica). NULL = linha estrutural sem composição.
--
-- Vínculo item↔driver: NÃO é coluna aqui (evita zilhão de NULLs). É a tabela-ponte
--   ativo.ativo_itens_drivers (N:N) — só existe linha quando o item TEM driver.
--   Ver §CATÁLOGO DE ATIVOS / DRIVERS adiante.
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.ativo_itens (
    ati_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ati_atv_id          INTEGER NOT NULL,
    ati_parent_id       INTEGER,                           -- pai na árvore; NULL = raiz. PROFUNDIDADE vem daqui.
    ati_ordem           INTEGER NOT NULL,                  -- ordem ESPARSA entre irmãos (1000, 2000…)
    ati_path            TEXT    NOT NULL,                  -- "0001.0002.0001" — DERIVADO; p/ ORDER BY e descendência
    ati_tipo            TEXT    NOT NULL,                  -- GRUPO | SERVIÇO | SUBTOTAL | TEXTO | OBSERVAÇÃO…
    ati_descricao       TEXT,
    ati_cmp_origem      TEXT,                              -- 'CATALOGO' | 'TENANT' | 'LOCAL' | NULL
    ati_cmp_id          INTEGER,                           -- id da composição NA origem (FK polimórfica via app)
    ati_quantidade      NUMERIC(18,6),                     -- derivada da memória se houver; senão digitada
    ati_unidade         TEXT,
    ati_bdi_id          INTEGER,                           -- BDI da linha (FK ativo_bdi; NULL em título/não-precificável). FK via ALTER (ver §BDI)
    ati_ajuste_json     JSONB,                             -- camada de ajuste REVERSÍVEL sobre o preço resolvido (§10)
    ati_have_memory_calc BOOLEAN NOT NULL DEFAULT FALSE,   -- qtd vem de memória (true) ou digitação (false)
    ati_regras_json     JSONB,                             -- metadados por tipo de linha
    ati_meta_json       JSONB,
    ati_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ati_atualizado_em   TIMESTAMPTZ,
    ati_criado_por      TEXT,
    ati_atualizado_por  TEXT,

    CONSTRAINT fk_ati_atv
        FOREIGN KEY (ati_atv_id)
        REFERENCES ativo.ativos (atv_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_ati_parent
        FOREIGN KEY (ati_parent_id)
        REFERENCES ativo.ativo_itens (ati_id)
        ON UPDATE CASCADE ON DELETE CASCADE,  -- deletar nó = deletar subárvore (primitiva "deletar")

    CONSTRAINT ck_ati_tipo
        CHECK (ati_tipo IN ('GRUPO', 'SERVIÇO', 'SUBTOTAL', 'TEXTO', 'OBSERVAÇÃO')),
    CONSTRAINT ck_ati_cmp_origem
        CHECK (ati_cmp_origem IS NULL OR ati_cmp_origem IN ('CATALOGO', 'TENANT', 'LOCAL')),
    -- coerência vínculo: origem e id andam juntos (ambos nulos ou ambos preenchidos)
    CONSTRAINT ck_ati_cmp_par
        CHECK ( (ati_cmp_origem IS NULL     AND ati_cmp_id IS NULL)
             OR (ati_cmp_origem IS NOT NULL AND ati_cmp_id IS NOT NULL) ),
    CONSTRAINT ck_ati_ajuste_obj
        CHECK (ati_ajuste_json IS NULL OR jsonb_typeof(ati_ajuste_json) = 'object'),
    -- não há dois irmãos com a mesma ordem sob o mesmo pai (no mesmo ativo)
    CONSTRAINT uq_ati_irmaos_ordem
        UNIQUE (ati_atv_id, ati_parent_id, ati_ordem)
);

-- leitura ordenada da árvore inteira de um ativo (ORDER BY ati_path)
CREATE INDEX ix_ati_atv_path
    ON ativo.ativo_itens (ati_atv_id, ati_path);
-- filhos diretos
CREATE INDEX ix_ati_parent
    ON ativo.ativo_itens (ati_parent_id);
-- descendência por prefixo de path (LIKE 'x.%')
CREATE INDEX ix_ati_atv_path_text
    ON ativo.ativo_itens (ati_atv_id, ati_path text_pattern_ops);


-- ============================================================
-- TABELA: ativo.orcamento_parametros      (contrato §8.7)
-- CONTEXTO de preço por fonte. ROTACIONÁVEL: trocar opa_edicao_id re-resolve
-- todo o orçamento sem tocar item algum.
-- LS saiu daqui → ativo.ativo_ls (ÚNICA por obra). BDI saiu daqui → ativo.ativo_bdi
--   (1+ por obra) + ati_bdi_id por linha. Decisão Renan 2026-06-14.
-- [VALIDAR] opa_modalidade (SD/CD) pode ser redundante com ativo_ls.als_tipo
--   (ONERADA/DESONERADA = obra-level); manter por ora, reavaliar na implementação.
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.orcamento_parametros (
    opa_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opa_atv_id          INTEGER NOT NULL,
    opa_fonte           TEXT    NOT NULL,                  -- SINAPI | CDHU | TENANT…
    opa_edicao_id       INTEGER,                           -- edição-base (catalogo.edicoes). NULL p/ fonte TENANT.
    opa_uf              CHAR(2) NOT NULL DEFAULT 'SP',
    opa_modalidade      TEXT    NOT NULL DEFAULT 'SD',      -- SD | CD | SE  [VALIDAR vs ativo_ls.als_tipo]
    opa_default         BOOLEAN NOT NULL DEFAULT FALSE,    -- contexto inicial herdado na criação
    opa_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    opa_atualizado_em   TIMESTAMPTZ,
    opa_criado_por      TEXT,
    opa_atualizado_por  TEXT,

    CONSTRAINT fk_opa_atv
        FOREIGN KEY (opa_atv_id)
        REFERENCES ativo.ativos (atv_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_opa_edicao
        FOREIGN KEY (opa_edicao_id)
        REFERENCES catalogo.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_opa_modalidade
        CHECK (opa_modalidade IN ('SD', 'CD', 'SE')),
    -- um contexto por (ativo, fonte)
    CONSTRAINT uq_opa_atv_fonte
        UNIQUE (opa_atv_id, opa_fonte)
);

-- no máximo UM contexto default por ativo
CREATE UNIQUE INDEX uq_opa_um_default
    ON ativo.orcamento_parametros (opa_atv_id)
    WHERE opa_default;

CREATE INDEX ix_opa_atv
    ON ativo.orcamento_parametros (opa_atv_id);


-- ============================================================
-- TABELA: ativo.orcamento_composicoes / _itens   (contrato §8.8)
-- Fork LOCAL por exceção: só existe quando o usuário altera uma composição
-- naquele orçamento. Espelha a forma de catalogo.composicoes(_itens), isolado.
-- Referenciada por ativo_itens via ati_cmp_origem='LOCAL'.
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.orcamento_composicoes (
    ocp_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ocp_atv_id          INTEGER NOT NULL,
    ocp_origem_ref      TEXT,                              -- origem+código original (rastreio do fork)
    ocp_codigo          TEXT    NOT NULL,
    ocp_descricao       TEXT,                              -- pode divergir do original (motivo do fork)
    ocp_unidade         TEXT,
    ocp_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ocp_atualizado_em   TIMESTAMPTZ,
    ocp_criado_por      TEXT,
    ocp_atualizado_por  TEXT,

    CONSTRAINT fk_ocp_atv
        FOREIGN KEY (ocp_atv_id)
        REFERENCES ativo.ativos (atv_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_ocp_atv_codigo
        UNIQUE (ocp_atv_id, ocp_codigo)
);

CREATE INDEX ix_ocp_atv
    ON ativo.orcamento_composicoes (ocp_atv_id);

CREATE TABLE IF NOT EXISTS ativo.orcamento_composicoes_itens (
    oci_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oci_ocp_id          INTEGER NOT NULL,
    oci_ref_origem      TEXT    NOT NULL,                  -- 'CATALOGO' | 'TENANT' | 'LOCAL' (onde vive o filho)
    oci_ref_tipo        TEXT    NOT NULL,                  -- 'INSUMO' | 'COMPOSICAO' (o que é o filho)
    oci_ref_id          INTEGER NOT NULL,                  -- id na origem+tipo (FK polimórfica via app)
    oci_coeficiente     NUMERIC(14,10) NOT NULL,           -- consumo/coeficiente na receita
    oci_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    oci_atualizado_em   TIMESTAMPTZ,
    oci_criado_por      TEXT,
    oci_atualizado_por  TEXT,

    CONSTRAINT fk_oci_ocp
        FOREIGN KEY (oci_ocp_id)
        REFERENCES ativo.orcamento_composicoes (ocp_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_oci_ref_origem
        CHECK (oci_ref_origem IN ('CATALOGO', 'TENANT', 'LOCAL')),
    CONSTRAINT ck_oci_ref_tipo
        CHECK (oci_ref_tipo IN ('INSUMO', 'COMPOSICAO'))
);

CREATE INDEX ix_oci_ocp
    ON ativo.orcamento_composicoes_itens (oci_ocp_id);


-- ============================================================
-- TABELA: ativo.orcamento_insumos / _preco       (contrato §8.9)
-- Fork LOCAL de insumo. Situação CHECK-text coerente com a doutrina do Catálogo
-- (null = sem preço). Referenciado por origem='LOCAL'.
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.orcamento_insumos (
    oin_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oin_atv_id          INTEGER NOT NULL,
    oin_origem_ref      TEXT,                              -- origem+código original (rastreio)
    oin_descricao       TEXT,
    oin_unidade         TEXT,
    oin_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    oin_atualizado_em   TIMESTAMPTZ,
    oin_criado_por      TEXT,
    oin_atualizado_por  TEXT,

    CONSTRAINT fk_oin_atv
        FOREIGN KEY (oin_atv_id)
        REFERENCES ativo.ativos (atv_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX ix_oin_atv
    ON ativo.orcamento_insumos (oin_atv_id);

CREATE TABLE IF NOT EXISTS ativo.orcamento_insumos_preco (
    oip_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oip_oin_id          INTEGER NOT NULL,
    oip_uf              CHAR(2) NOT NULL DEFAULT 'SP',
    oip_preco           NUMERIC(14,4),                     -- null = sem preço
    oip_situacao        TEXT,                              -- 'COM PREÇO' | 'SEM PREÇO' (null = sem preço)
    oip_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    oip_atualizado_em   TIMESTAMPTZ,
    oip_criado_por      TEXT,
    oip_atualizado_por  TEXT,

    CONSTRAINT fk_oip_oin
        FOREIGN KEY (oip_oin_id)
        REFERENCES ativo.orcamento_insumos (oin_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_oip_situacao
        CHECK (oip_situacao IS NULL OR oip_situacao IN ('COM PREÇO', 'SEM PREÇO')),
    CONSTRAINT uq_oip_oin_uf
        UNIQUE (oip_oin_id, oip_uf)
);

CREATE INDEX ix_oip_oin
    ON ativo.orcamento_insumos_preco (oip_oin_id);


-- ============================================================
-- TABELA: ativo.memo_calc / memo_calc_item       (contrato §8.10)
-- Memória de cálculo. DUAS origens, MESMO schema (consistência — decisão Renan 2026-06-14):
--   • PLUGIN/API (CAD/RVT/IFC): VERDADE = mc_json_cru (payload bruto); itens parseados.
--   • MANUAL (usuário digita): mc_json_cru NULL; VERDADE = os memo_calc_item digitados.
-- Um registro por import/lançamento; um filho por bloco/coletor/linha. SEM tabela de
-- entidades nem overlays relacionais (overlay é DERIVADO no viewer).
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.memo_calc (
    mc_id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mc_atv_id           INTEGER NOT NULL,
    mc_origem           TEXT    NOT NULL,                  -- VIA PLUGIN/API: 'CAD'|'RVT'|'IFC' | DIGITADA: 'MANUAL'. platform fica no json_cru (axysCAD §1.2)
    mc_arquivo          TEXT,                              -- source.file_name (plugin); NULL no MANUAL
    mc_hash             TEXT,                              -- checksum p/ provenance (plugin); NULL no MANUAL
    mc_json_cru         JSONB,                             -- payload axys-cad-v1 bruto = verdade (plugin). NULL no MANUAL (verdade = os memo_calc_item digitados)
    mc_importado_em     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mc_importado_por    TEXT,

    CONSTRAINT fk_mc_atv
        FOREIGN KEY (mc_atv_id)
        REFERENCES ativo.ativos (atv_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_mc_origem
        CHECK (mc_origem IN ('CAD', 'RVT', 'IFC', 'MANUAL')),
    CONSTRAINT ck_mc_json_obj
        CHECK (mc_json_cru IS NULL OR jsonb_typeof(mc_json_cru) = 'object'),
    -- plugin/API SEMPRE traz o payload bruto; MANUAL não tem payload (digitação é a verdade)
    CONSTRAINT ck_mc_json_por_origem
        CHECK (mc_origem = 'MANUAL' OR mc_json_cru IS NOT NULL),
    -- UPSERT idempotente por arquivo (axysCAD §9: reenviar o mesmo arquivo sobrescreve).
    -- MANUAL tem mc_arquivo NULL → NULLs não colidem (vários memos manuais por ativo OK).
    CONSTRAINT uq_mc_atv_arquivo
        UNIQUE (mc_atv_id, mc_arquivo)
);

CREATE INDEX ix_mc_atv
    ON ativo.memo_calc (mc_atv_id);

-- Colunas alinhadas ao mapeamento axysCAD §8 (1 captura → 1 memo_calc_item) quando
-- via plugin; no MANUAL o usuário digita codigo/nome/unidade/qtd e as colunas de
-- plugin (capture_id, collector, quantity_type, coeficiente, entidades) ficam NULL.
-- mci_codigo ← friendly_name (slug/agrupador); mci_nome_amigavel ← name (rótulo livre).
CREATE TABLE IF NOT EXISTS ativo.memo_calc_item (
    mci_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mci_mc_id           INTEGER NOT NULL,
    mci_capture_id      TEXT,                              -- capture_id do JSON (identidade p/ sync granular / SUPERSEDED)
    mci_codigo          TEXT    NOT NULL,                  -- friendly_name — slug/agrupador (junção semântica c/ o item)
    mci_nome_amigavel   TEXT,                              -- name — rótulo livre do orçamentista
    mci_local           TEXT,                              -- location_or_floor — âncora de localização (axysCAD: obrigatório)
    mci_collector       TEXT,                              -- AXUNIT | AXCOMP | AXAREA | AXVOL | AXTEXT
    mci_quantity_type   TEXT,                              -- UNIT | LENGTH | AREA | VOLUME | TEXT_VALUE (1:1 c/ collector)
    mci_metodo          TEXT,                              -- method do coletor (selection_count, entity_area_sum…)
    mci_unidade         TEXT,
    mci_qtd_calculada   NUMERIC(18,6) NOT NULL,            -- AUTORIDADE sobre o número (não recalcula das entidades)
    mci_coeficiente_json JSONB,                            -- coefficient {type,value,unit} (só AXVOL hoje; forma evolui sem ALTER)
    mci_entidades_consideradas JSONB,                      -- entities[] — evidência (handle/type/layer/coords). Prova, não fonte.
    mci_status          TEXT    NOT NULL DEFAULT 'SYNCED', -- SYNCED | SUPERSEDED (re-levantamento preserva histórico — axysCAD §9)
    mci_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mci_atualizado_em   TIMESTAMPTZ,
    mci_criado_por      TEXT,
    mci_atualizado_por  TEXT,

    CONSTRAINT fk_mci_mc
        FOREIGN KEY (mci_mc_id)
        REFERENCES ativo.memo_calc (mc_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_mci_collector
        CHECK (mci_collector IS NULL OR mci_collector IN ('AXUNIT','AXCOMP','AXAREA','AXVOL','AXTEXT')),
    CONSTRAINT ck_mci_qtype
        CHECK (mci_quantity_type IS NULL OR mci_quantity_type IN ('UNIT','LENGTH','AREA','VOLUME','TEXT_VALUE')),
    CONSTRAINT ck_mci_status
        CHECK (mci_status IN ('SYNCED', 'SUPERSEDED')),
    CONSTRAINT ck_mci_coef_obj
        CHECK (mci_coeficiente_json IS NULL OR jsonb_typeof(mci_coeficiente_json) = 'object')
);

CREATE INDEX ix_mci_mc
    ON ativo.memo_calc_item (mci_mc_id);
CREATE INDEX ix_mci_codigo
    ON ativo.memo_calc_item (mci_codigo);
CREATE INDEX ix_mci_capture
    ON ativo.memo_calc_item (mci_capture_id);


-- ============================================================
-- TABELA: ativo.memo_item_link            (contrato §8.11)
-- Ponte N:N (faz ABERTO e FECHADO caberem no mesmo schema). Item soma vários
-- blocos; bloco GLOBAL alimenta vários itens.
-- Quantidade do item = Σ mci_qtd_calculada dos blocos linkados (quando have_memory_calc).
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.memo_item_link (
    mil_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mil_mci_id          INTEGER NOT NULL,
    mil_ati_id          INTEGER NOT NULL,
    mil_tipo            TEXT    NOT NULL,                  -- 'DIRECIONADO' | 'GLOBAL'
    mil_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mil_criado_por      TEXT,

    CONSTRAINT fk_mil_mci
        FOREIGN KEY (mil_mci_id)
        REFERENCES ativo.memo_calc_item (mci_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_mil_ati
        FOREIGN KEY (mil_ati_id)
        REFERENCES ativo.ativo_itens (ati_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_mil_tipo
        CHECK (mil_tipo IN ('DIRECIONADO', 'GLOBAL')),
    CONSTRAINT uq_mil_mci_ati
        UNIQUE (mil_mci_id, mil_ati_id)
);

CREATE INDEX ix_mil_ati
    ON ativo.memo_item_link (mil_ati_id);
CREATE INDEX ix_mil_mci
    ON ativo.memo_item_link (mil_mci_id);


-- ============================================================
-- TABELA: ativo.ativo_revisoes            (contrato §8.12)
-- Estado vivo + revisões CONGELADAS. NÃO espelha 7 tabelas-gêmeas:
-- a foto fiel vive em rev_snapshot_json; o que se consulta vive em rev_resumo_json.
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.ativo_revisoes (
    rev_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_atv_id          INTEGER NOT NULL,
    rev_codigo          TEXT    NOT NULL,                  -- R01, R02…
    rev_status          TEXT    NOT NULL DEFAULT 'EMITIDA', -- emitida/arquivada…
    rev_data            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rev_autor           TEXT,
    rev_snapshot_json   JSONB   NOT NULL,                  -- FOTO write-once (orçamento+composições+preços+memória+params)
    rev_resumo_json     JSONB,                             -- resumo denormalizado (totais, ABC) — consulta/diff barato

    CONSTRAINT fk_rev_atv
        FOREIGN KEY (rev_atv_id)
        REFERENCES ativo.ativos (atv_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_rev_atv_codigo
        UNIQUE (rev_atv_id, rev_codigo),
    CONSTRAINT ck_rev_snapshot_obj
        CHECK (jsonb_typeof(rev_snapshot_json) = 'object'),
    CONSTRAINT ck_rev_resumo_obj
        CHECK (rev_resumo_json IS NULL OR jsonb_typeof(rev_resumo_json) = 'object')
);

CREATE INDEX ix_rev_atv
    ON ativo.ativo_revisoes (rev_atv_id);


-- ============================================================
-- TABELA: ativo.ativo_eventos             (contrato §8.13)
-- Trilha de eventos estruturais/negócio (criar, mover, indentar, emitir
-- revisão, rotacionar edição…). Auditoria FORMAL continua no schema audit —
-- isto é trilha de domínio.
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.ativo_eventos (
    evt_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evt_atv_id          INTEGER NOT NULL,
    evt_tipo            TEXT    NOT NULL,
    evt_payload_json    JSONB,
    evt_em              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    evt_por             TEXT,

    CONSTRAINT fk_evt_atv
        FOREIGN KEY (evt_atv_id)
        REFERENCES ativo.ativos (atv_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_evt_payload_obj
        CHECK (evt_payload_json IS NULL OR jsonb_typeof(evt_payload_json) = 'object')
);

CREATE INDEX ix_evt_atv
    ON ativo.ativo_eventos (evt_atv_id, evt_em);


-- ============================================================
-- §BDI E LEIS SOCIAIS  (decisão Renan 2026-06-14, ponto #5.b)
-- BDI: COMPOSTO (header + parcelas) e MÚLTIPLO por obra (1+). tipo ONERADO/
--   DESONERADO/REDUZIDO (normal onerado/desonerado + reduzido p/ equipamento).
--   CADA linha do orçamento recebe um BDI (ati_bdi_id). Default por obra (abd_default).
-- LS: COMPOSTA (header + parcelas) e ÚNICA por obra (1). tipo ONERADA/DESONERADA.
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.ativo_bdi (
    abd_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abd_atv_id          INTEGER NOT NULL,
    abd_tipo            TEXT    NOT NULL,                  -- ONERADO | DESONERADO | REDUZIDO
    abd_nome            TEXT,
    abd_percent         NUMERIC(8,4),                      -- BDI resultante (%), calculado das parcelas
    abd_default         BOOLEAN NOT NULL DEFAULT FALSE,    -- BDI padrão da obra (aplicado por default às linhas)
    abd_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    abd_atualizado_em   TIMESTAMPTZ,
    abd_criado_por      TEXT,
    abd_atualizado_por  TEXT,

    CONSTRAINT fk_abd_atv
        FOREIGN KEY (abd_atv_id)
        REFERENCES ativo.ativos (atv_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_abd_tipo
        CHECK (abd_tipo IN ('ONERADO', 'DESONERADO', 'REDUZIDO'))
);

CREATE INDEX ix_abd_atv
    ON ativo.ativo_bdi (abd_atv_id);
-- no máximo UM BDI default por obra
CREATE UNIQUE INDEX uq_abd_um_default
    ON ativo.ativo_bdi (abd_atv_id)
    WHERE abd_default;

CREATE TABLE IF NOT EXISTS ativo.ativo_bdi_composicao (
    abdc_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abdc_abd_id         INTEGER NOT NULL,
    abdc_parcela        TEXT    NOT NULL,                  -- ADM_CENTRAL | LUCRO | RISCO | DESP_FINANCEIRA | TRIBUTOS | SEGURO_GARANTIA…
    abdc_descricao      TEXT,
    abdc_percent        NUMERIC(8,4) NOT NULL,
    abdc_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    abdc_atualizado_em  TIMESTAMPTZ,
    abdc_criado_por     TEXT,
    abdc_atualizado_por TEXT,

    CONSTRAINT fk_abdc_abd
        FOREIGN KEY (abdc_abd_id)
        REFERENCES ativo.ativo_bdi (abd_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX ix_abdc_abd
    ON ativo.ativo_bdi_composicao (abdc_abd_id);

-- FK ati_bdi_id → ativo_bdi (via ALTER por causa da ordem de criação).
-- ON DELETE SET NULL: apagar um BDI não apaga linhas; elas ficam sem BDI até reatribuir.
ALTER TABLE ativo.ativo_itens
    ADD CONSTRAINT fk_ati_bdi
    FOREIGN KEY (ati_bdi_id)
    REFERENCES ativo.ativo_bdi (abd_id)
    ON UPDATE CASCADE ON DELETE SET NULL;

CREATE INDEX ix_ati_bdi
    ON ativo.ativo_itens (ati_bdi_id)
    WHERE ati_bdi_id IS NOT NULL;

-- ------------------------------------------------------------
-- Leis Sociais — ÚNICA por obra (header + parcelas)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ativo.ativo_ls (
    als_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    als_atv_id          INTEGER NOT NULL,
    als_tipo            TEXT    NOT NULL,                  -- ONERADA | DESONERADA
    als_percent_horista     NUMERIC(8,4),                  -- LS resultante (%) p/ horista
    als_percent_mensalista  NUMERIC(8,4),                  -- LS resultante (%) p/ mensalista
    als_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    als_atualizado_em   TIMESTAMPTZ,
    als_criado_por      TEXT,
    als_atualizado_por  TEXT,

    CONSTRAINT fk_als_atv
        FOREIGN KEY (als_atv_id)
        REFERENCES ativo.ativos (atv_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_als_tipo
        CHECK (als_tipo IN ('ONERADA', 'DESONERADA')),
    CONSTRAINT uq_als_atv
        UNIQUE (als_atv_id)                                -- ÚNICA por obra
);

CREATE TABLE IF NOT EXISTS ativo.ativo_ls_composicao (
    alsc_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alsc_als_id         INTEGER NOT NULL,
    alsc_grupo          TEXT,                              -- A | B | C | D (grupos da planilha de LS)
    alsc_codigo         TEXT,                              -- A1, A2, B1… (INSS, SESI…)
    alsc_descricao      TEXT,
    alsc_percent_horista     NUMERIC(8,4),
    alsc_percent_mensalista  NUMERIC(8,4),
    alsc_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    alsc_atualizado_em  TIMESTAMPTZ,
    alsc_criado_por     TEXT,
    alsc_atualizado_por TEXT,

    CONSTRAINT fk_alsc_als
        FOREIGN KEY (alsc_als_id)
        REFERENCES ativo.ativo_ls (als_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX ix_alsc_als
    ON ativo.ativo_ls_composicao (alsc_als_id);


-- ============================================================
-- §CRONOGRAMA físico-financeiro  (decisão Renan 2026-06-14, ponto #5.c)
-- Fasiamento do valor por PERÍODO. Feito por NÍVEL, até o limite n-1 do orçamento
-- (parou no nível 5 → cronograma vai até nível 4; normalmente nível 3): tudo abaixo
-- do "guarda-chuva" (o item do nível de corte) segue o padrão dele.
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.cronograma (
    cro_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cro_atv_id          INTEGER NOT NULL,
    cro_nome            TEXT,
    cro_prazo_dias      INTEGER,                           -- prazo total (ex.: 360)
    cro_periodo_dias    INTEGER NOT NULL DEFAULT 30,       -- tamanho do período (ex.: 30)
    cro_num_periodos    INTEGER,                           -- nº de períodos (ex.: 12)
    cro_nivel_corte     INTEGER,                           -- nível do "guarda-chuva" (≤ n-1)
    cro_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cro_atualizado_em   TIMESTAMPTZ,
    cro_criado_por      TEXT,
    cro_atualizado_por  TEXT,

    CONSTRAINT fk_cro_atv
        FOREIGN KEY (cro_atv_id)
        REFERENCES ativo.ativos (atv_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX ix_cro_atv
    ON ativo.cronograma (cro_atv_id);

CREATE TABLE IF NOT EXISTS ativo.cronograma_itens (
    cri_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cri_cro_id          INTEGER NOT NULL,
    cri_ati_id          INTEGER NOT NULL,                  -- item no nível de corte
    cri_periodo         INTEGER NOT NULL,                  -- 1..cro_num_periodos
    cri_percent         NUMERIC(9,6) NOT NULL,             -- fração do valor do item neste período
    cri_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cri_atualizado_em   TIMESTAMPTZ,
    cri_criado_por      TEXT,
    cri_atualizado_por  TEXT,

    CONSTRAINT fk_cri_cro
        FOREIGN KEY (cri_cro_id)
        REFERENCES ativo.cronograma (cro_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_cri_ati
        FOREIGN KEY (cri_ati_id)
        REFERENCES ativo.ativo_itens (ati_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_cri_cro_ati_periodo
        UNIQUE (cri_cro_id, cri_ati_id, cri_periodo)
);

CREATE INDEX ix_cri_cro
    ON ativo.cronograma_itens (cri_cro_id);
CREATE INDEX ix_cri_ati
    ON ativo.cronograma_itens (cri_ati_id);


-- ============================================================
-- §DOCUMENTOS / DIVERSIDADES DO ATIVO  (decisão Renan 2026-06-14)
-- Registro REAL (não JSONB de cabeçalho) dos documentos/peças que descrevem o ativo
-- — em especial o "repo-paradigma" dos modelos (is_catalog_source): arquivos que
-- mostram o que está orçado. Tabela enxuta, sem NULLs, refator barato. Mesma doutrina
-- do catalogo.documentos (que substituiu o ins_external_path JSONB).
-- [VALIDAR] sufixo "_catalog" (EN) vs "_catalogo" (PT, padrão do resto do banco).
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.ativo_diversidades_tipo_catalog (
    adt_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adt_codigo          TEXT    NOT NULL,                  -- código estável (ARQ, EST, ELE…)
    adt_descricao       TEXT    NOT NULL,                  -- rótulo (CAIXA ALTA — identidade)
    adt_ordem           INTEGER NOT NULL DEFAULT 1000,
    adt_ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    adt_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    adt_atualizado_em   TIMESTAMPTZ,
    adt_criado_por      TEXT,
    adt_atualizado_por  TEXT,

    CONSTRAINT uq_adt_codigo
        UNIQUE (adt_codigo),
    CONSTRAINT ck_adt_codigo_vazio
        CHECK (btrim(adt_codigo) <> ''),
    CONSTRAINT ck_adt_descricao_vazia
        CHECK (btrim(adt_descricao) <> '')
);

-- seed inicial (disciplinas de projeto) — CAIXA ALTA na identidade (feedback_caixa_alta_catalogo)
INSERT INTO ativo.ativo_diversidades_tipo_catalog (adt_codigo, adt_descricao, adt_ordem) VALUES
    ('ARQ', 'PROJETO ARQUITETÔNICO', 1000),
    ('EST', 'PROJETO ESTRUTURAL',    2000),
    ('ELE', 'PROJETO ELÉTRICO',      3000),
    ('HID', 'PROJETO HIDRÁULICO',    4000),
    ('MEC', 'PROJETO MECÂNICO',      5000),
    ('GAS', 'PROJETO GASES',         6000)
ON CONFLICT (adt_codigo) DO NOTHING;

-- ------------------------------------------------------------
-- TABELA: ativo.ativo_diversidades_catalog  (entradas por ativo)
-- Um documento/peça do ativo, tipado pela disciplina. Path no R2.
-- prefixo adc_ = Ativo Diversidade Catalog.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ativo.ativo_diversidades_catalog (
    adc_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adc_atv_id          INTEGER NOT NULL,                  -- ativo dono
    adc_adt_id          INTEGER NOT NULL,                  -- tipo/disciplina
    adc_descricao       TEXT,                              -- descrição da peça
    adc_path            TEXT,                              -- caminho no R2 (ou link)
    adc_ordem           INTEGER NOT NULL DEFAULT 1000,
    adc_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    adc_atualizado_em   TIMESTAMPTZ,
    adc_criado_por      TEXT,
    adc_atualizado_por  TEXT,

    CONSTRAINT fk_adc_atv
        FOREIGN KEY (adc_atv_id)
        REFERENCES ativo.ativos (atv_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_adc_adt
        FOREIGN KEY (adc_adt_id)
        REFERENCES ativo.ativo_diversidades_tipo_catalog (adt_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX ix_adc_atv
    ON ativo.ativo_diversidades_catalog (adc_atv_id, adc_ordem);
CREATE INDEX ix_adc_adt
    ON ativo.ativo_diversidades_catalog (adc_adt_id);


-- ============================================================
-- §CATÁLOGO DE ATIVOS / DRIVERS  (decisão 2026-06-14 — fora do contrato v0.2)
-- O gerador automatizado de orçamento é o produto vendável da Axys: a partir dos
-- PARÂMETROS da ficha (ficha_parametros/atributos) e de um MODELO (ativo com
-- atv_is_catalog_source=TRUE), DRIVERS calculam quantidades dos itens.
-- "Árvore única": o modelo é um ativo comum; gerar = copiar a subárvore do modelo
-- para o ativo do tenant + rodar os drivers contra a ficha dele.
--
-- drv_regra_json: [VALIDAR] formato da regra/fórmula (referencia par_codigo de
--   entrada → quantidade). Mantido JSONB p/ evoluir SEM ALTER (refator quase proibido).
-- drv_tenant_uuid NULL = driver GLOBAL (Axys, visível a todos); preenchido = driver
--   privado do tenant. (Driver É customizável por tenant — ao contrário de
--   ficha_parametros, que é vocabulário só-global.) [VALIDAR se tenant cria driver]
-- ============================================================
CREATE TABLE IF NOT EXISTS ativo.drivers (
    drv_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drv_tenant_uuid     UUID,                              -- NULL = global (Axys). [VALIDAR] sem FK física.
    drv_codigo          TEXT    NOT NULL,                  -- código estável do driver
    drv_nome            TEXT    NOT NULL,
    drv_descricao       TEXT,
    drv_tipo            TEXT,                              -- natureza da regra (FORMULA, LOOKUP…) — [VALIDAR]
    drv_unidade         TEXT,                              -- unidade da quantidade gerada
    drv_regra_json      JSONB,                             -- a regra/fórmula (entradas = par_codigo). [VALIDAR]
    drv_ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    drv_meta_json       JSONB,
    drv_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    drv_atualizado_em   TIMESTAMPTZ,
    drv_criado_por      TEXT,
    drv_atualizado_por  TEXT,

    CONSTRAINT uq_drivers_codigo_tenant
        UNIQUE (drv_tenant_uuid, drv_codigo),
    CONSTRAINT ck_drivers_regra_obj
        CHECK (drv_regra_json IS NULL OR jsonb_typeof(drv_regra_json) = 'object'),
    CONSTRAINT ck_drivers_meta_obj
        CHECK (drv_meta_json IS NULL OR jsonb_typeof(drv_meta_json) = 'object')
);

-- ------------------------------------------------------------
-- TABELA-PONTE: ativo.ativo_itens_drivers  (N:N item ↔ driver)
-- Só existe linha quando o item de modelo USA driver (sem NULLs em massa).
-- Um item pode somar vários drivers (alvenaria = área parede + área platibanda);
-- um driver pode servir a vários itens.
-- prefixo aid_ = Ativo Item Driver.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ativo.ativo_itens_drivers (
    aid_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aid_ati_id          INTEGER NOT NULL,
    aid_drv_id          INTEGER NOT NULL,
    aid_fator           NUMERIC(18,6),                     -- multiplicador opcional do driver neste item
    aid_meta_json       JSONB,                             -- parâmetros do vínculo (mapeamento de entradas etc.)
    aid_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    aid_atualizado_em   TIMESTAMPTZ,
    aid_criado_por      TEXT,
    aid_atualizado_por  TEXT,

    CONSTRAINT fk_aid_ati
        FOREIGN KEY (aid_ati_id)
        REFERENCES ativo.ativo_itens (ati_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_aid_drv
        FOREIGN KEY (aid_drv_id)
        REFERENCES ativo.drivers (drv_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_aid_ati_drv
        UNIQUE (aid_ati_id, aid_drv_id),
    CONSTRAINT ck_aid_meta_obj
        CHECK (aid_meta_json IS NULL OR jsonb_typeof(aid_meta_json) = 'object')
);

CREATE INDEX ix_aid_ati
    ON ativo.ativo_itens_drivers (aid_ati_id);
CREATE INDEX ix_aid_drv
    ON ativo.ativo_itens_drivers (aid_drv_id);


-- ============================================================
-- NAMESPACE RESERVADO (contrato §6 / §12) — NÃO CRIAR AGORA.
-- Cada microapp traz o próprio DDL no seu slot quando nascer:
--   ativo.ativo_docs    (Easy Docs)
--   ativo.ativo_pm      (Easy ProjectManager)
--   ativo.ativo_diario  (Easy BuildDiary)
--   ativo.ativo_fin     (Easy FinControl)
--   ativo.ativo_licit   (Easy LicitPlan)
--   ativo.ativo_repo    (Repositório de arquivos)
-- Namespace reservado ≠ tabela criada.
-- ============================================================


-- ============================================================
-- tenant_catalogo.*  (contrato §8.14 + decisão Renan 2026-06-14, ponto #6)
-- Biblioteca técnica do tenant, isolada por tenant_uuid (só na RAIZ).
-- REPLICAÇÃO MÍNIMA: insumos + insumos_preco + composicoes + composicoes_itens.
-- SEM composicoes_custo: custo de CPU do tenant é CALCULADO ao vivo (Σ coef × preço),
--   não armazenado (≠ catálogo global, que confere fonte×calculado).
-- A "BUCHA" (a.3): item de composição do tenant pode referenciar insumo OU composição,
--   vinda do CATÁLOGO GLOBAL ou do próprio TENANT → discriminadores ci_ref_origem +
--   ci_ref_tipo (FK polimórfica resolvida pelo app, sem FK física no filho).
-- ============================================================
CREATE TABLE IF NOT EXISTS tenant_catalogo.insumos (
    ins_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ins_tenant_uuid     UUID    NOT NULL,                  -- RAIZ de isolamento. [VALIDAR] sem FK física.
    ins_codigo          TEXT    NOT NULL,
    ins_descricao       TEXT    NOT NULL,
    ins_unidade         TEXT    NOT NULL,
    ins_ti_id           INTEGER NOT NULL,                  -- classificação (MO/MAT/EQUIP…) — FK ao lookup GLOBAL
    ins_ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    ins_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ins_atualizado_em   TIMESTAMPTZ,
    ins_criado_por      TEXT,
    ins_atualizado_por  TEXT,

    CONSTRAINT fk_tc_insumos_ti
        FOREIGN KEY (ins_ti_id)
        REFERENCES catalogo.insumos_tipo (ti_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_tc_insumos_tenant_codigo
        UNIQUE (ins_tenant_uuid, ins_codigo),
    CONSTRAINT ck_tc_insumos_codigo_vazio
        CHECK (btrim(ins_codigo) <> '')
);

CREATE INDEX ix_tc_insumos_tenant
    ON tenant_catalogo.insumos (ins_tenant_uuid, ins_ativo, ins_codigo);

CREATE TABLE IF NOT EXISTS tenant_catalogo.insumos_preco (
    pri_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pri_ins_id          INTEGER NOT NULL,
    pri_uf              CHAR(2) NOT NULL DEFAULT 'SP',
    pri_valor           NUMERIC(14,4),                     -- SE-only (pelado), doutrina do Catálogo; null = sem preço
    pri_situacao        TEXT,                              -- 'COM PREÇO' | 'SEM PREÇO' (null = sem preço)
    pri_origem          TEXT,                              -- procedência do preço: PROPRIA | PESQUISA | COTACAO… (cobre 5.a)
    pri_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pri_atualizado_em   TIMESTAMPTZ,
    pri_criado_por      TEXT,
    pri_atualizado_por  TEXT,

    CONSTRAINT fk_tc_pri_ins
        FOREIGN KEY (pri_ins_id)
        REFERENCES tenant_catalogo.insumos (ins_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_tc_pri_situacao
        CHECK (pri_situacao IS NULL OR pri_situacao IN ('COM PREÇO', 'SEM PREÇO')),
    CONSTRAINT uq_tc_pri_ins_uf
        UNIQUE (pri_ins_id, pri_uf)
);

CREATE INDEX ix_tc_pri_ins
    ON tenant_catalogo.insumos_preco (pri_ins_id);

CREATE TABLE IF NOT EXISTS tenant_catalogo.composicoes (
    cmp_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cmp_tenant_uuid     UUID    NOT NULL,                  -- RAIZ de isolamento. [VALIDAR] sem FK física.
    cmp_codigo          TEXT    NOT NULL,
    cmp_descricao       TEXT    NOT NULL,
    cmp_unidade         TEXT    NOT NULL,
    cmp_situacao        TEXT,                              -- CHECK-text (doutrina do Catálogo)
    cmp_ativa           BOOLEAN NOT NULL DEFAULT TRUE,
    cmp_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cmp_atualizado_em   TIMESTAMPTZ,
    cmp_criado_por      TEXT,
    cmp_atualizado_por  TEXT,

    CONSTRAINT uq_tc_cmp_tenant_codigo
        UNIQUE (cmp_tenant_uuid, cmp_codigo),
    CONSTRAINT ck_tc_cmp_codigo_vazio
        CHECK (btrim(cmp_codigo) <> '')
);

CREATE INDEX ix_tc_cmp_tenant
    ON tenant_catalogo.composicoes (cmp_tenant_uuid, cmp_ativa, cmp_codigo);

CREATE TABLE IF NOT EXISTS tenant_catalogo.composicoes_itens (
    ci_id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ci_cmp_id           INTEGER NOT NULL,                  -- composição-mãe (sempre do tenant)
    ci_ref_origem       TEXT    NOT NULL,                  -- 'CATALOGO' | 'TENANT' (onde vive o filho) — a.3
    ci_ref_tipo         TEXT    NOT NULL,                  -- 'INSUMO' | 'COMPOSICAO' (o que é o filho)  — a.3
    ci_ref_id           INTEGER NOT NULL,                  -- id na origem+tipo (FK polimórfica via app)
    ci_coeficiente      NUMERIC(14,10) NOT NULL,
    ci_situacao         TEXT,
    ci_criado_em        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ci_atualizado_em    TIMESTAMPTZ,
    ci_criado_por       TEXT,
    ci_atualizado_por   TEXT,

    CONSTRAINT fk_tc_ci_cmp
        FOREIGN KEY (ci_cmp_id)
        REFERENCES tenant_catalogo.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_tc_ci_ref_origem
        CHECK (ci_ref_origem IN ('CATALOGO', 'TENANT')),
    CONSTRAINT ck_tc_ci_ref_tipo
        CHECK (ci_ref_tipo IN ('INSUMO', 'COMPOSICAO'))
);

CREATE INDEX ix_tc_ci_cmp
    ON tenant_catalogo.composicoes_itens (ci_cmp_id);

-- (composicoes_custo do tenant NÃO existe — custo é calculado ao vivo. Ver header da seção.)

-- ============================================================
-- §ARQUIVAMENTO — desconstrução / reconstrução por tenant  [VALIDAR / pode virar contrato]
-- Problema: dados de orçamento de tenant SEM licença ativa há muito tempo não
-- podem ficar no banco quente (barato p/ 1, inviável p/ 10M). Evolui o backup R2 já
-- aprovado (memória project_audit_r2_backup) p/ ciclo por-tenant dirigido pelo Hub.
--
-- FRONTEIRA (X.2, decisão Renan): a REGRA/CONTEXTO/limites são do HUB. O Easy NÃO
-- conhece a regra — apenas EXECUTA quando chamado: (a) desconstruir(tenant) e
-- (b) reconstruir(tenant). O Hub documenta o ciclo do lado dele.
--
-- CICLO (serviço + Celery, não SQL puro):
--   1. DESCONSTRUÇÃO: Hub detecta tenant sem licença há > N dias (N em tabela do HUB)
--      → chama Easy → Celery async: SELECT de TODAS as tabelas do tenant (alcançáveis
--      via tenant_uuid nas raízes + FK) → BACKFILL JSON estruturado (mesmos nomes/roles
--      do banco) → grava no destino (R2 catalogado, ou schema frio) → DELETE do quente.
--   2. RECONSTRUÇÃO: Hub cobra e chama → Easy recarrega o backfill no quente.
--      PKs GENERATED BY DEFAULT permitem reinsert com id original (FKs preservadas).
--   3. RETENÇÃO: payloads guardados ~5 anos; não voltou, purga até de lá (gatilho do Hub).
--
-- POR QUE O SCHEMA JÁ SUPORTA: tenant_uuid só nas raízes + folhas por FK ⇒ recorte
-- por tenant é determinístico (sem rastrear tenant em toda folha). catalogo.* é GLOBAL
-- (nunca entra no backfill do tenant). Só falta o REGISTRO abaixo (o "catálogo no SQL").
--
-- arquivo.arquivamentos: registro de cada arquivamento (onde está, status, validade).
-- O payload em si vai p/ R2 (ou schema frio); aqui fica só o índice consultável.
-- ============================================================
CREATE SCHEMA IF NOT EXISTS arquivo;

GRANT USAGE ON SCHEMA arquivo TO "axys_tec";
ALTER DEFAULT PRIVILEGES IN SCHEMA arquivo
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";
ALTER DEFAULT PRIVILEGES IN SCHEMA arquivo
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";

CREATE TABLE IF NOT EXISTS arquivo.arquivamentos (
    arq_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arq_tenant_uuid     UUID    NOT NULL,                  -- tenant arquivado
    arq_status          TEXT    NOT NULL DEFAULT 'ARQUIVADO', -- ARQUIVADO | RESTAURADO | PURGADO
    arq_destino         TEXT    NOT NULL DEFAULT 'R2',      -- 'R2' | 'SCHEMA_FRIO'
    arq_localizacao     TEXT,                              -- path no R2 (ou nome do schema frio)
    arq_payload_hash    TEXT,                              -- checksum do backfill p/ integridade
    arq_tabelas_json    JSONB,                             -- { "ativo.ativos": 12, "ativo.ativo_itens": 3480, … } banco vs qtd
    arq_arquivado_em    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    arq_arquivado_por   TEXT,                              -- ator (serviço/hub)
    arq_restaurado_em   TIMESTAMPTZ,
    arq_expira_em       TIMESTAMPTZ,                       -- arquivado_em + 5 anos (purga)
    arq_meta_json       JSONB,

    CONSTRAINT ck_arq_status
        CHECK (arq_status IN ('ARQUIVADO', 'RESTAURADO', 'PURGADO')),
    CONSTRAINT ck_arq_destino
        CHECK (arq_destino IN ('R2', 'SCHEMA_FRIO')),
    CONSTRAINT ck_arq_tabelas_obj
        CHECK (arq_tabelas_json IS NULL OR jsonb_typeof(arq_tabelas_json) = 'object'),
    CONSTRAINT ck_arq_meta_obj
        CHECK (arq_meta_json IS NULL OR jsonb_typeof(arq_meta_json) = 'object')
);

CREATE INDEX ix_arq_tenant
    ON arquivo.arquivamentos (arq_tenant_uuid, arq_status);
CREATE INDEX ix_arq_expira
    ON arquivo.arquivamentos (arq_expira_em)
    WHERE arq_status = 'ARQUIVADO';


-- ============================================================
-- FIM DA PROPOSTA. Próximo: validação com Renan → mover p/ schema.sql.
-- RLS: políticas a habilitar na ida p/ schema.sql (tenant_uuid já presente).
-- ============================================================
