-- ============================================================
-- AxysEasy — Schema SQL
-- Banco: PostgreSQL 14+
-- Schemas: catalogo · audit
--
-- catalogo   : catálogo de fontes de preços, insumos, preços por
--         edição/UF/modalidade, composições de preço versionadas
--         e hierarquia de grupos/subgrupos.
-- audit : trilha de auditoria — quem/quando/o quê/antes/depois.
--
-- NB: o schema de orçamento/obras (futuro módulo "ativo") está só no
--   contrato (contracts/modulo_ativo_sumario_executivo.md), ainda não
--   implementado neste schema — será gradual, conforme implementação.
--
-- Decisões de arquitetura
-- ───────────────────────
-- VERSIONAMENTO DE CATÁLOGO
--   composicoes, composicao_itens, precos_insumo e custos_composicao são
--   VERSIONADOS por edição (uma linha por edição, imutável — sem UPDATE/
--   DELETE em dados históricos). Re-importar a mesma edi_id é idempotente.
--   UNIQUE em composições: (cmp_fte_id, cmp_codigo, cmp_edi_id).
--   insumos é a IDENTIDADE VIGENTE por (fonte, código): pode ter atributos
--   cadastrais (descrição/unidade/tipo) atualizados a cada edição — o
--   histórico cadastral vai para catalogo.insumos_historico e a série de
--   preços é preservada por edição em precos_insumo.
--
-- UF / MODALIDADE
--   precos_insumo e custos_composicao armazenam uma linha por
--   (insumo/composição, edição, uf, modalidade).
--   SINAPI: todas 27 UFs importadas por edição.
--   Estimativa: ~262 k linhas de preço de insumo por import (× 3 modalidades);
--   ~560 k de custo de composição (× 3 modalidades). PostgreSQL suporta com folga.
--   modalidade: 'SD' = sem desoneração | 'CD' = com desoneração | 'SE' = sem encargos sociais
--
-- TENANCY
--   Tabelas catalogo.*: catálogo compartilhado — sem tenant_uuid.
--   Dados do tenant (futuro módulo "ativo") carregarão tenant_uuid
--   quando implementados — fora deste schema por ora.
--
-- GRUPOS / SUBGRUPOS
--   catalogo.grupos:    nível 1 (CDHU: código 'XX'; SINAPI: não usa)
--   catalogo.subgrupos: nível 2 — sub_grp_id NULLABLE para SINAPI
--     (SINAPI usa sub_grp_id = NULL; seus "grupos" são subgrupos)
--
-- TIPO DE INSUMO
--   ins_tipo_sinapi: classificação exata da fonte (SINAPI verbatim
--     ou mapeado de outras fontes). Fidelidade ao dado original.
--   ins_ti_id: FK para catalogo.tipos_insumo
--     (MO / EQUIP_AQ / EQUIP_LOC / MAT / SERV / ESP)
--     agrupamento para histogramas e relatórios.
--   Mapeamento padrão SINAPI → tipos_insumo:
--     MATERIAL                → MAT
--     MAO DE OBRA             → MO
--     ENCARGOS COMPLEMENTARES → MO
--     EQUIPAMENTO (AQUISIÇÃO) → EQUIP_AQ
--     EQUIPAMENTO (LOCAÇÃO)   → EQUIP_LOC
--     SERVIÇOS                → SERV
--     ESPECIAIS               → ESP
--
-- PADRÃO DE NOMENCLATURA
--   Prefixo de coluna = abreviatura da tabela
--   PKs: INTEGER GENERATED BY DEFAULT AS IDENTITY
--   Timestamps: TIMESTAMPTZ; datas: DATE
--   Coeficientes: NUMERIC(14,6); preços/valores: NUMERIC(14,4)
--   Audit trail: _criado_em, _atualizado_em, _criado_por, _atualizado_por
--
-- ESTRUTURA RECOMENDADA / CONTRATO INTERNO DA APP
-- Estes JSONB são gerados exclusivamente pela aplicação.
-- Não devem ser montados livremente por usuários, integrações externas
-- ou rotinas ad hoc.
-- A estrutura pode evoluir, mas somente por alteração deliberada da app,
-- com compatibilidade documentada e, quando necessário, versionamento.
-- Qualquer alteração estrutural nestes JSONB deve ser tratada como
-- mudança de contrato interno da aplicação.
--
-- DOCUMENTAÇÃO EXTERNA (JSONB) — ESTRUTURA CANÔNICA
--   Campos ativos: catalogo.insumos.ins_external_path e
--                  catalogo.composicoes.cmp_external_path.
--   O banco guarda só metadados/paths; o conteúdo fica no R2
--   (bucket easy-public). HTML é o documento principal; PDF é derivado;
--   assets ficam em pasta própria. tipo_documento varia por entidade:
--   'catalogo_tecnico' (insumo) | 'caderno_encargos' (composição); o
--   diretório segue /insumos/... ou /composicoes/...
--
--   {
--     "bucket": "easy-public",
--     "tipo_documento": "catalogo_tecnico",
--     "vigente": {
--       "revisao": "rev_001",
--       "edicao_inicio": "2024-10",
--       "edicao_fim": null,
--       "formato_principal": "html",
--       "html_path":   "/insumos/45087_2024-10_rev001.html",
--       "pdf_path":    "/insumos/45087_2024-10_rev001.pdf",
--       "assets_path": "/insumos/45087_2024-10_rev001_assets/",
--       "mime_type": "text/html",
--       "checksum": null,
--       "publicado_em": null,
--       "publicado_por": null,
--       "observacao": null
--     },
--     "revisoes": [
--       {
--         "revisao": "rev_001",
--         "edicao_inicio": "2024-10",
--         "edicao_fim": null,
--         "html_path":   "/insumos/45087_2024-10_rev001.html",
--         "pdf_path":    "/insumos/45087_2024-10_rev001.pdf",
--         "assets_path": "/insumos/45087_2024-10_rev001_assets/",
--         "status": "VIGENTE",
--         "publicado_em": null,
--         "publicado_por": null,
--         "motivo_revisao": "publicacao_inicial"
--       }
--     ]
--   }
--
--   Variante de COMPOSIÇÃO — mesmo formato; muda tipo e diretório:
--     "tipo_documento": "caderno_encargos",
--     "vigente": { ...,
--       "html_path":   "/composicoes/105006_2024-10_rev001.html",
--       "pdf_path":    "/composicoes/105006_2024-10_rev001.pdf",
--       "assets_path": "/composicoes/105006_2024-10_rev001_assets/" }
--
--   Regra de revisão: ao entrar nova revisão, ela vira "vigente"; a
--   anterior recebe edicao_fim e status != 'VIGENTE'; "revisoes"
--   preserva o histórico.
--
-- AUDITORIA (JSONB) — schema audit
--   audit.logs.log_dados_antes / log_dados_depois: snapshot do registro
--     afetado como objeto SIMPLES coluna→valor — NÃO embrulhar em
--     schema/tabela/pk (log_schema, log_tabela, log_registro_id e log_acao
--     já são colunas próprias). Cadastros: objeto completo; alta
--     frequência: diff parcial (só campos alterados).
--     Ex.: { "ins_descricao": "...", "ins_unidade": "UN", "ins_ti_id": 4 }
--   audit.api_logs.log_corpo_req: corpo da requisição (POST/PUT/PATCH/DELETE).
--     O conteúdo deve ser SANITIZADO antes da gravação. É VEDADO registrar
--     senha, token, segredo, chave privada, credenciais ou dados sensíveis.
--     Alteração estrutural deste JSONB = mudança de contrato interno da app.
--     Ex.: { "codigo": "45087", "descricao": "..." }
--   audit.login_logs.log_detalhes: metadados do evento de autenticação.
--     Ex.: { "motivo_falha": "senha_invalida", "tentativas": 3 }
--          | { "provider_sub": "...", "scopes": [...] }
--
--   Os JSONB de catalogo.insumos_historico e catalogo.composicoes_historico
--   têm ESTRUTURA RECOMENDADA (não contrato rígido) no comentário de cada tabela.
-- ============================================================


-- ============================================================
-- SCHEMA: catalogo
-- ============================================================

CREATE SCHEMA IF NOT EXISTS catalogo;

GRANT USAGE ON SCHEMA catalogo  TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA catalogo
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA catalogo
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";


-- ============================================================
-- TABELA: catalogo.tipos_insumo
-- Contrato de regra de negócio (canônico):
--   docs/projects/axys-easy/contracts/catalogo/CATALOGO_BUSINESS_RULES.md
-- Grupos de insumos para histogramas e relatórios.
-- Domínio estrutural — seed ESSENCIAL inline logo abaixo (não em seed.sql).
--
-- NC = "Não Classificado": fallback técnico CONTROLADO de curadoria, NÃO é
--   categoria técnica real da fonte. Existe p/ permitir import completo sem
--   abortar (ins_ti_id é NOT NULL). Entra em fila de curadoria e NÃO deve
--   alimentar histogramas gerenciais como tipo técnico normal.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.tipos_insumo (
    ti_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ti_codigo          TEXT    NOT NULL,   -- MO|EQUIP_AQ|EQUIP_LOC|MAT|SERV|ESP|NC
    ti_nome            TEXT    NOT NULL,
    ti_ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    ti_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ti_atualizado_em   TIMESTAMPTZ,
    ti_criado_por      TEXT,
    ti_atualizado_por  TEXT,

    CONSTRAINT uq_tipos_insumo_codigo
        UNIQUE (ti_codigo),

    CONSTRAINT ck_tipos_insumo_codigo_vazio
        CHECK (btrim(ti_codigo) <> ''),

    CONSTRAINT ck_tipos_insumo_nome_vazio
        CHECK (btrim(ti_nome) <> '')
);

-- Seed essencial (estrutural) — inline, não em seed.sql:
INSERT INTO catalogo.tipos_insumo (ti_codigo, ti_nome) VALUES
    ('MO',       'Mão de Obra'),
    ('EQUIP_AQ', 'Equipamento — Aquisição'),
    ('EQUIP_LOC','Equipamento — Locação'),
    ('MAT',      'Material'),
    ('SERV',     'Serviço'),
    ('ESP',      'Especiais'),
    ('NC',       'Não Classificado (fallback de curadoria)')
ON CONFLICT (ti_codigo) DO NOTHING;


-- ============================================================
-- TABELA: catalogo.situacoes
-- Contrato de regra de negócio (canônico):
--   docs/projects/axys-easy/contracts/catalogo/CATALOGO_BUSINESS_RULES.md
-- Domínio controlado de situações do catálogo (lookup por FK — substitui
-- texto repetido em massa). DOIS domínios apenas:
--   INSUMO     → situação do PREÇO do insumo naquela UF/edição (precos_insumo).
--   COMPOSICAO → situação declarada da composição.
-- Não há domínio 'PRECO' (situação de preço É do insumo) nem 'ITEM' (item é
-- só insumo ou composição dentro de composição).
-- A situação aqui é a DECLARADA pela fonte (auditoria). Coerência preço×
-- situação e o cálculo efetivo são contrato da APP — NÃO há trigger.
-- A FK composta (sit_id, dominio) garante DOMÍNIO válido no banco.
-- Domínio estrutural — seed ESSENCIAL inline logo abaixo (não em seed.sql).
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.situacoes (
    sit_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sit_dominio   TEXT     NOT NULL,
    sit_codigo    TEXT     NOT NULL,
    sit_descricao TEXT     NOT NULL,
    sit_ordem     SMALLINT NOT NULL DEFAULT 0,
    sit_ativo     BOOLEAN  NOT NULL DEFAULT TRUE,

    CONSTRAINT ck_situacoes_dominio
        CHECK (sit_dominio IN ('INSUMO', 'COMPOSICAO')),

    CONSTRAINT uq_situacoes_dominio_codigo
        UNIQUE (sit_dominio, sit_codigo),

    -- alvo das FKs compostas de domínio (garante domínio válido sem trigger):
    CONSTRAINT uq_situacoes_id_dominio
        UNIQUE (sit_id, sit_dominio)
);

-- Seed essencial (estrutural) — inline, não em seed.sql:
INSERT INTO catalogo.situacoes (sit_dominio, sit_codigo, sit_descricao, sit_ordem) VALUES
    ('INSUMO',    'COM_PRECO', 'Preço publicado pela fonte na UF/edição', 1),
    ('INSUMO',    'SEM_PRECO', 'Insumo existe, fonte não publicou preço', 2),
    ('COMPOSICAO','COM_CUSTO', 'Composição com custo na edição',          1),
    ('COMPOSICAO','SEM_CUSTO', 'Composição sem custo (item faltante)',    2),
    ('COMPOSICAO','SUSPENSO',  'Composição suspensa',                     3),
    ('COMPOSICAO','EM_ESTUDO', 'Composição em estudo',                    4)
ON CONFLICT (sit_dominio, sit_codigo) DO NOTHING;


-- ============================================================
-- TABELA: catalogo.fontes
-- Contrato funcional (canônico):
--   docs/projects/axys-easy/contracts/catalogo/CATALOGO_FONTES.md
-- Catálogo das fontes de preços (SINAPI, CDHU, FDE, AXYS...).
--
-- fte_ordem_edicao:
--   'DATA'   — edição mais recente = maior edi_mes_ref
--   'VERSAO' — edição mais recente = maior edi_codigo_versao
--
-- Fonte 'AXYS': composições próprias do tenant — sem edição
--   mensal; preço informado direto, sem linha em precos_insumo.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.fontes (
    fte_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fte_codigo         TEXT    NOT NULL,   -- 'SINAPI' | 'CDHU' | 'FDE' | 'AXYS'
    fte_nome           TEXT    NOT NULL,
    fte_ordem_edicao   TEXT    NOT NULL DEFAULT 'DATA',
    fte_ativa          BOOLEAN NOT NULL DEFAULT TRUE,
    fte_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fte_atualizado_em  TIMESTAMPTZ,
    fte_criado_por     TEXT,
    fte_atualizado_por TEXT,

    CONSTRAINT uq_fontes_codigo
        UNIQUE (fte_codigo),

    CONSTRAINT ck_fontes_codigo_vazio
        CHECK (btrim(fte_codigo) <> ''),

    CONSTRAINT ck_fontes_nome_vazio
        CHECK (btrim(fte_nome) <> ''),

    CONSTRAINT ck_fontes_ordem_edicao
        CHECK (fte_ordem_edicao IN ('DATA', 'VERSAO'))
);

CREATE INDEX ix_fontes_ativa
    ON catalogo.fontes (fte_ativa, fte_codigo);


-- ============================================================
-- TABELA: catalogo.edicoes
-- Contrato funcional (canônico):
--   docs/projects/axys-easy/contracts/catalogo/CATALOGO_EDICOES.md
-- Cada publicação de uma fonte de preços.
--
-- edi_mes_ref:       1º dia do mês de referência (DATE).
-- edi_codigo_versao: para fontes com VERSAO (ex: CDHU '201').
-- edi_uf_padrao:     UF exibida por padrão na consulta.
--   SINAPI: 'SP' — todas 27 UFs estão importadas na edição.
--   CDHU:   'SP' — fonte estadual, apenas SP.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.edicoes (
    edi_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edi_fte_id         INTEGER NOT NULL,
    edi_mes_ref        DATE    NOT NULL,
    edi_codigo_versao  TEXT,
    edi_uf_padrao      CHAR(2) NOT NULL DEFAULT 'SP',
    edi_ativa          BOOLEAN NOT NULL DEFAULT TRUE,
    edi_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edi_atualizado_em  TIMESTAMPTZ,
    edi_criado_por     TEXT,
    edi_atualizado_por TEXT,

    CONSTRAINT fk_edicoes_fte
        FOREIGN KEY (edi_fte_id)
        REFERENCES catalogo.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_edicoes_fte_mes
        UNIQUE (edi_fte_id, edi_mes_ref),

    CONSTRAINT ck_edicoes_primeiro_do_mes
        CHECK (EXTRACT(DAY FROM edi_mes_ref) = 1),

    CONSTRAINT ck_edicoes_codigo_versao_vazio
        CHECK (edi_codigo_versao IS NULL OR btrim(edi_codigo_versao) <> '')
);

CREATE INDEX ix_edicoes_fte_mes
    ON catalogo.edicoes (edi_fte_id, edi_mes_ref DESC);

CREATE INDEX ix_edicoes_ativas
    ON catalogo.edicoes (edi_fte_id, edi_ativa)
    WHERE edi_ativa = TRUE;


-- ============================================================
-- TABELA: catalogo.grupos
-- Nível 1 da hierarquia de classificação.
--   CDHU: código numérico 'XX' (ex: '01', '02')
--   SINAPI: não usa — subgrupos têm sub_grp_id = NULL
--
-- DECISÃO (MVP): grupos/subgrupos são TAXONOMIA AUXILIAR de navegação,
--   SEM versionamento por edição. Se houver drift relevante de taxonomia
--   entre edições, cria-se versionamento próprio depois — não bloquear
--   importação por isso agora.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.grupos (
    grp_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grp_fte_id         INTEGER NOT NULL,
    grp_codigo         TEXT    NOT NULL,
    grp_descricao      TEXT    NOT NULL,
    grp_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    grp_atualizado_em  TIMESTAMPTZ,
    grp_criado_por     TEXT,
    grp_atualizado_por TEXT,

    CONSTRAINT fk_grupos_fte
        FOREIGN KEY (grp_fte_id)
        REFERENCES catalogo.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_grupos_fte_codigo
        UNIQUE (grp_fte_id, grp_codigo),

    CONSTRAINT ck_grupos_codigo_vazio
        CHECK (btrim(grp_codigo) <> '')
);

CREATE INDEX ix_grupos_fte
    ON catalogo.grupos (grp_fte_id);


-- ============================================================
-- TABELA: catalogo.subgrupos
-- Nível 2 da hierarquia.
--   CDHU: código 'XX.XX', FK sub_grp_id preenchida
--   SINAPI: nome do grupo (ex: 'Acessibilidade'), sub_grp_id NULL
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.subgrupos (
    sub_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_fte_id         INTEGER NOT NULL,
    sub_grp_id         INTEGER,                -- NULL para SINAPI
    sub_codigo         TEXT    NOT NULL,
    sub_descricao      TEXT    NOT NULL,
    sub_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sub_atualizado_em  TIMESTAMPTZ,
    sub_criado_por     TEXT,
    sub_atualizado_por TEXT,

    CONSTRAINT fk_subgrupos_fte
        FOREIGN KEY (sub_fte_id)
        REFERENCES catalogo.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_subgrupos_grp
        FOREIGN KEY (sub_grp_id)
        REFERENCES catalogo.grupos (grp_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_subgrupos_fte_codigo
        UNIQUE (sub_fte_id, sub_codigo),

    CONSTRAINT ck_subgrupos_codigo_vazio
        CHECK (btrim(sub_codigo) <> '')
);

CREATE INDEX ix_subgrupos_fte
    ON catalogo.subgrupos (sub_fte_id);

CREATE INDEX ix_subgrupos_grp
    ON catalogo.subgrupos (sub_grp_id)
    WHERE sub_grp_id IS NOT NULL;


-- ============================================================
-- TABELA: catalogo.insumos
-- Contrato de regra de negócio (canônico):
--   docs/projects/axys-easy/contracts/catalogo/CATALOGO_BUSINESS_RULES.md
--   (classificação/origem/NC: CDHU e SINAPI nos contratos de import)
-- Identidade dos insumos — o que o insumo É, sem preço.
--
-- ins_ti_id: FK para tipos_insumo. NUNCA NULL — todo insumo é
--   classificado. SINAPI traz classificação nativa (FONTE); CDHU é
--   classificada por descrição+unidade pela regra; órfão do Analítico vai
--   por fuzzy; sem confiança cai em 'NC' (Não Classificado). Nunca NULL.
-- ins_ti_origem: autoridade da classificação — 'FONTE' (classif nativa da
--   fonte), 'REGRA' (parser/fuzzy/léxico) ou 'MANUAL' (curadoria humana).
--   PREVALÊNCIA no reimport: FONTE > MANUAL > REGRA. FONTE prevalece até
--   sobre MANUAL; MANUAL só prevalece quando a fonte NÃO classifica; REGRA/NC
--   são reaplicados a cada reimport. Default 'REGRA'. A prevalência é
--   garantida pelo PARSER (ON CONFLICT), não pelo banco.
-- ins_ativo: false quando ausente na edição mais recente da
--   fonte. Não exclui o registro — preserva histórico.
-- ins_external_path: metadados de documentação externa do insumo em
--   Cloudflare R2 (bucket easy-public). Índice documental direto no
--   registro p/ localizar o documento técnico/catálogo VIGENTE e as
--   revisões anteriores. NÃO armazena o conteúdo (HTML/PDF/imagens) —
--   só paths, metadados e revisão. HTML é o formato principal; PDF é
--   derivado; assets ficam em pasta própria no R2. Estrutura:
--   { bucket, tipo_documento, vigente:{...}, revisoes:[...] }.
--   Auditoria formal continua no schema audit — isto é índice, não log.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.insumos (
    ins_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ins_fte_id         INTEGER NOT NULL,
    ins_ti_id          INTEGER NOT NULL,
    ins_ti_origem      TEXT    NOT NULL DEFAULT 'REGRA',   -- 'FONTE' | 'REGRA' | 'MANUAL'
    ins_codigo         TEXT    NOT NULL,
    ins_descricao      TEXT    NOT NULL,
    ins_unidade        TEXT    NOT NULL,
    ins_ativo          BOOLEAN NOT NULL DEFAULT TRUE,
    ins_external_path  JSONB,
    ins_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ins_atualizado_em  TIMESTAMPTZ,
    ins_criado_por     TEXT,
    ins_atualizado_por TEXT,

    CONSTRAINT fk_insumos_fte
        FOREIGN KEY (ins_fte_id)
        REFERENCES catalogo.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_insumos_ti
        FOREIGN KEY (ins_ti_id)
        REFERENCES catalogo.tipos_insumo (ti_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_insumos_fte_codigo
        UNIQUE (ins_fte_id, ins_codigo),

    CONSTRAINT ck_insumos_ti_origem
        CHECK (ins_ti_origem IN ('FONTE', 'REGRA', 'MANUAL')),

    CONSTRAINT ck_insumos_codigo_vazio
        CHECK (btrim(ins_codigo) <> ''),

    CONSTRAINT ck_insumos_unidade_vazia
        CHECK (btrim(ins_unidade) <> ''),

    CONSTRAINT ck_insumos_external_path_obj
        CHECK (ins_external_path IS NULL
            OR jsonb_typeof(ins_external_path) = 'object')
);

CREATE INDEX ix_insumos_fte_ativo
    ON catalogo.insumos (ins_fte_id, ins_ativo, ins_codigo);

CREATE INDEX ix_insumos_ti
    ON catalogo.insumos (ins_ti_id);


-- ============================================================
-- TABELA: catalogo.precos_insumo
-- Contrato de regra de negócio (canônico):
--   docs/projects/axys-easy/contracts/catalogo/CATALOGO_BUSINESS_RULES.md  (§3 Preço)
-- Preços dos insumos por edição / UF / modalidade.
-- Cada linha é imutável. Re-import da mesma
-- (insumo, edição, uf, modalidade) é upsert idempotente.
--
-- pri_uf:         UF da coleta ('SP', 'RJ', ...)
-- pri_modalidade:
--   'SE' = sem encargos sociais — modalidade PADRÃO p/ insumos NÃO-MO (material,
--          equipamento, serviço, item comercial) e p/ fontes que NÃO distinguem
--          encargos/desoneração. Não-MO não carrega encargo social → sempre 'SE'.
--   'SD' = sem desoneração — quando a fonte publica preço de MO nessa modalidade.
--   'CD' = com desoneração — quando a fonte publica preço de MO nessa modalidade.
--   Regra de negócio (responsabilidade do importador):
--     - insumos NÃO-MO são SEMPRE armazenados em 'SE' (não duplicar em SD/CD);
--     - MO / encargos complementares usam as modalidades publicadas pela fonte;
--     - se a fonte NÃO distingue modalidade, usar 'SE'.
--   Ex.: SINAPI MO → SD/CD/SE (conforme a fonte); CDHU → 'SE' p/ tudo (mono-coluna,
--        não distingue encargos). 'SE' é o default de segurança, mas o parser deve
--        setar a modalidade explicitamente.
-- pri_origem:     'C' = coletado | 'CR' = coef. representativo
-- pri_valor:      valor publicado EXATAMENTE (inclui 0); NULL quando a fonte
--   não publicou preço — o MOTIVO fica em pri_sit_id, nunca solto.
-- pri_sit_id:     FK p/ catalogo.situacoes (domínio 'INSUMO') = situação do
--   preço: COM_PRECO (valor publicado) | SEM_PRECO (sem preço da fonte).
--   Contrato do parser: TODA UF da edição tem linha; AUSÊNCIA de linha =
--   falha/não-processado, NUNCA "sem preço". Coerência valor×situação é
--   responsabilidade do parser/importador — NÃO há trigger.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.precos_insumo (
    pri_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pri_ins_id         INTEGER       NOT NULL,
    pri_edi_id         INTEGER       NOT NULL,
    pri_uf             CHAR(2)       NOT NULL DEFAULT 'SP',
    pri_modalidade     CHAR(2)       NOT NULL DEFAULT 'SE',
    pri_valor          NUMERIC(14,4),
    pri_sit_id         INTEGER       NOT NULL,
    pri_sit_dominio    TEXT          NOT NULL DEFAULT 'INSUMO',
    pri_origem         CHAR(2),
    pri_criado_em      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pri_atualizado_em  TIMESTAMPTZ,
    pri_criado_por     TEXT,
    pri_atualizado_por TEXT,

    CONSTRAINT fk_precos_ins
        FOREIGN KEY (pri_ins_id)
        REFERENCES catalogo.insumos (ins_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_precos_edi
        FOREIGN KEY (pri_edi_id)
        REFERENCES catalogo.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_precos_ins_edi_uf_mod
        UNIQUE (pri_ins_id, pri_edi_id, pri_uf, pri_modalidade),

    CONSTRAINT ck_precos_sit_dominio
        CHECK (pri_sit_dominio = 'INSUMO'),

    CONSTRAINT fk_precos_sit
        FOREIGN KEY (pri_sit_id, pri_sit_dominio)
        REFERENCES catalogo.situacoes (sit_id, sit_dominio)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_precos_modalidade
        CHECK (pri_modalidade IN ('SD', 'CD', 'SE')),

    CONSTRAINT ck_precos_origem
        CHECK (pri_origem IS NULL OR pri_origem IN ('C', 'CR'))
);

CREATE INDEX ix_precos_ins_edi
    ON catalogo.precos_insumo (pri_ins_id, pri_edi_id, pri_uf, pri_modalidade);

CREATE INDEX ix_precos_edi
    ON catalogo.precos_insumo (pri_edi_id);

CREATE INDEX ix_precos_uf
    ON catalogo.precos_insumo (pri_uf, pri_edi_id);


-- ============================================================
-- TABELA: catalogo.composicoes
-- Contrato de regra de negócio (canônico):
--   docs/projects/axys-easy/contracts/catalogo/CATALOGO_BUSINESS_RULES.md  (§4 Composição)
-- Cabeçalho das CPUs — VERSIONADO por edição.
-- Cada (cmp_fte_id, cmp_codigo, cmp_edi_id) é uma linha
-- distinta e imutável. Não há UPDATE em dados históricos.
--
-- cmp_situacao: situação OFICIAL publicada/consolidada pela fonte —
--               'COM CUSTO' | 'SEM CUSTO' | 'SUSPENSO' | 'EM ESTUDO'.
-- cmp_sub_id:   FK para subgrupos (nullable — composições AXYS
--               são livres de subgrupo)
-- cmp_motivo_sem_custo: explicação objetiva do SEM CUSTO (ex.:
--   "Item 45087 sem preço na fonte SINAPI"). NULL quando não aplicável.
-- cmp_tem_item_sem_preco: ao menos um item direto (insumo) sem preço.
-- cmp_tem_item_sem_custo: ao menos uma subcomposição direta sem custo.
--   Estes flags tornam o SEM CUSTO AUDITÁVEL sem recalcular custo parcial.
-- Histórico cadastral/estrutural fica na tabela LATERAL
--   catalogo.composicoes_historico — NÃO em coluna JSON nesta tabela.
-- cmp_external_path: metadados de documentação externa da composição
--   em Cloudflare R2 (bucket easy-public). Índice documental direto no
--   registro p/ localizar caderno de encargos, critérios de medição,
--   descritivo técnico e revisões. NÃO armazena o conteúdo (HTML/PDF/
--   imagens) — só paths, metadados e revisão. HTML é o formato
--   principal; PDF é derivado; assets em pasta própria no R2. Estrutura:
--   { bucket, tipo_documento, vigente:{...}, revisoes:[...] }.
--   Auditoria formal continua no schema audit — isto é índice, não log.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.composicoes (
    cmp_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cmp_fte_id          INTEGER NOT NULL,
    cmp_edi_id          INTEGER NOT NULL,
    cmp_sub_id          INTEGER,
    cmp_codigo          TEXT    NOT NULL,
    cmp_descricao       TEXT    NOT NULL,
    cmp_unidade         TEXT    NOT NULL,
    cmp_situacao        TEXT,
    cmp_motivo_sem_custo   TEXT,
    cmp_tem_item_sem_preco BOOLEAN NOT NULL DEFAULT FALSE,
    cmp_tem_item_sem_custo BOOLEAN NOT NULL DEFAULT FALSE,
    cmp_ativa           BOOLEAN NOT NULL DEFAULT TRUE,
    cmp_primeira_pub    DATE,
    cmp_ultima_pub      DATE,
    cmp_ultima_alteracao DATE,
    cmp_external_path   JSONB,
    cmp_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cmp_atualizado_em   TIMESTAMPTZ,
    cmp_criado_por      TEXT,
    cmp_atualizado_por  TEXT,

    CONSTRAINT fk_composicoes_fte
        FOREIGN KEY (cmp_fte_id)
        REFERENCES catalogo.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_composicoes_edi
        FOREIGN KEY (cmp_edi_id)
        REFERENCES catalogo.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_composicoes_sub
        FOREIGN KEY (cmp_sub_id)
        REFERENCES catalogo.subgrupos (sub_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_composicoes_fte_codigo_edi
        UNIQUE (cmp_fte_id, cmp_codigo, cmp_edi_id),

    CONSTRAINT ck_composicoes_codigo_vazio
        CHECK (btrim(cmp_codigo) <> ''),

    CONSTRAINT ck_composicoes_unidade_vazia
        CHECK (btrim(cmp_unidade) <> ''),

    CONSTRAINT ck_composicoes_situacao
        CHECK (cmp_situacao IS NULL OR cmp_situacao IN (
            'COM CUSTO', 'SEM CUSTO', 'SUSPENSO', 'EM ESTUDO'
        )),

    CONSTRAINT ck_composicoes_external_path_obj
        CHECK (cmp_external_path IS NULL
            OR jsonb_typeof(cmp_external_path) = 'object')
);

CREATE INDEX ix_composicoes_fte_edi
    ON catalogo.composicoes (cmp_fte_id, cmp_edi_id, cmp_codigo);

CREATE INDEX ix_composicoes_fte_codigo
    ON catalogo.composicoes (cmp_fte_id, cmp_codigo);

CREATE INDEX ix_composicoes_sub
    ON catalogo.composicoes (cmp_sub_id)
    WHERE cmp_sub_id IS NOT NULL;

CREATE INDEX ix_composicoes_situacao
    ON catalogo.composicoes (cmp_situacao)
    WHERE cmp_situacao IS NOT NULL;


-- ============================================================
-- TABELA: catalogo.composicao_itens
-- Contrato de regra de negócio (canônico):
--   docs/projects/axys-easy/contracts/catalogo/CATALOGO_BUSINESS_RULES.md  (§4-§5)
-- Itens de cada composição na sua edição.
-- Filho pode ser insumo ('INSUMO') ou sub-composição ('COMPOSICAO').
-- Vinculado à composição versionada (cmp_id inclui edição).
-- Ciclos proibidos — verificados na camada de aplicação.
--
-- ci_situacao: situação do item na fonte — 'COM PREÇO' | 'SEM PREÇO'
--   | 'COM CUSTO' | 'SEM CUSTO' | 'SUSPENSO' | 'EM ESTUDO'.
-- ci_codigo/descricao/unidade_fonte_original: texto BRUTO da fonte,
--   preservado para auditoria/conferência/debug de parser, mesmo após
--   o item ser resolvido para FK (ci_ins_id / ci_cmp_filho_id).
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.composicao_itens (
    ci_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ci_cmp_id          INTEGER       NOT NULL,
    ci_tipo_filho      TEXT          NOT NULL,
    ci_ins_id          INTEGER,
    ci_cmp_filho_id    INTEGER,
    ci_coef            NUMERIC(14,6) NOT NULL,
    ci_situacao        TEXT,
    ci_codigo_fonte_original     TEXT,
    ci_descricao_fonte_original  TEXT,
    ci_unidade_fonte_original    TEXT,
    ci_ordem           SMALLINT      NOT NULL DEFAULT 0,
    ci_criado_em       TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ci_atualizado_em   TIMESTAMPTZ,
    ci_criado_por      TEXT,
    ci_atualizado_por  TEXT,

    CONSTRAINT fk_ci_cmp
        FOREIGN KEY (ci_cmp_id)
        REFERENCES catalogo.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT fk_ci_ins
        FOREIGN KEY (ci_ins_id)
        REFERENCES catalogo.insumos (ins_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_ci_cmp_filho
        FOREIGN KEY (ci_cmp_filho_id)
        REFERENCES catalogo.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_ci_tipo_filho
        CHECK (ci_tipo_filho IN ('INSUMO', 'COMPOSICAO')),

    CONSTRAINT ck_ci_filho_xor
        CHECK (
            (ci_tipo_filho = 'INSUMO'
                AND ci_ins_id IS NOT NULL
                AND ci_cmp_filho_id IS NULL)
            OR
            (ci_tipo_filho = 'COMPOSICAO'
                AND ci_cmp_filho_id IS NOT NULL
                AND ci_ins_id IS NULL)
        ),

    CONSTRAINT ck_ci_coef_positivo
        CHECK (ci_coef > 0),

    CONSTRAINT ck_ci_situacao
        CHECK (
            ci_situacao IS NULL
            OR (ci_tipo_filho = 'INSUMO'
                AND ci_situacao IN ('COM PREÇO', 'SEM PREÇO'))
            OR (ci_tipo_filho = 'COMPOSICAO'
                AND ci_situacao IN ('COM CUSTO', 'SEM CUSTO', 'SUSPENSO', 'EM ESTUDO'))
        ),

    CONSTRAINT uq_ci_cmp_ins
        UNIQUE (ci_cmp_id, ci_ins_id),

    CONSTRAINT uq_ci_cmp_filho
        UNIQUE (ci_cmp_id, ci_cmp_filho_id)
);

CREATE INDEX ix_ci_cmp
    ON catalogo.composicao_itens (ci_cmp_id, ci_ordem);

CREATE INDEX ix_ci_ins
    ON catalogo.composicao_itens (ci_ins_id)
    WHERE ci_ins_id IS NOT NULL;

CREATE INDEX ix_ci_cmp_filho
    ON catalogo.composicao_itens (ci_cmp_filho_id)
    WHERE ci_cmp_filho_id IS NOT NULL;


-- ============================================================
-- TABELA: catalogo.custos_composicao
-- Contrato de regra de negócio (canônico):
--   docs/projects/axys-easy/contracts/catalogo/CATALOGO_BUSINESS_RULES.md  (§4-§5, %AS)
-- Custos pré-calculados por composição / edição / UF / modalidade.
-- SINAPI fornece os valores direto nas abas CSD/CCD.
-- Imutável — mesmo regime de precos_insumo.
--
-- Guarda DOIS valores lado a lado — dado contra dado, auditável:
-- cc_custo_fonte: valor OFICIAL publicado/importado da fonte-base.
--   NUNCA é sobrescrito/descartado. = NULL quando não há custo válido;
--   = 0 SÓ quando a fonte publica zero numérico. A situação oficial
--   (SEM CUSTO etc.) fica em composicoes.cmp_situacao.
-- cc_custo_calculado: valor recalculado pela aplicação a partir dos
--   itens e preços disponíveis. NÃO substitui automaticamente o oficial.
-- cc_diferenca_valor: cc_custo_calculado - cc_custo_fonte (pode ser < 0).
-- cc_diferenca_percentual: cc_diferenca_valor / cc_custo_fonte quando
--   cc_custo_fonte > 0; NULL quando fonte é NULL/0 (não forçar cálculo).
-- cc_status_conferencia: classificação fonte × cálculo (ver CHECK).
-- cc_observacao_conferencia: nota livre da conferência.
-- A UI pode exibir ambos e destacar a diferença; NÃO mascarar divergência
--   nem gravar custo parcial como oficial. (Motor/trigger: não aqui.)
--
-- A EDIÇÃO vem de composicoes.cmp_edi_id via cc_cmp_id (composição é
--   versionada por edição) — sem coluna própria. Consultas por edição
--   fazem join com composicoes.
--
-- cc_pct_sp: % do custo atribuído ao preço de SP por ausência
--   de coleta local no estado. NULL para CDHU.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.custos_composicao (
    cc_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cc_cmp_id          INTEGER       NOT NULL,
    cc_uf              CHAR(2)       NOT NULL DEFAULT 'SP',
    cc_modalidade      CHAR(2)       NOT NULL DEFAULT 'SD',
    cc_custo_fonte          NUMERIC(14,4),
    cc_custo_calculado      NUMERIC(14,4),
    cc_diferenca_valor      NUMERIC(14,4),
    cc_diferenca_percentual NUMERIC(12,6),
    cc_status_conferencia   TEXT,
    cc_observacao_conferencia TEXT,
    cc_pct_sp          NUMERIC(8,6),
    cc_criado_em       TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cc_atualizado_em   TIMESTAMPTZ,
    cc_criado_por      TEXT,
    cc_atualizado_por  TEXT,

    CONSTRAINT fk_cc_cmp
        FOREIGN KEY (cc_cmp_id)
        REFERENCES catalogo.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT uq_cc_cmp_uf_mod
        UNIQUE (cc_cmp_id, cc_uf, cc_modalidade),

    CONSTRAINT ck_cc_modalidade
        CHECK (cc_modalidade IN ('SD', 'CD', 'SE')),

    CONSTRAINT ck_cc_custo_fonte_nonneg
        CHECK (cc_custo_fonte IS NULL OR cc_custo_fonte >= 0),

    CONSTRAINT ck_cc_custo_calculado_nonneg
        CHECK (cc_custo_calculado IS NULL OR cc_custo_calculado >= 0),

    CONSTRAINT ck_cc_status_conferencia
        CHECK (cc_status_conferencia IS NULL OR cc_status_conferencia IN (
            'NAO_CALCULADO', 'IGUAL', 'DIVERGENTE_ARREDONDAMENTO',
            'DIVERGENTE_RELEVANTE', 'SEM_CUSTO_FONTE', 'SEM_CUSTO_CALCULADO',
            'ERRO_PROCESSAMENTO'
        ))
);

CREATE INDEX ix_cc_cmp
    ON catalogo.custos_composicao (cc_cmp_id, cc_uf, cc_modalidade);


-- ============================================================
-- TABELA: catalogo.sinapi_manutencoes
-- Contrato de regra de negócio (canônico):
--   docs/projects/axys-easy/contracts/catalogo/CATALOGO_SINAPI_IMPORT_CONTRACT.md
-- Log de alterações do SINAPI por boletim mensal.
-- Referência para rastrear o que mudou entre edições.
-- Imutável após import.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.sinapi_manutencoes (
    sm_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sm_edi_id       INTEGER NOT NULL,
    sm_tipo         TEXT    NOT NULL,
    sm_codigo       TEXT    NOT NULL,
    sm_descricao    TEXT,
    sm_manutencao   TEXT    NOT NULL,
    sm_importado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sm_edi
        FOREIGN KEY (sm_edi_id)
        REFERENCES catalogo.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_sm_tipo
        CHECK (sm_tipo IN ('INSUMO', 'COMPOSICAO'))
);

CREATE INDEX ix_sm_edi
    ON catalogo.sinapi_manutencoes (sm_edi_id);

CREATE INDEX ix_sm_codigo
    ON catalogo.sinapi_manutencoes (sm_codigo, sm_edi_id);

CREATE INDEX ix_sm_manutencao
    ON catalogo.sinapi_manutencoes (sm_manutencao);


-- ============================================================
-- TABELA: catalogo.insumos_equivalencias
-- Equivalência entre insumos de fontes-base diferentes (ex.: insumo
-- CDHU ≈ insumo SINAPI ≈ insumo EMOP). Implementada na origem (import).
-- ie_tipo_equivalencia: EXATA | APROXIMADA | SUBSTITUTA |
--   COMERCIAL | SEMANTICA.   ie_score: confiança 0..1.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.insumos_equivalencias (
    ie_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ie_ins_id_origem       INTEGER NOT NULL,
    ie_ins_id_equivalente  INTEGER NOT NULL,
    ie_tipo_equivalencia   TEXT,
    ie_score               NUMERIC(4,3),
    ie_metodo              TEXT,
    ie_observacao          TEXT,
    ie_ativo               BOOLEAN NOT NULL DEFAULT TRUE,
    ie_criado_em           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ie_atualizado_em       TIMESTAMPTZ,
    ie_criado_por          TEXT,
    ie_atualizado_por      TEXT,

    CONSTRAINT fk_insumos_equivalencias_origem
        FOREIGN KEY (ie_ins_id_origem)
        REFERENCES catalogo.insumos (ins_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_insumos_equivalencias_equivalente
        FOREIGN KEY (ie_ins_id_equivalente)
        REFERENCES catalogo.insumos (ins_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_insumos_equivalencias_nao_auto
        CHECK (ie_ins_id_origem <> ie_ins_id_equivalente),

    CONSTRAINT ck_insumos_equivalencias_tipo
        CHECK (ie_tipo_equivalencia IS NULL OR ie_tipo_equivalencia IN
            ('EXATA', 'APROXIMADA', 'SUBSTITUTA', 'COMERCIAL', 'SEMANTICA')),

    CONSTRAINT ck_insumos_equivalencias_score
        CHECK (ie_score IS NULL OR (ie_score >= 0 AND ie_score <= 1))
);

CREATE INDEX ix_insumos_equivalencias_origem
    ON catalogo.insumos_equivalencias (ie_ins_id_origem);
CREATE INDEX ix_insumos_equivalencias_equivalente
    ON catalogo.insumos_equivalencias (ie_ins_id_equivalente);


-- ============================================================
-- TABELA: catalogo.insumos_historico
-- Trilha de auditoria da EVOLUÇÃO CADASTRAL do insumo ao longo das
-- edições da fonte-base (criação, alteração de descrição/unidade/
-- tipo/classificação, inativação, reativação). Implementada na origem.
--
-- NÃO armazena preços e NÃO substitui catalogo.precos_insumo (série
-- histórica de preços por edição/UF/modalidade). catalogo.insumos
-- continua representando o ESTADO VIGENTE; esta tabela guarda o
-- histórico documental.
--
-- ih_tipo_evento: CRIACAO | ALTERACAO | INATIVACAO | REATIVACAO.
-- ih_edi_id_inicio / ih_edi_id_fim: faixa de edições (fim NULL = aberto).
-- JSONB intencional: o conjunto de campos alterados varia por
--   fonte-base/versão — snapshot/diff documental.
-- Append-only: sem _atualizado_* (snapshots imutáveis).
--
-- ESTRUTURA RECOMENDADA dos JSONB (NÃO contrato rígido — pode variar
--   conforme fonte-base, parser e tipo de alteração):
--   CRIACAO    → ih_dados_novos {edicao, codigo, descricao, unidade, tipo, ativo}
--   ALTERACAO  → ih_dados_anteriores {edicao_origem, descricao, unidade, tipo, ativo};
--                ih_dados_novos {edicao_alteracao, descricao, unidade, tipo, ativo};
--                ih_diff {descricao:{de,para}, unidade:{de,para}}  (só os mudados)
--   INATIVACAO → ih_dados_anteriores {ultima_edicao_ativa, codigo, ..., ativo:true};
--                ih_dados_novos {edicao_inativacao, ativo:false};
--                ih_diff {ativo:{de:true, para:false}}
--   REATIVACAO → simétrico (edicao_reativacao; ativo:{de:false, para:true})
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.insumos_historico (
    ih_id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ih_ins_id            INTEGER NOT NULL,
    ih_edi_id_inicio     INTEGER,
    ih_edi_id_fim        INTEGER,
    ih_tipo_evento       TEXT    NOT NULL,
    ih_dados_anteriores  JSONB,
    ih_dados_novos       JSONB,
    ih_diff              JSONB,
    ih_observacao        TEXT,
    ih_criado_em         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ih_criado_por        TEXT,

    CONSTRAINT fk_insumos_historico_ins
        FOREIGN KEY (ih_ins_id)
        REFERENCES catalogo.insumos (ins_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_insumos_historico_edi_inicio
        FOREIGN KEY (ih_edi_id_inicio)
        REFERENCES catalogo.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_insumos_historico_edi_fim
        FOREIGN KEY (ih_edi_id_fim)
        REFERENCES catalogo.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_insumos_historico_tipo_evento
        CHECK (ih_tipo_evento IN
            ('CRIACAO', 'ALTERACAO', 'INATIVACAO', 'REATIVACAO'))
);

CREATE INDEX ix_insumos_historico_ins
    ON catalogo.insumos_historico (ih_ins_id);
CREATE INDEX ix_insumos_historico_ins_edi
    ON catalogo.insumos_historico (ih_ins_id, ih_edi_id_inicio);
CREATE INDEX ix_insumos_historico_tipo
    ON catalogo.insumos_historico (ih_tipo_evento);
CREATE INDEX ix_insumos_historico_diff
    ON catalogo.insumos_historico USING GIN (ih_diff);


-- ============================================================
-- ============================================================
--   EXPANSÃO FUTURA — RESERVAS ESTRUTURAIS (não usadas no MVP v1)
-- ============================================================
-- As estruturas abaixo são PREVISÃO de expansão. Existem para
-- deixar o banco escalável — taxonomia/ontologia de insumos,
-- atributos técnicos, códigos externos (NCM/EAN/CATMAT/CATSER/
-- fabricante), pesquisa de preço por NF-e pública (Lei Federal
-- 14.133) e auditoria/evolução histórica de composições — SEM
-- contaminar a regra de negócio inicial.
--
-- NÃO usar como regra de negócio no MVP v1. NÃO serão populadas
-- na primeira versão. Sem parser, carga, integração ou tela ainda.
-- catalogo.insumos continua sendo a identidade principal do insumo,
-- vinculada à sua fonte-base.
-- ============================================================
-- ============================================================


-- ============================================================
-- TABELA: catalogo.insumos_classificacao   [EXPANSÃO FUTURA]
-- Classificação semântica/técnica do insumo — relacional e
-- consultável (sem JSONB). Ex.: família 'tubo pvc', subfamília
-- 'tubo pvc esgoto', categoria 'instalações hidrossanitárias',
-- especificação 'DN 100 mm, série normal', unidade norm. 'barra'.
-- Reserva estrutural — não populada no MVP v1.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.insumos_classificacao (
    ic_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ic_ins_id              INTEGER NOT NULL,
    ic_familia             TEXT,
    ic_subfamilia          TEXT,
    ic_categoria           TEXT,
    ic_especificacao       TEXT,
    ic_unidade_normalizada TEXT,
    ic_criado_em           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ic_atualizado_em       TIMESTAMPTZ,
    ic_criado_por          TEXT,
    ic_atualizado_por      TEXT,

    CONSTRAINT fk_insumos_classificacao_ins
        FOREIGN KEY (ic_ins_id)
        REFERENCES catalogo.insumos (ins_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX ix_insumos_classificacao_ins
    ON catalogo.insumos_classificacao (ic_ins_id);


-- ============================================================
-- TABELA: catalogo.insumos_atributos   [EXPANSÃO FUTURA]
-- Atributos técnicos parametrizados — modelo EAV controlado,
-- relacional (sem JSONB). Ex.: (diametro, 100, mm),
-- (classe, esgoto, NULL), (comprimento, 6, m), (material, PVC, NULL).
-- Reserva estrutural — não populada no MVP v1.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.insumos_atributos (
    ia_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ia_ins_id          INTEGER NOT NULL,
    ia_atributo        TEXT    NOT NULL,
    ia_valor           TEXT,
    ia_unidade         TEXT,
    ia_ordem           INTEGER,
    ia_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ia_atualizado_em   TIMESTAMPTZ,
    ia_criado_por      TEXT,
    ia_atualizado_por  TEXT,

    CONSTRAINT fk_insumos_atributos_ins
        FOREIGN KEY (ia_ins_id)
        REFERENCES catalogo.insumos (ins_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_insumos_atributos_atributo_vazio
        CHECK (btrim(ia_atributo) <> '')
);

CREATE INDEX ix_insumos_atributos_ins
    ON catalogo.insumos_atributos (ia_ins_id);
CREATE INDEX ix_insumos_atributos_atributo
    ON catalogo.insumos_atributos (ia_atributo);


-- ============================================================
-- TABELA: catalogo.insumos_codigos_externos   [EXPANSÃO FUTURA]
-- Vínculo do insumo a códigos externos / fiscais / comerciais.
-- Um insumo pode ter VÁRIOS códigos de tipos diferentes — por isso
-- é tabela, não colunas fixas (ncm/ean/...) em catalogo.insumos.
-- ice_tipo_codigo: NCM | EAN | GTIN | CATMAT | CATSER | FABRICANTE
--   | OUTRO.
-- Reserva estrutural — não populada no MVP v1.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.insumos_codigos_externos (
    ice_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ice_ins_id         INTEGER NOT NULL,
    ice_tipo_codigo    TEXT    NOT NULL,
    ice_codigo         TEXT    NOT NULL,
    ice_descricao      TEXT,
    ice_fonte          TEXT,
    ice_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ice_atualizado_em  TIMESTAMPTZ,
    ice_criado_por     TEXT,
    ice_atualizado_por TEXT,

    CONSTRAINT fk_insumos_codigos_externos_ins
        FOREIGN KEY (ice_ins_id)
        REFERENCES catalogo.insumos (ins_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_insumos_codigos_externos_tipo
        CHECK (ice_tipo_codigo IN
            ('NCM', 'EAN', 'GTIN', 'CATMAT', 'CATSER', 'FABRICANTE', 'OUTRO')),

    CONSTRAINT ck_insumos_codigos_externos_codigo_vazio
        CHECK (btrim(ice_codigo) <> '')
);

CREATE INDEX ix_insumos_codigos_externos_ins
    ON catalogo.insumos_codigos_externos (ice_ins_id);
CREATE INDEX ix_insumos_codigos_externos_tipo_codigo
    ON catalogo.insumos_codigos_externos (ice_tipo_codigo, ice_codigo);


-- ============================================================
-- TABELA: catalogo.insumos_nfe_itens_precos   [EXPANSÃO FUTURA]
-- Preços derivados de itens de NF-e — pesquisa de preço por nota
-- fiscal eletrônica (Lei 14.133). O mapeamento ao catálogo é
-- opcional (nip_ins_id_mapeado NULLABLE), podendo vir de matching
-- semântico. Representação relacional, sem JSONB.
-- Fica em catalogo (mesmo schema de precos_insumo) — sem schema
-- 'precos' separado. Reserva estrutural — não populada no MVP v1.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.insumos_nfe_itens_precos (
    nip_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nip_ins_id_mapeado      INTEGER,
    nip_chave_nfe           TEXT,
    nip_data_emissao        DATE,
    nip_uf                  TEXT,
    nip_municipio           TEXT,
    nip_cnpj_emitente_hash  TEXT,
    nip_descricao_original  TEXT,
    nip_ncm                 TEXT,
    nip_ean                 TEXT,
    nip_unidade             TEXT,
    nip_quantidade          NUMERIC(14,4),
    nip_valor_unitario      NUMERIC(14,4),
    nip_valor_total         NUMERIC(14,4),
    nip_score_mapeamento    NUMERIC(4,3),
    nip_metodo_mapeamento   TEXT,
    nip_criado_em           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_insumos_nfe_itens_precos_ins
        FOREIGN KEY (nip_ins_id_mapeado)
        REFERENCES catalogo.insumos (ins_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_insumos_nfe_itens_precos_score
        CHECK (nip_score_mapeamento IS NULL
               OR (nip_score_mapeamento >= 0 AND nip_score_mapeamento <= 1))
);

CREATE INDEX ix_insumos_nfe_itens_precos_ins
    ON catalogo.insumos_nfe_itens_precos (nip_ins_id_mapeado)
    WHERE nip_ins_id_mapeado IS NOT NULL;
CREATE INDEX ix_insumos_nfe_itens_precos_ncm
    ON catalogo.insumos_nfe_itens_precos (nip_ncm)
    WHERE nip_ncm IS NOT NULL;
CREATE INDEX ix_insumos_nfe_itens_precos_chave
    ON catalogo.insumos_nfe_itens_precos (nip_chave_nfe);


-- ============================================================
-- TABELA: catalogo.composicoes_historico   [EXPANSÃO FUTURA]
-- Trilha de auditoria da EVOLUÇÃO CADASTRAL E ESTRUTURAL das
-- composições entre edições (cabeçalho, itens, situação).
--
-- Previsão estrutural/auditoria — NÃO usar como regra de negócio
-- inicial; NÃO substitui o versionamento por edição. catalogo.composicoes
-- e catalogo.composicao_itens seguem como a estrutura OFICIAL da
-- composição na edição importada; catalogo.custos_composicao, o custo
-- oficial. Reserva — não populada no MVP v1.
--
-- ch_tipo_evento: CRIACAO | ALTERACAO_CABECALHO | ALTERACAO_ITENS |
--   ALTERACAO_CABECALHO_E_ITENS | INATIVACAO | REATIVACAO |
--   ALTERACAO_SITUACAO | ALTERACAO_CUSTO_FONTE |
--   ALTERACAO_CUSTO_CALCULADO | DIVERGENCIA_CUSTO.
-- JSONB INTENCIONAL: o conjunto de alterações estruturais varia muito
--   entre edições (snapshot/diff documental). Append-only (sem _atualizado_*).
--
-- ESTRUTURA RECOMENDADA do ch_diff por tipo (NÃO contrato rígido — pode
--   variar conforme fonte-base, parser e tipo de alteração):
--   ALTERACAO_CABECALHO → {cabecalho:{descricao:{de,para}, unidade:{de,para},
--                          situacao:{de,para}}}
--   ALTERACAO_ITENS     → {itens:{incluidos:[{tipo,codigo,descricao,unidade,
--                          coeficiente,situacao}], excluidos:[...],
--                          alterados:[{tipo,codigo,campo,de,para}]}}
--   ALTERACAO_SITUACAO  → {situacao:{de,para,motivo}, itens_criticos:[{tipo,
--                          codigo,descricao,situacao}]}
--   ALTERACAO_CUSTO_* / DIVERGENCIA_CUSTO → {custos:{uf, modalidade,
--                          custo_fonte:{de,para}, custo_calculado:{de,para},
--                          diferenca_valor:{de,para}, diferenca_percentual:{de,para},
--                          status_conferencia:{de,para}}}
--   ch_dados_anteriores / ch_dados_novos: snapshot do cabeçalho na edição
--                          origem / nova.
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.composicoes_historico (
    ch_id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ch_cmp_id_origem    INTEGER,
    ch_cmp_id_novo      INTEGER,
    ch_fte_id           INTEGER NOT NULL,
    ch_codigo           TEXT    NOT NULL,
    ch_edi_id_origem    INTEGER,
    ch_edi_id_nova      INTEGER,
    ch_tipo_evento      TEXT    NOT NULL,
    ch_dados_anteriores JSONB,
    ch_dados_novos      JSONB,
    ch_diff             JSONB,
    ch_observacao       TEXT,
    ch_criado_em        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ch_criado_por       TEXT,

    CONSTRAINT fk_composicoes_historico_cmp_origem
        FOREIGN KEY (ch_cmp_id_origem)
        REFERENCES catalogo.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_composicoes_historico_cmp_novo
        FOREIGN KEY (ch_cmp_id_novo)
        REFERENCES catalogo.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_composicoes_historico_fte
        FOREIGN KEY (ch_fte_id)
        REFERENCES catalogo.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_composicoes_historico_edi_origem
        FOREIGN KEY (ch_edi_id_origem)
        REFERENCES catalogo.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_composicoes_historico_edi_nova
        FOREIGN KEY (ch_edi_id_nova)
        REFERENCES catalogo.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_composicoes_historico_tipo_evento
        CHECK (ch_tipo_evento IN (
            'CRIACAO', 'ALTERACAO_CABECALHO', 'ALTERACAO_ITENS',
            'ALTERACAO_CABECALHO_E_ITENS', 'INATIVACAO', 'REATIVACAO',
            'ALTERACAO_SITUACAO', 'ALTERACAO_CUSTO_FONTE',
            'ALTERACAO_CUSTO_CALCULADO', 'DIVERGENCIA_CUSTO'
        ))
);

CREATE INDEX ix_composicoes_historico_fte_codigo
    ON catalogo.composicoes_historico (ch_fte_id, ch_codigo);
CREATE INDEX ix_composicoes_historico_edis
    ON catalogo.composicoes_historico (ch_edi_id_origem, ch_edi_id_nova);
CREATE INDEX ix_composicoes_historico_tipo
    ON catalogo.composicoes_historico (ch_tipo_evento);
CREATE INDEX ix_composicoes_historico_cmp_origem
    ON catalogo.composicoes_historico (ch_cmp_id_origem);
CREATE INDEX ix_composicoes_historico_cmp_novo
    ON catalogo.composicoes_historico (ch_cmp_id_novo);


-- ============================================================
-- TABELA: catalogo.composicoes_alertas_custo   [EXPANSÃO FUTURA]
-- Alertas técnicos de custo/situação por composição e edição —
-- futura explicação de POR QUE uma composição está SEM CUSTO, sem
-- misturar com o cálculo oficial de custo (custos_composicao).
-- Previsão estrutural — não usar operacionalmente agora; não
-- populada no MVP v1.
--
-- cac_tipo_alerta: ITEM_SEM_PRECO | SUBCOMPOSICAO_SEM_CUSTO |
--   COMPOSICAO_SEM_CUSTO | CUSTO_OFICIAL_ZERO | DIVERGENCIA_ESTRUTURAL |
--   DIVERGENCIA_CUSTO_FONTE_CALCULADO.
-- Campos opcionais cac_uf / cac_modalidade / cac_custo_fonte /
--   cac_custo_calculado / cac_diferenca_* / cac_status_conferencia
--   detalham o alerta de divergência fonte × cálculo (espelham
--   catalogo.custos_composicao).
-- ============================================================
CREATE TABLE IF NOT EXISTS catalogo.composicoes_alertas_custo (
    cac_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cac_cmp_id         INTEGER NOT NULL,
    cac_edi_id         INTEGER NOT NULL,
    cac_tipo_alerta    TEXT    NOT NULL,
    cac_codigo_item    TEXT,
    cac_tipo_item      TEXT,
    cac_descricao_item TEXT,
    cac_situacao_item  TEXT,
    cac_uf             CHAR(2),
    cac_modalidade     CHAR(2),
    cac_custo_fonte         NUMERIC(14,4),
    cac_custo_calculado     NUMERIC(14,4),
    cac_diferenca_valor     NUMERIC(14,4),
    cac_diferenca_percentual NUMERIC(12,6),
    cac_status_conferencia  TEXT,
    cac_observacao     TEXT,
    cac_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_composicoes_alertas_custo_cmp
        FOREIGN KEY (cac_cmp_id)
        REFERENCES catalogo.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_composicoes_alertas_custo_edi
        FOREIGN KEY (cac_edi_id)
        REFERENCES catalogo.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_composicoes_alertas_custo_tipo
        CHECK (cac_tipo_alerta IN (
            'ITEM_SEM_PRECO', 'SUBCOMPOSICAO_SEM_CUSTO', 'COMPOSICAO_SEM_CUSTO',
            'CUSTO_OFICIAL_ZERO', 'DIVERGENCIA_ESTRUTURAL',
            'DIVERGENCIA_CUSTO_FONTE_CALCULADO'
        ))
);

CREATE INDEX ix_composicoes_alertas_custo_cmp_edi
    ON catalogo.composicoes_alertas_custo (cac_cmp_id, cac_edi_id);
CREATE INDEX ix_composicoes_alertas_custo_tipo
    ON catalogo.composicoes_alertas_custo (cac_tipo_alerta);


-- ============================================================
-- SCHEMA: audit
-- Trilha de auditoria. Append-only — sem UPDATE nem DELETE via app.
--
-- Tabelas ativas:
--   audit.logs_retencao     — políticas de retenção (lookup controlado
--                             pelo gestor tech — users não vêem)
--   audit.criterio_retencao — mapeamento (schema, tabela) → política
--   audit.logs              — histórico de alterações em dados
--   audit.login_logs        — eventos de autenticação e origem
--   audit.api_logs          — chamadas externas à API (writes only)
--
-- Limpeza periódica (dias 5/10/15/20/25 de cada mês, 02h00):
--
--   DELETE FROM audit.logs l
--   USING audit.criterio_retencao cr
--   JOIN  audit.logs_retencao lr ON cr.crit_ret_id = lr.ret_id
--   WHERE cr.crit_schema   = l.log_schema
--     AND cr.crit_tabela   = l.log_tabela
--     AND lr.ret_permanente = false
--     AND l.log_criado_em  < NOW() - (lr.ret_dias || ' days')::INTERVAL;
--
--   Tabelas SEM critério definido → NÃO deletadas (seguro por omissão).
--   Detectar tabelas não configuradas:
--     SELECT DISTINCT log_schema, log_tabela FROM audit.logs l
--     WHERE NOT EXISTS (
--         SELECT 1 FROM audit.criterio_retencao cr
--         WHERE cr.crit_schema = l.log_schema
--           AND cr.crit_tabela = l.log_tabela
--     );
--
-- ── Arquitetura futura: sanitização de dados de tenants ──────
--
-- Distinção importante: limpeza de logs ≠ sanitização de dados.
-- A sanitização afeta dados de negócio do tenant (futuro módulo
-- "ativo") de tenants que encerraram uso. Por isso, o worker deve
-- ser tratado em separado do cleanup de audit.logs.
--
-- Tabelas previstas (a implementar quando o módulo "ativo" estiver maduro):
--
--   audit.logs_retencao_by_tenant
--     id, tenant_id, tenant_role
--     → marca tenants que NÃO podem ter dados tocados,
--       independente do critério global de retenção.
--
--   audit.logs_table_arquivar_r2
--     id, schema, tabela
--     → cataloga quais tabelas devem ter seus dados exportados
--       para R2 como CSV antes da sanitização (fallback de controle).
--
-- Worker executar_limpeza() — três passagens:
--   1. retencao_criterios()    → avalia quais tabelas/registros limpar
--   2. retencao_by_tenant()    → exclui UUIDs de tenants protegidos
--   3. gerar_backup_tenants()  → exporta CSV para R2 os registros
--                                 que serão sanitizados
--   DELETE final apenas após o backup confirmado no R2.
--
-- Rationale: tenants de uso único geram orçamentos e não retornam.
-- O banco é sanitizado, mas o dado fica no R2 ad-aeternum como
-- fallback para reinsert controlado se necessário.
-- Tudo na app é auditável — este schema é o lugar canônico para
-- documentar essa intenção.
--
-- Decisões de design:
--   - Retenção determinada no momento da limpeza (não gravada por linha)
--     → política pode ser ajustada retroativamente sem perda silenciosa
--   - Sem FK para tabelas de negócio (sobrevive a soft/hard delete)
--   - audit.logs: full JSON em cadastros, diff parcial em alta frequência
--   - audit.api_logs: apenas writes (POST/PUT/DELETE); GETs ignorados
--   - audit.login_logs: campo origem prevê OAuth futuro (gov.br, Apple…)
-- ============================================================

CREATE SCHEMA IF NOT EXISTS audit;

GRANT USAGE ON SCHEMA audit TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA audit
    GRANT SELECT, INSERT ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA audit
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";


-- ------------------------------------------------------------
-- audit.logs_retencao — políticas de retenção (lookup)
-- Seed inicial em easy_seed.sql.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.logs_retencao (
    ret_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ret_descricao   TEXT    NOT NULL,
    ret_permanente  BOOLEAN NOT NULL DEFAULT false,
    ret_dias        INTEGER NULL,

    CONSTRAINT ck_retencao_permanencia CHECK (
        (ret_permanente = true  AND ret_dias IS NULL)
        OR
        (ret_permanente = false AND ret_dias IS NOT NULL AND ret_dias > 0)
    )
);


-- ------------------------------------------------------------
-- audit.criterio_retencao — mapeamento (schema, tabela) → política
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.criterio_retencao (
    crit_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crit_schema   TEXT    NOT NULL,
    crit_tabela   TEXT    NOT NULL,
    crit_ret_id   INTEGER NOT NULL,

    CONSTRAINT fk_criterio_retencao
        FOREIGN KEY (crit_ret_id)
        REFERENCES audit.logs_retencao (ret_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_criterio_schema_tabela
        UNIQUE (crit_schema, crit_tabela)
);

CREATE INDEX ix_criterio_schema_tabela
    ON audit.criterio_retencao (crit_schema, crit_tabela);


-- ------------------------------------------------------------
-- audit.logs — histórico de alterações em dados
-- Retenção determinada por audit.criterio_retencao no cleanup job.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.logs (
    log_id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- O quê
    log_schema       TEXT          NOT NULL,
    log_tabela       TEXT          NOT NULL,
    log_registro_id  TEXT          NOT NULL,
    log_acao         TEXT          NOT NULL
                     CHECK (log_acao IN ('INSERT', 'UPDATE', 'DELETE')),

    -- Quem / quando
    log_usuario      TEXT          NOT NULL,
    log_ip           TEXT,

    -- Como estava / como ficou
    log_dados_antes  JSONB,
    log_dados_depois JSONB,

    log_criado_em    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_audit_logs_registro
    ON audit.logs (log_tabela, log_registro_id);
CREATE INDEX ix_audit_logs_usuario
    ON audit.logs (log_usuario);
CREATE INDEX ix_audit_logs_criado_em
    ON audit.logs (log_criado_em DESC);


-- ------------------------------------------------------------
-- audit.login_logs — eventos de autenticação e origem
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.login_logs (
    log_id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    log_user_id     TEXT,
    log_email       TEXT,
    log_nome        TEXT,
    log_tenant_id   TEXT,

    log_acao        TEXT         NOT NULL
                    CHECK (log_acao IN ('LOGIN', 'LOGOUT', 'LOGIN_FALHA')),

    log_origem      TEXT         NOT NULL DEFAULT 'LOCAL'
                    CHECK (log_origem IN (
                        'LOCAL',
                        'GOV_BR',
                        'APPLE',
                        'GOOGLE',
                        'API_KEY'
                    )),

    log_ip          TEXT,
    log_user_agent  TEXT,
    log_detalhes    JSONB,

    log_criado_em   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_audit_login_email
    ON audit.login_logs (log_email);
CREATE INDEX ix_audit_login_user_id
    ON audit.login_logs (log_user_id)
    WHERE log_user_id IS NOT NULL;
CREATE INDEX ix_audit_login_criado_em
    ON audit.login_logs (log_criado_em DESC);


-- ------------------------------------------------------------
-- audit.api_logs — chamadas externas à API (writes only)
-- Registra POST/PUT/PATCH/DELETE; GETs ignorados.
-- audit.api_logs captura o contexto HTTP; audit.logs captura o dado.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.api_logs (
    log_id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    log_method      TEXT         NOT NULL
                    CHECK (log_method IN ('POST', 'PUT', 'PATCH', 'DELETE')),
    log_endpoint    TEXT         NOT NULL,
    log_status      SMALLINT     NOT NULL,

    log_cliente     TEXT,
    log_usuario     TEXT,
    log_ip          TEXT,

    log_corpo_req   JSONB,
    log_duracao_ms  INTEGER,

    log_criado_em   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_audit_api_endpoint
    ON audit.api_logs (log_endpoint, log_criado_em DESC);
CREATE INDEX ix_audit_api_cliente
    ON audit.api_logs (log_cliente)
    WHERE log_cliente IS NOT NULL;
CREATE INDEX ix_audit_api_criado_em
    ON audit.api_logs (log_criado_em DESC);


