-- ============================================================
-- Axys-Gestor / SL — Schema SQL
-- Banco: PostgreSQL 14+
-- Schemas: organization · catalog · planning · orders · purchases · tickets · royalties · audit
--
-- organization : cadastros organizacionais, parceiros, fornecedores, vínculos e segredos por loja.
-- catalog      : catálogo mestre de coleções, grupos, tipos, grades, produtos e anexos.
-- planning     : reservado para evolução futura de planejamento de coleção/compras.
-- orders       : pedidos comerciais por loja.
-- purchases    : compras / notas fiscais e seus itens.
-- tickets      : contestações, abatimentos e histórico operacional.
-- royalties    : consolidação e conciliação de royalties / marketing.
-- audit        : trilha de auditoria, login, API e políticas de retenção.
--
-- Decisões de arquitetura
-- ───────────────────────
-- NOMENCLATURA
--   Tabelas e colunas em inglês. Comentários, seeds e checks textuais em português-BR.
--   Mantém aderência ao ecossistema Axys e ao contrato interno da aplicação.
--
-- CHAVES / TENANCY
--   Tabelas transacionais usam BIGINT IDENTITY.
--   Entidades de cadastro usam INTEGER IDENTITY quando aplicável.
--   UUIDs de tenant/store/partner são gravados conforme contrato externo da app.
--
-- AUDITORIA
--   Onde aplicável: created_at, updated_at, created_by, updated_by.
--   Tabelas de anexos / histórico guardam apenas criação por serem eventos imutáveis.
--
-- VALORES / TIPOS
--   Timestamps: TIMESTAMPTZ; datas: DATE.
--   Valores monetários: NUMERIC(14,2).
--   JSONB estruturais são contrato interno da aplicação.
--
-- OBSERVAÇÃO
--   O schema planning é criado agora, mas suas tabelas ficam reservadas para evolução futura.
-- ============================================================

SET client_min_messages = WARNING;


-- ============================================================
-- SCHEMAS / PRIVILEGES
-- ============================================================
CREATE SCHEMA IF NOT EXISTS organization;

GRANT USAGE ON SCHEMA organization TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA organization
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA organization
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";

CREATE SCHEMA IF NOT EXISTS catalog;

GRANT USAGE ON SCHEMA catalog TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA catalog
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA catalog
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";

CREATE SCHEMA IF NOT EXISTS planning;

GRANT USAGE ON SCHEMA planning TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA planning
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA planning
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";

CREATE SCHEMA IF NOT EXISTS orders;

GRANT USAGE ON SCHEMA orders TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA orders
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA orders
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";

CREATE SCHEMA IF NOT EXISTS purchases;

GRANT USAGE ON SCHEMA purchases TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA purchases
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA purchases
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";

CREATE SCHEMA IF NOT EXISTS tickets;

GRANT USAGE ON SCHEMA tickets TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA tickets
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA tickets
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";

CREATE SCHEMA IF NOT EXISTS royalties;

GRANT USAGE ON SCHEMA royalties TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA royalties
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA royalties
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";

CREATE SCHEMA IF NOT EXISTS audit;

GRANT USAGE ON SCHEMA audit TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA audit
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA audit
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";

-- ============================================================
-- SCHEMA: organization
-- ============================================================


CREATE TABLE IF NOT EXISTS organization.brand (
    brand_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description     TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ,
    created_by      TEXT,
    updated_by      TEXT,

    CONSTRAINT uq_brand_description
        UNIQUE (description),

    CONSTRAINT ck_brand_description_not_blank
        CHECK (btrim(description) <> '')
);


CREATE TABLE IF NOT EXISTS organization.brand_revenue (
    brand_revenue_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id            INTEGER NOT NULL,
    description         TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ,
    created_by          TEXT,
    updated_by          TEXT,

    CONSTRAINT fk_brand_revenue_brand
        FOREIGN KEY (brand_id) REFERENCES organization.brand (brand_id),

    CONSTRAINT uq_brand_revenue_brand_description
        UNIQUE (brand_id, description),

    CONSTRAINT ck_brand_revenue_description_not_blank
        CHECK (btrim(description) <> '')
);


CREATE TABLE IF NOT EXISTS organization.group_enterprise (
    group_enterprise_uuid    UUID PRIMARY KEY,
    enterprise_name          TEXT NOT NULL,
    brand_id                 INTEGER NOT NULL,
    brand_revenue_id         INTEGER NOT NULL,
    documents_json           JSONB NOT NULL DEFAULT '{}'::jsonb,
    addresses_json           JSONB NOT NULL DEFAULT '[]'::jsonb,
    contacts_json            JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ,
    created_by               TEXT,
    updated_by               TEXT,

    CONSTRAINT fk_group_enterprise_brand
        FOREIGN KEY (brand_id) REFERENCES organization.brand (brand_id),

    CONSTRAINT fk_group_enterprise_brand_revenue
        FOREIGN KEY (brand_revenue_id) REFERENCES organization.brand_revenue (brand_revenue_id),

    CONSTRAINT ck_group_enterprise_name_not_blank
        CHECK (btrim(enterprise_name) <> '')
);


CREATE TABLE IF NOT EXISTS organization.partner (
    partner_uuid         UUID PRIMARY KEY,
    partner_name         TEXT NOT NULL,
    documents_json       JSONB NOT NULL DEFAULT '{}'::jsonb,
    addresses_json       JSONB NOT NULL DEFAULT '[]'::jsonb,
    contacts_json        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ,
    created_by           TEXT,
    updated_by           TEXT,

    CONSTRAINT ck_partner_name_not_blank
        CHECK (btrim(partner_name) <> '')
);


CREATE TABLE IF NOT EXISTS organization.supplier (
    supplier_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_name           TEXT NOT NULL,
    documents_json       JSONB NOT NULL DEFAULT '{}'::jsonb,
    addresses_json       JSONB NOT NULL DEFAULT '[]'::jsonb,
    contacts_json        JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata_json        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ,
    created_by           TEXT,
    updated_by           TEXT,

    CONSTRAINT ck_supplier_legal_name_not_blank
        CHECK (btrim(legal_name) <> '')
);


CREATE TABLE IF NOT EXISTS organization.tenant_store (
    tenant_uuid      UUID NOT NULL,
    store_uuid       UUID NOT NULL,
    partner_uuid     UUID NOT NULL,
    license_active   BOOLEAN NOT NULL DEFAULT TRUE,
    synced_at        TIMESTAMPTZ,

    CONSTRAINT uq_tenant_store
        UNIQUE (tenant_uuid, store_uuid, partner_uuid),

    CONSTRAINT fk_tenant_store_partner
        FOREIGN KEY (partner_uuid) REFERENCES organization.partner (partner_uuid)
);


CREATE TABLE IF NOT EXISTS organization.store_secrets (
    store_uuid                  UUID PRIMARY KEY,
    secrets_json_encrypted      JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- SCHEMA: catalog
-- ============================================================
CREATE TABLE IF NOT EXISTS catalog.collection (
    collection_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id         INTEGER NOT NULL,
    description      TEXT NOT NULL,
    season           TEXT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ,
    created_by       TEXT,
    updated_by       TEXT,

    CONSTRAINT fk_collection_brand
        FOREIGN KEY (brand_id) REFERENCES organization.brand (brand_id),

    CONSTRAINT uq_collection_brand_description_season
        UNIQUE (brand_id, description, season),

    CONSTRAINT ck_collection_description_not_blank
        CHECK (btrim(description) <> ''),

    CONSTRAINT ck_collection_season
        CHECK (season IN ('VERAO', 'OUTONO', 'INVERNO', 'PRIMAVERA'))
);


CREATE TABLE IF NOT EXISTS catalog.product_group (
    product_group_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description         TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ,
    created_by          TEXT,
    updated_by          TEXT,

    CONSTRAINT uq_product_group_description
        UNIQUE (description),

    CONSTRAINT ck_product_group_description_not_blank
        CHECK (btrim(description) <> '')
);


CREATE TABLE IF NOT EXISTS catalog.product_type (
    product_type_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_group_id    INTEGER NOT NULL,
    description         TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ,
    created_by          TEXT,
    updated_by          TEXT,

    CONSTRAINT fk_product_type_group
        FOREIGN KEY (product_group_id) REFERENCES catalog.product_group (product_group_id),

    CONSTRAINT uq_product_type_group_description
        UNIQUE (product_group_id, description),

    CONSTRAINT ck_product_type_description_not_blank
        CHECK (btrim(description) <> '')
);


CREATE TABLE IF NOT EXISTS catalog.product_grade (
    product_grade_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description         TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ,
    created_by          TEXT,
    updated_by          TEXT,

    CONSTRAINT uq_product_grade_description
        UNIQUE (description),

    CONSTRAINT ck_product_grade_description_not_blank
        CHECK (btrim(description) <> '')
);


CREATE TABLE IF NOT EXISTS catalog.product (
    product_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id                    INTEGER NOT NULL,
    product_group_id            INTEGER NOT NULL,
    product_type_id             INTEGER NOT NULL,
    product_grade_id            INTEGER NOT NULL,
    sku                         TEXT NOT NULL,
    description                 TEXT NOT NULL,
    product_main_photo_path     TEXT,
    product_photos_path         JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ,
    created_by                  TEXT,
    updated_by                  TEXT,

    CONSTRAINT fk_product_brand
        FOREIGN KEY (brand_id) REFERENCES organization.brand (brand_id),

    CONSTRAINT fk_product_group
        FOREIGN KEY (product_group_id) REFERENCES catalog.product_group (product_group_id),

    CONSTRAINT fk_product_type
        FOREIGN KEY (product_type_id) REFERENCES catalog.product_type (product_type_id),

    CONSTRAINT fk_product_grade
        FOREIGN KEY (product_grade_id) REFERENCES catalog.product_grade (product_grade_id),

    CONSTRAINT uq_product_brand_sku
        UNIQUE (brand_id, sku),

    CONSTRAINT ck_product_sku_not_blank
        CHECK (btrim(sku) <> ''),

    CONSTRAINT ck_product_description_not_blank
        CHECK (btrim(description) <> '')
);


CREATE TABLE IF NOT EXISTS catalog.attachment_type (
    attachment_type_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  TEXT NOT NULL,
    code                  TEXT NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ,
    created_by            TEXT,
    updated_by            TEXT,

    CONSTRAINT uq_attachment_type_name
        UNIQUE (name),

    CONSTRAINT uq_attachment_type_code
        UNIQUE (code),

    CONSTRAINT ck_attachment_type_name_not_blank
        CHECK (btrim(name) <> ''),

    CONSTRAINT ck_attachment_type_code_not_blank
        CHECK (btrim(code) <> '')
);


INSERT INTO catalog.product_group (description, created_by)
SELECT v.description, 'Axys-Gestor / SL — seed inicial'
FROM (VALUES
    ('Calçados'),
    ('Bolsas'),
    ('Carteiras')
) AS v(description)
ON CONFLICT (description) DO NOTHING;


INSERT INTO catalog.product_type (product_group_id, description, created_by)
SELECT pg.product_group_id, v.description, 'Axys-Gestor / SL — seed inicial'
FROM (VALUES
    ('Calçados', 'Anabela'),
    ('Bolsas', 'Bolsa'),
    ('Calçados', 'Boneca'),
    ('Calçados', 'Bota'),
    ('Carteiras', 'Carteira'),
    ('Bolsas', 'Clutch'),
    ('Calçados', 'Espadrilhe'),
    ('Calçados', 'Flip Flop'),
    ('Bolsas', 'Mala'),
    ('Calçados', 'Mocassim'),
    ('Bolsas', 'Mochila'),
    ('Calçados', 'Mule'),
    ('Bolsas', 'Necessaire'),
    ('Calçados', 'Overknee'),
    ('Calçados', 'Papete'),
    ('Calçados', 'Peep Toe'),
    ('Calçados', 'Plataforma'),
    ('Carteiras', 'Porta Cartão'),
    ('Carteiras', 'Porta Passaporte'),
    ('Calçados', 'Rasteira'),
    ('Calçados', 'Sandália'),
    ('Calçados', 'Sapatilha'),
    ('Calçados', 'Scarpin'),
    ('Bolsas', 'Shopper'),
    ('Calçados', 'Slide'),
    ('Calçados', 'Slip On'),
    ('Calçados', 'Tênis'),
    ('Bolsas', 'Tote')
) AS v(group_description, description)
JOIN catalog.product_group pg
  ON pg.description = v.group_description
ON CONFLICT (product_group_id, description) DO NOTHING;


INSERT INTO catalog.product_grade (description, created_by)
SELECT v.description, 'Axys-Gestor / SL — seed inicial'
FROM (VALUES
    ('34'),
    ('35'),
    ('36'),
    ('37'),
    ('38'),
    ('39'),
    ('40'),
    ('33/4'),
    ('34/5'),
    ('35/6'),
    ('36/7'),
    ('37/8'),
    ('38/9'),
    ('39/0'),
    ('40/1'),
    ('PC')
) AS v(description)
ON CONFLICT (description) DO NOTHING;


INSERT INTO catalog.attachment_type (name, code, created_by)
SELECT v.name, v.code, 'Axys-Gestor / SL — seed inicial'
FROM (VALUES
    ('NFe', 'NFE'),
    ('NFSe', 'NFSE'),
    ('CTe', 'CTE'),
    ('Ficha de Royalties', 'FICHA_ROYALTIES'),
    ('Ficha de Tickets', 'FICHA_TICKETS'),
    ('Comprovante', 'COMPROVANTE'),
    ('E-mail', 'EMAIL'),
    ('Boleto', 'BOLETO'),
    ('Documento de Cobrança', 'COBRANCA'),
    ('Comprovante de Recusa', 'RECUSA'),
    ('Outro', 'OUTRO')
) AS v(name, code)
ON CONFLICT (code) DO NOTHING;


-- ============================================================
-- SCHEMA: planning
-- ============================================================
-- ============================================================
-- SCHEMA: orders
-- ============================================================
CREATE TABLE IF NOT EXISTS orders."order" (
    order_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_uuid                UUID NOT NULL,
    supplier_id               INTEGER NOT NULL,
    collection_id             INTEGER NOT NULL,
    order_number              TEXT NOT NULL,
    order_attachments_json    JSONB NOT NULL DEFAULT '[]'::jsonb,
    total_qty                 INTEGER NOT NULL DEFAULT 0,
    total_amount              NUMERIC(14,2) NOT NULL DEFAULT 0,
    status                    TEXT NOT NULL DEFAULT 'RASCUNHO',
    created_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMPTZ,
    created_by                TEXT,
    updated_by                TEXT,

    CONSTRAINT fk_order_supplier
        FOREIGN KEY (supplier_id) REFERENCES organization.supplier (supplier_id) ON DELETE RESTRICT,

    CONSTRAINT fk_order_collection
        FOREIGN KEY (collection_id) REFERENCES catalog.collection (collection_id) ON DELETE RESTRICT,

    CONSTRAINT uq_order_store_order_number
        UNIQUE (store_uuid, order_number),

    CONSTRAINT ck_order_number_not_blank
        CHECK (btrim(order_number) <> ''),

    CONSTRAINT ck_order_total_qty_non_negative
        CHECK (total_qty >= 0),

    CONSTRAINT ck_order_total_amount_non_negative
        CHECK (total_amount >= 0),

    CONSTRAINT ck_order_status
        CHECK (status IN ('RASCUNHO', 'APROVADO', 'FATURADO', 'CANCELADO'))
);


CREATE TABLE IF NOT EXISTS orders.order_product (
    order_product_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                 BIGINT NOT NULL,
    product_id               INTEGER NOT NULL,
    sell_in_unit_price       NUMERIC(14,2) NOT NULL DEFAULT 0,
    sell_in_total_amount     NUMERIC(14,2) NOT NULL DEFAULT 0,
    sell_out_unit_price      NUMERIC(14,2),
    sell_out_total_amount    NUMERIC(14,2),
    total_qty                INTEGER NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ,
    created_by               TEXT,
    updated_by               TEXT,

    CONSTRAINT fk_order_product_order
        FOREIGN KEY (order_id) REFERENCES orders."order" (order_id) ON DELETE CASCADE,

    CONSTRAINT fk_order_product_product
        FOREIGN KEY (product_id) REFERENCES catalog.product (product_id) ON DELETE RESTRICT,

    CONSTRAINT uq_order_product_order_product
        UNIQUE (order_id, product_id),

    CONSTRAINT ck_order_product_sell_in_unit_price_non_negative
        CHECK (sell_in_unit_price >= 0),

    CONSTRAINT ck_order_product_sell_in_total_amount_non_negative
        CHECK (sell_in_total_amount >= 0),

    CONSTRAINT ck_order_product_sell_out_unit_price_non_negative
        CHECK (sell_out_unit_price IS NULL OR sell_out_unit_price >= 0),

    CONSTRAINT ck_order_product_sell_out_total_amount_non_negative
        CHECK (sell_out_total_amount IS NULL OR sell_out_total_amount >= 0),

    CONSTRAINT ck_order_product_total_qty_non_negative
        CHECK (total_qty >= 0)
);


CREATE TABLE IF NOT EXISTS orders.order_product_grade (
    order_product_grade_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_product_id          BIGINT NOT NULL,
    grade_size                TEXT NOT NULL,
    quantity                  INTEGER NOT NULL DEFAULT 0,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMPTZ,
    created_by                TEXT,
    updated_by                TEXT,

    CONSTRAINT fk_order_product_grade_order_product
        FOREIGN KEY (order_product_id) REFERENCES orders.order_product (order_product_id) ON DELETE CASCADE,

    CONSTRAINT uq_order_product_grade_size
        UNIQUE (order_product_id, grade_size),

    CONSTRAINT ck_order_product_grade_size_not_blank
        CHECK (btrim(grade_size) <> ''),

    CONSTRAINT ck_order_product_grade_quantity_non_negative
        CHECK (quantity >= 0)
);


-- ============================================================
-- SCHEMA: purchases
-- ============================================================
CREATE TABLE IF NOT EXISTS purchases.purchase (
    purchase_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_uuid                  UUID NOT NULL,
    supplier_id                 INTEGER NOT NULL,
    collection_id               INTEGER NOT NULL,
    purchase_number             TEXT NOT NULL,
    purchase_nfe_key            TEXT,
    purchase_attachments_json   JSONB NOT NULL DEFAULT '[]'::jsonb,
    total_amount_supplier       NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_amount_royalties      NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_amount_marketing      NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_amount                NUMERIC(14,2) NOT NULL DEFAULT 0,
    purchase_status             TEXT NOT NULL DEFAULT 'LANCADO',
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ,
    created_by                  TEXT,
    updated_by                  TEXT,

    CONSTRAINT fk_purchase_supplier
        FOREIGN KEY (supplier_id) REFERENCES organization.supplier (supplier_id) ON DELETE RESTRICT,

    CONSTRAINT fk_purchase_collection
        FOREIGN KEY (collection_id) REFERENCES catalog.collection (collection_id) ON DELETE RESTRICT,

    CONSTRAINT uq_purchase_store_number
        UNIQUE (store_uuid, purchase_number),

    CONSTRAINT uq_purchase_nfe_key
        UNIQUE (purchase_nfe_key),

    CONSTRAINT ck_purchase_number_not_blank
        CHECK (btrim(purchase_number) <> ''),

    CONSTRAINT ck_purchase_nfe_key_not_blank
        CHECK (purchase_nfe_key IS NULL OR btrim(purchase_nfe_key) <> ''),

    CONSTRAINT ck_purchase_total_amount_supplier_non_negative
        CHECK (total_amount_supplier >= 0),

    CONSTRAINT ck_purchase_total_amount_royalties_non_negative
        CHECK (total_amount_royalties >= 0),

    CONSTRAINT ck_purchase_total_amount_marketing_non_negative
        CHECK (total_amount_marketing >= 0),

    CONSTRAINT ck_purchase_total_amount_non_negative
        CHECK (total_amount >= 0),

    CONSTRAINT ck_purchase_status
        CHECK (purchase_status IN ('LANCADO', 'RECEBIDO', 'RECUSADO', 'NAO_RECEBIDO'))
);


CREATE TABLE IF NOT EXISTS purchases.purchase_product (
    purchase_product_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id            BIGINT NOT NULL,
    product_id             INTEGER NOT NULL,
    unit_price             NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_qty              INTEGER NOT NULL DEFAULT 0,
    total_amount           NUMERIC(14,2) NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ,
    created_by             TEXT,
    updated_by             TEXT,

    CONSTRAINT fk_purchase_product_purchase
        FOREIGN KEY (purchase_id) REFERENCES purchases.purchase (purchase_id) ON DELETE CASCADE,

    CONSTRAINT fk_purchase_product_product
        FOREIGN KEY (product_id) REFERENCES catalog.product (product_id) ON DELETE RESTRICT,

    CONSTRAINT uq_purchase_product_purchase_product
        UNIQUE (purchase_id, product_id),

    CONSTRAINT ck_purchase_product_unit_price_non_negative
        CHECK (unit_price >= 0),

    CONSTRAINT ck_purchase_product_total_qty_non_negative
        CHECK (total_qty >= 0),

    CONSTRAINT ck_purchase_product_total_amount_non_negative
        CHECK (total_amount >= 0)
);


CREATE TABLE IF NOT EXISTS purchases.purchase_product_grade (
    purchase_product_grade_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_product_id          BIGINT NOT NULL,
    grade_size                   TEXT NOT NULL,
    quantity                     INTEGER NOT NULL DEFAULT 0,
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   TIMESTAMPTZ,
    created_by                   TEXT,
    updated_by                   TEXT,

    CONSTRAINT fk_purchase_product_grade_purchase_product
        FOREIGN KEY (purchase_product_id) REFERENCES purchases.purchase_product (purchase_product_id) ON DELETE CASCADE,

    CONSTRAINT uq_purchase_product_grade_size
        UNIQUE (purchase_product_id, grade_size),

    CONSTRAINT ck_purchase_product_grade_size_not_blank
        CHECK (btrim(grade_size) <> ''),

    CONSTRAINT ck_purchase_product_grade_quantity_non_negative
        CHECK (quantity >= 0)
);


-- ============================================================
-- SCHEMA: tickets
-- ============================================================
CREATE TABLE IF NOT EXISTS tickets.ticket (
    ticket_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_uuid                UUID NOT NULL,
    ticket_number             TEXT NOT NULL,
    ticket_type               TEXT NOT NULL,
    purchase_id               BIGINT,
    order_id                  BIGINT,
    ticket_status             TEXT NOT NULL DEFAULT 'LANCADO',
    total_amount_claimed      NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_amount_approved     NUMERIC(14,2) NOT NULL DEFAULT 0,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMPTZ,
    created_by                TEXT,
    updated_by                TEXT,

    CONSTRAINT fk_ticket_purchase
        FOREIGN KEY (purchase_id) REFERENCES purchases.purchase (purchase_id) ON DELETE SET NULL,

    CONSTRAINT fk_ticket_order
        FOREIGN KEY (order_id) REFERENCES orders."order" (order_id) ON DELETE SET NULL,

    CONSTRAINT uq_ticket_store_number
        UNIQUE (store_uuid, ticket_number),

    CONSTRAINT ck_ticket_number_not_blank
        CHECK (btrim(ticket_number) <> ''),

    CONSTRAINT ck_ticket_type_not_blank
        CHECK (btrim(ticket_type) <> ''),

    CONSTRAINT ck_ticket_status
        CHECK (ticket_status IN ('LANCADO', 'DEVIDO', 'CONVERTIDO', 'RECUSADO', 'PAGO')),

    CONSTRAINT ck_ticket_total_amount_claimed_non_negative
        CHECK (total_amount_claimed >= 0),

    CONSTRAINT ck_ticket_total_amount_approved_non_negative
        CHECK (total_amount_approved >= 0)
);


CREATE TABLE IF NOT EXISTS tickets.ticket_debtor_split (
    ticket_debtor_split_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id                 BIGINT NOT NULL,
    brand_revenue_id          INTEGER,
    group_enterprise_uuid     UUID,
    debtor_type               TEXT NOT NULL,
    amount_claimed            NUMERIC(14,2) NOT NULL DEFAULT 0,
    amount_approved           NUMERIC(14,2) NOT NULL DEFAULT 0,
    split_status              TEXT NOT NULL DEFAULT 'LANCADO',
    created_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMPTZ,
    created_by                TEXT,
    updated_by                TEXT,

    CONSTRAINT fk_ticket_debtor_split_ticket
        FOREIGN KEY (ticket_id) REFERENCES tickets.ticket (ticket_id) ON DELETE CASCADE,

    CONSTRAINT fk_ticket_debtor_split_brand_revenue
        FOREIGN KEY (brand_revenue_id) REFERENCES organization.brand_revenue (brand_revenue_id) ON DELETE SET NULL,

    CONSTRAINT fk_ticket_debtor_split_group_enterprise
        FOREIGN KEY (group_enterprise_uuid) REFERENCES organization.group_enterprise (group_enterprise_uuid) ON DELETE SET NULL,

    CONSTRAINT ck_ticket_debtor_split_debtor_type
        CHECK (debtor_type IN ('FORNECEDOR', 'FRANQUIA_ROYALTIES', 'FRANQUIA_MARKETING')),

    CONSTRAINT ck_ticket_debtor_split_amount_claimed_non_negative
        CHECK (amount_claimed >= 0),

    CONSTRAINT ck_ticket_debtor_split_amount_approved_non_negative
        CHECK (amount_approved >= 0),

    CONSTRAINT ck_ticket_debtor_split_status
        CHECK (split_status IN ('LANCADO', 'DEVIDO', 'RECUSADO', 'PAGO_ABATIDO'))
);


CREATE TABLE IF NOT EXISTS tickets.ticket_attachment (
    ticket_attachment_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id               BIGINT NOT NULL,
    attachment_type_id      INTEGER,
    attachment_path         TEXT NOT NULL,
    filename                TEXT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              TEXT,

    CONSTRAINT fk_ticket_attachment_ticket
        FOREIGN KEY (ticket_id) REFERENCES tickets.ticket (ticket_id) ON DELETE CASCADE,

    CONSTRAINT fk_ticket_attachment_type
        FOREIGN KEY (attachment_type_id) REFERENCES catalog.attachment_type (attachment_type_id) ON DELETE SET NULL,

    CONSTRAINT ck_ticket_attachment_path_not_blank
        CHECK (btrim(attachment_path) <> ''),

    CONSTRAINT ck_ticket_attachment_filename_not_blank
        CHECK (btrim(filename) <> '')
);


CREATE TABLE IF NOT EXISTS tickets.ticket_history (
    ticket_history_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id            BIGINT NOT NULL,
    action               TEXT NOT NULL,
    description          TEXT NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by           TEXT,

    CONSTRAINT fk_ticket_history_ticket
        FOREIGN KEY (ticket_id) REFERENCES tickets.ticket (ticket_id) ON DELETE CASCADE,

    CONSTRAINT ck_ticket_history_action_not_blank
        CHECK (btrim(action) <> ''),

    CONSTRAINT ck_ticket_history_description_not_blank
        CHECK (btrim(description) <> '')
);


-- ============================================================
-- SCHEMA: royalties
-- ============================================================
CREATE TABLE IF NOT EXISTS royalties.royalty_statement (
    royalty_statement_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_uuid                UUID NOT NULL,
    collection_id             INTEGER NOT NULL,
    group_enterprise_uuid     UUID NOT NULL,
    brand_revenue_id          INTEGER NOT NULL,
    statement_number          TEXT NOT NULL,
    base_calculation_amount   NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_royalties_amount    NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_marketing_amount    NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_deduction_amount    NUMERIC(14,2) NOT NULL DEFAULT 0,
    net_amount_due            NUMERIC(14,2) NOT NULL DEFAULT 0,
    statement_status          TEXT NOT NULL DEFAULT 'PREVISTO',
    due_date                  DATE NOT NULL,
    payment_date              DATE,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMPTZ,
    created_by                TEXT,
    updated_by                TEXT,

    CONSTRAINT fk_royalty_statement_collection
        FOREIGN KEY (collection_id) REFERENCES catalog.collection (collection_id) ON DELETE RESTRICT,

    CONSTRAINT fk_royalty_statement_group_enterprise
        FOREIGN KEY (group_enterprise_uuid) REFERENCES organization.group_enterprise (group_enterprise_uuid) ON DELETE RESTRICT,

    CONSTRAINT fk_royalty_statement_brand_revenue
        FOREIGN KEY (brand_revenue_id) REFERENCES organization.brand_revenue (brand_revenue_id) ON DELETE RESTRICT,

    CONSTRAINT uq_royalty_statement_scope
        UNIQUE (store_uuid, collection_id, group_enterprise_uuid, brand_revenue_id, statement_number),

    CONSTRAINT ck_royalty_statement_number_not_blank
        CHECK (btrim(statement_number) <> ''),

    CONSTRAINT ck_royalty_statement_base_calculation_amount_non_negative
        CHECK (base_calculation_amount >= 0),

    CONSTRAINT ck_royalty_statement_total_royalties_amount_non_negative
        CHECK (total_royalties_amount >= 0),

    CONSTRAINT ck_royalty_statement_total_marketing_amount_non_negative
        CHECK (total_marketing_amount >= 0),

    CONSTRAINT ck_royalty_statement_total_deduction_amount_non_negative
        CHECK (total_deduction_amount >= 0),

    CONSTRAINT ck_royalty_statement_net_amount_due_non_negative
        CHECK (net_amount_due >= 0),

    CONSTRAINT ck_royalty_statement_status
        CHECK (statement_status IN ('PREVISTO', 'DEVIDO', 'FATURADO', 'PAGO', 'CANCELADO')),

    CONSTRAINT ck_royalty_statement_payment_date
        CHECK (payment_date IS NULL OR payment_date >= due_date)
);


CREATE TABLE IF NOT EXISTS royalties.royalty_statement_detail (
    royalty_statement_detail_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    royalty_statement_id           BIGINT NOT NULL,
    purchase_id                    BIGINT NOT NULL,
    calculated_royalties_amount    NUMERIC(14,2) NOT NULL DEFAULT 0,
    calculated_marketing_amount    NUMERIC(14,2) NOT NULL DEFAULT 0,
    created_at                     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                     TIMESTAMPTZ,
    created_by                     TEXT,
    updated_by                     TEXT,

    CONSTRAINT fk_royalty_statement_detail_statement
        FOREIGN KEY (royalty_statement_id) REFERENCES royalties.royalty_statement (royalty_statement_id) ON DELETE CASCADE,

    CONSTRAINT fk_royalty_statement_detail_purchase
        FOREIGN KEY (purchase_id) REFERENCES purchases.purchase (purchase_id) ON DELETE RESTRICT,

    CONSTRAINT uq_royalty_statement_detail_statement_purchase
        UNIQUE (royalty_statement_id, purchase_id),

    CONSTRAINT ck_royalty_statement_detail_calculated_royalties_non_negative
        CHECK (calculated_royalties_amount >= 0),

    CONSTRAINT ck_royalty_statement_detail_calculated_marketing_non_negative
        CHECK (calculated_marketing_amount >= 0)
);


CREATE TABLE IF NOT EXISTS royalties.royalty_statement_attachment (
    royalty_statement_attachment_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    royalty_statement_id               BIGINT NOT NULL,
    attachment_type_id                 INTEGER,
    attachment_path                    TEXT NOT NULL,
    filename                           TEXT NOT NULL,
    created_at                         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by                         TEXT,

    CONSTRAINT fk_royalty_statement_attachment_statement
        FOREIGN KEY (royalty_statement_id) REFERENCES royalties.royalty_statement (royalty_statement_id) ON DELETE CASCADE,

    CONSTRAINT fk_royalty_statement_attachment_type
        FOREIGN KEY (attachment_type_id) REFERENCES catalog.attachment_type (attachment_type_id) ON DELETE SET NULL,

    CONSTRAINT ck_royalty_statement_attachment_path_not_blank
        CHECK (btrim(attachment_path) <> ''),

    CONSTRAINT ck_royalty_statement_attachment_filename_not_blank
        CHECK (btrim(filename) <> '')
);


-- ============================================================
-- SCHEMA: audit
-- ============================================================
CREATE TABLE IF NOT EXISTS audit.retention_policy (
    retention_policy_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description            TEXT NOT NULL,
    is_permanent           BOOLEAN NOT NULL DEFAULT FALSE,
    retention_days         INTEGER,

    CONSTRAINT uq_retention_policy_description
        UNIQUE (description),

    CONSTRAINT ck_retention_policy_description_not_blank
        CHECK (btrim(description) <> ''),

    CONSTRAINT ck_retention_policy_days
        CHECK (
            (is_permanent = TRUE AND retention_days IS NULL)
            OR
            (is_permanent = FALSE AND retention_days IS NOT NULL AND retention_days >= 0)
        )
);


CREATE TABLE IF NOT EXISTS audit.retention_rule (
    retention_rule_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_name            TEXT NOT NULL,
    table_name             TEXT NOT NULL,
    retention_policy_id    INTEGER NOT NULL,

    CONSTRAINT fk_retention_rule_policy
        FOREIGN KEY (retention_policy_id) REFERENCES audit.retention_policy (retention_policy_id),

    CONSTRAINT uq_retention_rule_schema_table
        UNIQUE (schema_name, table_name),

    CONSTRAINT ck_retention_rule_schema_name_not_blank
        CHECK (btrim(schema_name) <> ''),

    CONSTRAINT ck_retention_rule_table_name_not_blank
        CHECK (btrim(table_name) <> '')
);


CREATE TABLE IF NOT EXISTS audit.logs (
    log_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_schema          TEXT NOT NULL,
    log_table           TEXT NOT NULL,
    log_record_id       TEXT NOT NULL,
    log_action          TEXT NOT NULL,
    log_user            TEXT,
    log_ip              TEXT,
    log_before_data     JSONB,
    log_after_data      JSONB,
    log_created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_logs_schema_not_blank
        CHECK (btrim(log_schema) <> ''),

    CONSTRAINT ck_logs_table_not_blank
        CHECK (btrim(log_table) <> ''),

    CONSTRAINT ck_logs_record_id_not_blank
        CHECK (btrim(log_record_id) <> ''),

    CONSTRAINT ck_logs_action
        CHECK (log_action IN ('INSERCAO', 'ATUALIZACAO', 'EXCLUSAO'))
);


CREATE TABLE IF NOT EXISTS audit.login_logs (
    log_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_user_id         TEXT,
    log_email           TEXT,
    log_name            TEXT,
    log_tenant_id       TEXT,
    log_action          TEXT NOT NULL,
    log_origin          TEXT NOT NULL,
    log_ip              TEXT,
    log_user_agent      TEXT,
    log_details         JSONB,
    log_created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_login_logs_action
        CHECK (log_action IN ('ENTRADA', 'SAIDA', 'FALHA_AUTENTICACAO')),

    CONSTRAINT ck_login_logs_origin
        CHECK (log_origin IN ('LOCAL', 'SSO', 'GOV_BR', 'APPLE', 'GOOGLE', 'CHAVE_API'))
);


CREATE TABLE IF NOT EXISTS audit.api_logs (
    log_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_method           TEXT NOT NULL,
    log_endpoint         TEXT NOT NULL,
    log_status           SMALLINT NOT NULL,
    log_client           TEXT,
    log_user             TEXT,
    log_ip               TEXT,
    log_request_body     JSONB,
    log_duration_ms      INTEGER,
    log_created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_api_logs_method
        CHECK (log_method IN ('POST', 'PUT', 'PATCH', 'DELETE')),

    CONSTRAINT ck_api_logs_endpoint_not_blank
        CHECK (btrim(log_endpoint) <> ''),

    CONSTRAINT ck_api_logs_duration_non_negative
        CHECK (log_duration_ms IS NULL OR log_duration_ms >= 0)
);


INSERT INTO audit.retention_policy (description, is_permanent, retention_days) VALUES
    ('Permanente', TRUE, NULL),
    ('90 dias', FALSE, 90),
    ('365 dias', FALSE, 365)
ON CONFLICT (description) DO NOTHING;


-- ============================================================
-- ÍNDICES OPERACIONAIS
-- ============================================================
CREATE INDEX IF NOT EXISTS ix_brand_revenue_brand_id
    ON organization.brand_revenue (brand_id);

CREATE INDEX IF NOT EXISTS ix_group_enterprise_brand_id
    ON organization.group_enterprise (brand_id);

CREATE INDEX IF NOT EXISTS ix_group_enterprise_brand_revenue_id
    ON organization.group_enterprise (brand_revenue_id);

CREATE INDEX IF NOT EXISTS ix_tenant_store_store_uuid
    ON organization.tenant_store (store_uuid);

CREATE INDEX IF NOT EXISTS ix_tenant_store_partner_uuid
    ON organization.tenant_store (partner_uuid);

CREATE INDEX IF NOT EXISTS ix_collection_brand_id
    ON catalog.collection (brand_id);

CREATE INDEX IF NOT EXISTS ix_product_type_product_group_id
    ON catalog.product_type (product_group_id);

CREATE INDEX IF NOT EXISTS ix_product_brand_id
    ON catalog.product (brand_id);

CREATE INDEX IF NOT EXISTS ix_product_product_group_id
    ON catalog.product (product_group_id);

CREATE INDEX IF NOT EXISTS ix_product_product_type_id
    ON catalog.product (product_type_id);

CREATE INDEX IF NOT EXISTS ix_product_product_grade_id
    ON catalog.product (product_grade_id);

CREATE INDEX IF NOT EXISTS ix_order_store_uuid
    ON orders."order" (store_uuid);

CREATE INDEX IF NOT EXISTS ix_order_supplier_id
    ON orders."order" (supplier_id);

CREATE INDEX IF NOT EXISTS ix_order_collection_id
    ON orders."order" (collection_id);

CREATE INDEX IF NOT EXISTS ix_order_status
    ON orders."order" (status);

CREATE INDEX IF NOT EXISTS ix_order_product_product_id
    ON orders.order_product (product_id);

CREATE INDEX IF NOT EXISTS ix_purchase_store_uuid
    ON purchases.purchase (store_uuid);

CREATE INDEX IF NOT EXISTS ix_purchase_supplier_id
    ON purchases.purchase (supplier_id);

CREATE INDEX IF NOT EXISTS ix_purchase_collection_id
    ON purchases.purchase (collection_id);

CREATE INDEX IF NOT EXISTS ix_purchase_status
    ON purchases.purchase (purchase_status);

CREATE INDEX IF NOT EXISTS ix_purchase_product_product_id
    ON purchases.purchase_product (product_id);

CREATE INDEX IF NOT EXISTS ix_ticket_store_uuid
    ON tickets.ticket (store_uuid);

CREATE INDEX IF NOT EXISTS ix_ticket_purchase_id
    ON tickets.ticket (purchase_id);

CREATE INDEX IF NOT EXISTS ix_ticket_order_id
    ON tickets.ticket (order_id);

CREATE INDEX IF NOT EXISTS ix_ticket_status
    ON tickets.ticket (ticket_status);

CREATE INDEX IF NOT EXISTS ix_ticket_debtor_split_brand_revenue_id
    ON tickets.ticket_debtor_split (brand_revenue_id);

CREATE INDEX IF NOT EXISTS ix_ticket_debtor_split_group_enterprise_uuid
    ON tickets.ticket_debtor_split (group_enterprise_uuid);

CREATE INDEX IF NOT EXISTS ix_ticket_debtor_split_debtor_type
    ON tickets.ticket_debtor_split (debtor_type);

CREATE INDEX IF NOT EXISTS ix_ticket_attachment_type_id
    ON tickets.ticket_attachment (attachment_type_id);

CREATE INDEX IF NOT EXISTS ix_royalty_statement_store_uuid
    ON royalties.royalty_statement (store_uuid);

CREATE INDEX IF NOT EXISTS ix_royalty_statement_collection_id
    ON royalties.royalty_statement (collection_id);

CREATE INDEX IF NOT EXISTS ix_royalty_statement_group_enterprise_uuid
    ON royalties.royalty_statement (group_enterprise_uuid);

CREATE INDEX IF NOT EXISTS ix_royalty_statement_brand_revenue_id
    ON royalties.royalty_statement (brand_revenue_id);

CREATE INDEX IF NOT EXISTS ix_royalty_statement_status
    ON royalties.royalty_statement (statement_status);

CREATE INDEX IF NOT EXISTS ix_royalty_statement_due_date
    ON royalties.royalty_statement (due_date);

CREATE INDEX IF NOT EXISTS ix_royalty_statement_detail_purchase_id
    ON royalties.royalty_statement_detail (purchase_id);

CREATE INDEX IF NOT EXISTS ix_royalty_statement_attachment_type_id
    ON royalties.royalty_statement_attachment (attachment_type_id);

CREATE INDEX IF NOT EXISTS ix_retention_rule_retention_policy_id
    ON audit.retention_rule (retention_policy_id);

CREATE INDEX IF NOT EXISTS ix_logs_schema_table_record
    ON audit.logs (log_schema, log_table, log_record_id);

CREATE INDEX IF NOT EXISTS ix_logs_created_at
    ON audit.logs (log_created_at);

CREATE INDEX IF NOT EXISTS ix_login_logs_created_at
    ON audit.login_logs (log_created_at);

CREATE INDEX IF NOT EXISTS ix_login_logs_user_id
    ON audit.login_logs (log_user_id);

CREATE INDEX IF NOT EXISTS ix_api_logs_created_at
    ON audit.api_logs (log_created_at);

CREATE INDEX IF NOT EXISTS ix_api_logs_endpoint
    ON audit.api_logs (log_endpoint);


-- ============================================================
-- COMENTÁRIOS ESTRUTURAIS
-- ============================================================
COMMENT ON TABLE organization.tenant_store IS
'Tabela ponte entre tenant, loja e parceiro comercial que opera a conta.';

COMMENT ON TABLE catalog.product IS
'Cadastro mestre do produto comercial da marca, identificado por SKU único por brand.';

COMMENT ON TABLE orders."order" IS
'Pedido comercial da loja, com totais consolidados e anexos de apoio em JSONB.';

COMMENT ON COLUMN orders."order".order_attachments_json IS
'Lista de anexos do pedido gerida pela aplicação. Estrutura interna controlada.';

COMMENT ON TABLE orders.order_product IS
'Itens do pedido com precificação de sell-in e sell-out e quantidade consolidada.';

COMMENT ON TABLE purchases.purchase IS
'Nota fiscal de compra / recebimento da loja, base para auditoria e royalties.';

COMMENT ON COLUMN purchases.purchase.purchase_attachments_json IS
'Lista de anexos da compra/NF gerida pela aplicação. Estrutura interna controlada.';

COMMENT ON TABLE tickets.ticket IS
'Contestação operacional/financeira vinculável a compra e/ou pedido.';

COMMENT ON TABLE tickets.ticket_debtor_split IS
'Rateio financeiro do ticket entre possíveis devedores e naturezas de abatimento.';

COMMENT ON TABLE royalties.royalty_statement IS
'Folha de cobrança/conciliação de royalties e marketing por loja, coleção e faturamento.';

COMMENT ON TABLE audit.logs IS
'Trilha genérica de alterações estruturais da aplicação por schema/tabela/registro.';
