-- Migration — tenant_catalogo (redesenho 4→7 tabelas)
-- Aplicar em PROD (homologação): tenant_catalogo estava sem uso (0 referência no código) e vazio.
-- Contrato: docs/projects/axys-easy/contracts/catalogo/TENANT_CATALOGO_PROPOSTA.md
-- Idempotente: DROP CASCADE + CREATE do desenho novo. Recria vazio, RASCUNHO por default nas edições.

DROP SCHEMA IF EXISTS tenant_catalogo CASCADE;

-- ============================================================
-- SCHEMA: tenant_catalogo  (biblioteca técnica própria do tenant)
-- Contrato/proposta: docs/projects/axys-easy/contracts/catalogo/TENANT_CATALOGO_PROPOSTA.md (validado 2026-08-17).
-- Espelha a FORMA do catalogo, ENXUTO e isolado por tenant_uuid (raiz). 7 tabelas:
--   fontes · edicoes · insumos · insumos_preco · composicoes · composicoes_itens · composicoes_custo.
-- SEM: CTC, path/R2, grupos/subgrupos, BDI, conferência, encargos itemizados, cadernos, equivalências,
--      tabela de histórico/auditoria. Único histórico = série de PREÇO por edição.
-- FK física SÓ p/ o lookup GLOBAL catalogo.insumos_tipo. Unidade = texto livre (sem FK unidades).
-- UF vive no INSUMO (ins_uf); preço por (insumo, edição). L.S. mínima só p/ MO (edicoes.edi_ls_horista,
--   trunc SINAPI). Composição UF-agnóstica: aceita filho de qualquer UF; custo SEMPRE calculado (Σ) e
--   armazenado (cache) — 1 por (cmp, edição). Filho GLOBAL precificado por composicoes_itens.ci_uf.
-- Import por (fonte, edição, UF) é IDEMPOTENTE (put/update = delete+insert do escopo).
-- RLS: colunas *_tenant_uuid já presentes; políticas ADIADAS (habilitar ao liberar tenants).
-- ============================================================
CREATE SCHEMA IF NOT EXISTS tenant_catalogo;

GRANT USAGE ON SCHEMA tenant_catalogo TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA tenant_catalogo
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA tenant_catalogo
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";

-- ── 1) FONTES próprias/externas do tenant ──
CREATE TABLE IF NOT EXISTS tenant_catalogo.fontes (
    fte_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fte_tenant_uuid    UUID    NOT NULL,                  -- RAIZ de isolamento. [VALIDAR] sem FK física.
    fte_codigo         TEXT    NOT NULL,
    fte_nome           TEXT    NOT NULL,
    fte_tipo           TEXT    NOT NULL DEFAULT 'PROPRIA', -- PROPRIA | EXTERNA
    fte_ativa          BOOLEAN NOT NULL DEFAULT TRUE,
    fte_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fte_atualizado_em  TIMESTAMPTZ,
    fte_criado_por     TEXT,
    fte_atualizado_por TEXT,

    CONSTRAINT uq_tcf_tenant_codigo UNIQUE (fte_tenant_uuid, fte_codigo),
    CONSTRAINT ck_tcf_tipo   CHECK (fte_tipo IN ('PROPRIA', 'EXTERNA')),
    CONSTRAINT ck_tcf_codigo CHECK (btrim(fte_codigo) <> '')
);

CREATE INDEX ix_tcf_tenant ON tenant_catalogo.fontes (fte_tenant_uuid, fte_ativa);

-- ── 2) EDIÇÕES da fonte (sem UF padrão, sem pipeline; L.S. da edição p/ MO) ──
CREATE TABLE IF NOT EXISTS tenant_catalogo.edicoes (
    edi_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edi_tenant_uuid    UUID    NOT NULL,                  -- RAIZ de isolamento. [VALIDAR] sem FK física.
    edi_fte_id         INTEGER NOT NULL,
    edi_referencia     DATE    NOT NULL,                  -- data efetiva da tabela de preços
    edi_codigo_versao  TEXT,                              -- número/rótulo livre ("184", "Tabela Jan/26")
    edi_ls_horista     NUMERIC(8,4),                      -- L.S. p/ MO (NULL = MO fica pelado)
    edi_situacao       TEXT    NOT NULL DEFAULT 'RASCUNHO', -- RASCUNHO | PUBLICADA | ARQUIVADA
    edi_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edi_atualizado_em  TIMESTAMPTZ,
    edi_criado_por     TEXT,
    edi_atualizado_por TEXT,

    CONSTRAINT fk_tce_fte
        FOREIGN KEY (edi_fte_id)
        REFERENCES tenant_catalogo.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_tce_fte_ref UNIQUE (edi_fte_id, edi_referencia),
    CONSTRAINT ck_tce_situacao CHECK (edi_situacao IN ('RASCUNHO', 'PUBLICADA', 'ARQUIVADA'))
);

CREATE INDEX ix_tce_fte ON tenant_catalogo.edicoes (edi_fte_id, edi_referencia DESC);

-- ── 3) INSUMOS do tenant (UF vive aqui; ti_id → lookup GLOBAL; sem ativo) ──
CREATE TABLE IF NOT EXISTS tenant_catalogo.insumos (
    ins_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ins_tenant_uuid    UUID    NOT NULL,                  -- RAIZ de isolamento. [VALIDAR] sem FK física.
    ins_fte_id         INTEGER NOT NULL,
    ins_ti_id          INTEGER NOT NULL,                  -- classificação (MO/MAT/EQ…) — FK ao lookup GLOBAL
    ins_codigo         TEXT    NOT NULL,
    ins_descricao      TEXT    NOT NULL,
    ins_unidade        TEXT    NOT NULL,                  -- texto livre (sem FK unidades)
    ins_uf             CHAR(2) NOT NULL DEFAULT 'SP',     -- UF do insumo (o preço herda daqui)
    ins_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ins_atualizado_em  TIMESTAMPTZ,
    ins_criado_por     TEXT,
    ins_atualizado_por TEXT,

    CONSTRAINT fk_tci_fte
        FOREIGN KEY (ins_fte_id)
        REFERENCES tenant_catalogo.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_tci_ti
        FOREIGN KEY (ins_ti_id)
        REFERENCES catalogo.insumos_tipo (ti_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_tci_fte_codigo_uf UNIQUE (ins_fte_id, ins_codigo, ins_uf),
    CONSTRAINT ck_tci_codigo CHECK (btrim(ins_codigo) <> '')
);

CREATE INDEX ix_tci_tenant ON tenant_catalogo.insumos (ins_tenant_uuid, ins_codigo);

-- ── 4) PREÇO do insumo (UF herda do insumo; MO = pelado; cotação inline em JSONB) ──
CREATE TABLE IF NOT EXISTS tenant_catalogo.insumos_preco (
    pri_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pri_ins_id         INTEGER NOT NULL,
    pri_edi_id         INTEGER NOT NULL,
    pri_valor          NUMERIC(14,4),                     -- MO = PELADO (SE); demais = valor final
    pri_situacao       TEXT,                              -- 'COM PREÇO' | 'SEM PREÇO' (null = sem preço)
    pri_origem         TEXT,                              -- PROPRIA | PESQUISA | COTACAO | IMPORT
    pri_cotacoes       JSONB,                             -- [{empresa, site, telefone, email, responsavel, data, valor}]
    pri_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pri_atualizado_em  TIMESTAMPTZ,
    pri_criado_por     TEXT,
    pri_atualizado_por TEXT,

    CONSTRAINT fk_tcp_ins
        FOREIGN KEY (pri_ins_id)
        REFERENCES tenant_catalogo.insumos (ins_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_tcp_edi
        FOREIGN KEY (pri_edi_id)
        REFERENCES tenant_catalogo.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_tcp UNIQUE (pri_ins_id, pri_edi_id),    -- grão: (insumo, edição) — UF vem do insumo
    CONSTRAINT ck_tcp_situacao
        CHECK (pri_situacao IS NULL OR pri_situacao IN ('COM PREÇO', 'SEM PREÇO'))
);

CREATE INDEX ix_tcp_ins_edi ON tenant_catalogo.insumos_preco (pri_ins_id, pri_edi_id);

-- ── 5) COMPOSIÇÕES do tenant (sem situação/ativa) ──
CREATE TABLE IF NOT EXISTS tenant_catalogo.composicoes (
    cmp_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cmp_tenant_uuid    UUID    NOT NULL,                  -- RAIZ de isolamento. [VALIDAR] sem FK física.
    cmp_fte_id         INTEGER NOT NULL,
    cmp_codigo         TEXT    NOT NULL,
    cmp_descricao      TEXT    NOT NULL,
    cmp_unidade        TEXT    NOT NULL,
    cmp_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cmp_atualizado_em  TIMESTAMPTZ,
    cmp_criado_por     TEXT,
    cmp_atualizado_por TEXT,

    CONSTRAINT fk_tcc_fte
        FOREIGN KEY (cmp_fte_id)
        REFERENCES tenant_catalogo.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_tcc_fte_codigo UNIQUE (cmp_fte_id, cmp_codigo),
    CONSTRAINT ck_tcc_codigo CHECK (btrim(cmp_codigo) <> '')
);

CREATE INDEX ix_tcc_tenant ON tenant_catalogo.composicoes (cmp_tenant_uuid, cmp_codigo);

-- ── 6) ITENS da composição (ref polimórfica a.3: global OU tenant, insumo OU composição) ──
CREATE TABLE IF NOT EXISTS tenant_catalogo.composicoes_itens (
    ci_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ci_cmp_id          INTEGER NOT NULL,                  -- composição-mãe (sempre do tenant)
    ci_ref_origem      TEXT    NOT NULL,                  -- 'CATALOGO' | 'TENANT' (onde vive o filho)
    ci_ref_tipo        TEXT    NOT NULL,                  -- 'INSUMO' | 'COMPOSICAO' (o que é o filho)
    ci_ref_id          INTEGER NOT NULL,                  -- id na origem+tipo (FK polimórfica via app)
    ci_coeficiente     NUMERIC(14,10) NOT NULL,
    ci_uf              CHAR(2),                           -- UF só p/ precificar filho GLOBAL (tenant herda de ins_uf)
    ci_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ci_atualizado_em   TIMESTAMPTZ,
    ci_criado_por      TEXT,
    ci_atualizado_por  TEXT,

    CONSTRAINT fk_tcci_cmp
        FOREIGN KEY (ci_cmp_id)
        REFERENCES tenant_catalogo.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_tcci_ref_origem CHECK (ci_ref_origem IN ('CATALOGO', 'TENANT')),
    CONSTRAINT ck_tcci_ref_tipo   CHECK (ci_ref_tipo IN ('INSUMO', 'COMPOSICAO'))
);

CREATE INDEX ix_tcci_cmp ON tenant_catalogo.composicoes_itens (ci_cmp_id);

-- ── 7) CUSTO da composição (cache; SEMPRE calculado; UF-agnóstico → 1 por (cmp, edição)) ──
CREATE TABLE IF NOT EXISTS tenant_catalogo.composicoes_custo (
    cc_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cc_cmp_id          INTEGER NOT NULL,
    cc_edi_id          INTEGER NOT NULL,
    cc_custo           NUMERIC(14,4),
    cc_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cc_atualizado_em   TIMESTAMPTZ,
    cc_criado_por      TEXT,
    cc_atualizado_por  TEXT,

    CONSTRAINT fk_tccu_cmp
        FOREIGN KEY (cc_cmp_id)
        REFERENCES tenant_catalogo.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_tccu_edi
        FOREIGN KEY (cc_edi_id)
        REFERENCES tenant_catalogo.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_tccu UNIQUE (cc_cmp_id, cc_edi_id)
);

CREATE INDEX ix_tccu_cmp_edi ON tenant_catalogo.composicoes_custo (cc_cmp_id, cc_edi_id);

