-- tenant_catalogo.unidades — vocabulário de unidades PRÓPRIAS do tenant (código + descrição).
-- A descrição importa no descritivo do orçamento. O dropdown de unidade = catalogo.unidades (global)
-- ∪ tenant_catalogo.unidades (tenant). insumos/composições continuam guardando o CÓDIGO (texto livre).
-- Mínima (sem ativo): vocabulário get-or-create; não orfaniza (o código fica no insumo). Idempotente.
-- Contrato: docs/projects/axys-easy/contracts/catalogo/TENANT_CATALOGO_PROPOSTA.md

CREATE TABLE IF NOT EXISTS tenant_catalogo.unidades (
    un_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un_tenant_uuid    UUID    NOT NULL,                  -- RAIZ de isolamento. [VALIDAR] sem FK física.
    un_codigo         TEXT    NOT NULL,                  -- VG, M3XKM…
    un_descricao      TEXT,                              -- importa no descritivo do orçamento
    un_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    un_atualizado_em  TIMESTAMPTZ,
    un_criado_por     TEXT,
    un_atualizado_por TEXT,

    CONSTRAINT uq_tcu_tenant_codigo UNIQUE (un_tenant_uuid, un_codigo),
    CONSTRAINT ck_tcu_codigo CHECK (btrim(un_codigo) <> '')
);

CREATE INDEX IF NOT EXISTS ix_tcu_tenant ON tenant_catalogo.unidades (un_tenant_uuid, un_codigo);
