-- ============================================================
-- AxysEasy — Schema SQL
-- Banco: PostgreSQL 14+
-- Schemas: cpu · orca · audit
--
-- cpu   : catálogo de fontes de preços, insumos, preços por
--         edição/UF/modalidade, composições de preço versionadas
--         e hierarquia de grupos/subgrupos.
-- orca  : obras orçamentárias, BDI, serviços em estrutura
--         hierárquica, motor paramétrico e cronograma
--         físico-financeiro.
-- audit : trilha de auditoria — quem/quando/o quê/antes/depois.
--
-- Decisões de arquitetura
-- ───────────────────────
-- VERSIONAMENTO DE CATÁLOGO
--   Cada importação cria novos registros vinculados à edição
--   (edi_id). Não há UPDATE/DELETE em dados históricos.
--   Re-importar a mesma edi_id é idempotente dentro da edição.
--   UNIQUE em composições: (cmp_fte_id, cmp_codigo, cmp_edi_id)
--
-- UF / MODALIDADE
--   precos_insumo e custos_composicao armazenam uma linha por
--   (insumo/composição, edição, uf, modalidade).
--   SINAPI: todas 27 UFs importadas por edição.
--   Estimativa: ~262 k linhas de preço de insumo por import;
--   ~560 k de custo de composição. PostgreSQL suporta com folga.
--   modalidade: 'SD' = sem desoneração | 'CD' = com desoneração
--   'SE' (sem encargos) não é armazenado — apenas consulta direta.
--
-- TENANCY
--   Tabelas cpu.*: catálogo compartilhado — sem tenant_uuid.
--   Tabelas orca.*: dados do tenant — obr_tenant_uuid em todas.
--   Obras são imutáveis após obr_status = 'ARQUIVADO'.
--   srv_cmp_id referencia a composição na edição exata da obra
--   (obr_edi_id); snapshot garantido pelo versionamento.
--
-- GRUPOS / SUBGRUPOS
--   cpu.grupos:    nível 1 (CDHU: código 'XX'; SINAPI: não usa)
--   cpu.subgrupos: nível 2 — sub_grp_id NULLABLE para SINAPI
--     (SINAPI usa sub_grp_id = NULL; seus "grupos" são subgrupos)
--
-- TIPO DE INSUMO
--   ins_tipo_sinapi: classificação exata da fonte (SINAPI verbatim
--     ou mapeado de outras fontes). Fidelidade ao dado original.
--   ins_ti_id: FK para cpu.tipos_insumo
--     (MO / EQUIP_AQ / EQUIP_LOC / MAT / SERV / ESP)
--     agrupamento para histogramas e relatórios.
--   Mapeamento padrão SINAPI → tipos_insumo:
--     MATERIAL                → MAT
--     MAO DE OBRA             → MO
--     ENCARGOS COMPLEMENTARES → MO
--     EQUIPAMENTO (AQUISIÇÃO) → EQUIP_AQ
--     EQUIPAMENTO (LOCAÇÃO)   → EQUIP_LOC
--     SERVIÇOS                → SERV
--     ESPECIAIS               → ESP
--
-- PADRÃO DE NOMENCLATURA
--   Prefixo de coluna = abreviatura da tabela
--   PKs: INTEGER GENERATED BY DEFAULT AS IDENTITY
--   Timestamps: TIMESTAMPTZ; datas: DATE
--   Coeficientes: NUMERIC(14,6); preços/valores: NUMERIC(14,4)
--   Audit trail: _criado_em, _atualizado_em, _criado_por, _atualizado_por
-- ============================================================


-- ============================================================
-- SCHEMA: cpu
-- ============================================================

CREATE SCHEMA IF NOT EXISTS cpu;

GRANT USAGE ON SCHEMA cpu  TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA cpu
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA cpu
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";


-- ============================================================
-- TABELA: cpu.tipos_insumo
-- Grupos de insumos para histogramas e relatórios.
-- Seed inicial — ver db/seed.sql.
-- ============================================================
CREATE TABLE IF NOT EXISTS cpu.tipos_insumo (
    ti_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ti_codigo          TEXT    NOT NULL,   -- MO | EQUIP_AQ | EQUIP_LOC | MAT | SERV | ESP
    ti_nome            TEXT    NOT NULL,
    ti_ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    ti_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ti_atualizado_em   TIMESTAMPTZ,
    ti_criado_por      TEXT,
    ti_atualizado_por  TEXT,

    CONSTRAINT uq_tipos_insumo_codigo
        UNIQUE (ti_codigo),

    CONSTRAINT ck_tipos_insumo_codigo_vazio
        CHECK (btrim(ti_codigo) <> ''),

    CONSTRAINT ck_tipos_insumo_nome_vazio
        CHECK (btrim(ti_nome) <> '')
);


-- ============================================================
-- TABELA: cpu.fontes
-- Catálogo das fontes de preços (SINAPI, CDHU, FDE, AXYS...).
--
-- fte_ordem_edicao:
--   'DATA'   — edição mais recente = maior edi_mes_ref
--   'VERSAO' — edição mais recente = maior edi_codigo_versao
--
-- Fonte 'AXYS': composições próprias do tenant — sem edição
--   mensal; preço informado direto, sem linha em precos_insumo.
-- ============================================================
CREATE TABLE IF NOT EXISTS cpu.fontes (
    fte_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fte_codigo         TEXT    NOT NULL,   -- 'SINAPI' | 'CDHU' | 'FDE' | 'AXYS'
    fte_nome           TEXT    NOT NULL,
    fte_ordem_edicao   TEXT    NOT NULL DEFAULT 'DATA',
    fte_ativa          BOOLEAN NOT NULL DEFAULT TRUE,
    fte_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fte_atualizado_em  TIMESTAMPTZ,
    fte_criado_por     TEXT,
    fte_atualizado_por TEXT,

    CONSTRAINT uq_fontes_codigo
        UNIQUE (fte_codigo),

    CONSTRAINT ck_fontes_codigo_vazio
        CHECK (btrim(fte_codigo) <> ''),

    CONSTRAINT ck_fontes_nome_vazio
        CHECK (btrim(fte_nome) <> ''),

    CONSTRAINT ck_fontes_ordem_edicao
        CHECK (fte_ordem_edicao IN ('DATA', 'VERSÃO'))
);

CREATE INDEX ix_fontes_ativa
    ON cpu.fontes (fte_ativa, fte_codigo);


-- ============================================================
-- TABELA: cpu.edicoes
-- Cada publicação de uma fonte de preços.
--
-- edi_mes_ref:       1º dia do mês de referência (DATE).
-- edi_codigo_versao: para fontes com VERSAO (ex: CDHU '201').
-- edi_uf_padrao:     UF exibida por padrão na consulta.
--   SINAPI: 'SP' — todas 27 UFs estão importadas na edição.
--   CDHU:   'SP' — fonte estadual, apenas SP.
-- ============================================================
CREATE TABLE IF NOT EXISTS cpu.edicoes (
    edi_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edi_fte_id         INTEGER NOT NULL,
    edi_mes_ref        DATE    NOT NULL,
    edi_codigo_versao  TEXT,
    edi_uf_padrao      CHAR(2) NOT NULL DEFAULT 'SP',
    edi_ativa          BOOLEAN NOT NULL DEFAULT TRUE,
    edi_importado_em   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edi_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edi_atualizado_em  TIMESTAMPTZ,
    edi_criado_por     TEXT,
    edi_atualizado_por TEXT,

    CONSTRAINT fk_edicoes_fte
        FOREIGN KEY (edi_fte_id)
        REFERENCES cpu.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_edicoes_fte_mes
        UNIQUE (edi_fte_id, edi_mes_ref),

    CONSTRAINT ck_edicoes_primeiro_do_mes
        CHECK (EXTRACT(DAY FROM edi_mes_ref) = 1),

    CONSTRAINT ck_edicoes_codigo_versao_vazio
        CHECK (edi_codigo_versao IS NULL OR btrim(edi_codigo_versao) <> '')
);

CREATE INDEX ix_edicoes_fte_mes
    ON cpu.edicoes (edi_fte_id, edi_mes_ref DESC);

CREATE INDEX ix_edicoes_ativas
    ON cpu.edicoes (edi_fte_id, edi_ativa)
    WHERE edi_ativa = TRUE;


-- ============================================================
-- TABELA: cpu.grupos
-- Nível 1 da hierarquia de classificação.
--   CDHU: código numérico 'XX' (ex: '01', '02')
--   SINAPI: não usa — subgrupos têm sub_grp_id = NULL
-- ============================================================
CREATE TABLE IF NOT EXISTS cpu.grupos (
    grp_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grp_fte_id         INTEGER NOT NULL,
    grp_codigo         TEXT    NOT NULL,
    grp_descricao      TEXT    NOT NULL,
    grp_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    grp_atualizado_em  TIMESTAMPTZ,
    grp_criado_por     TEXT,
    grp_atualizado_por TEXT,

    CONSTRAINT fk_grupos_fte
        FOREIGN KEY (grp_fte_id)
        REFERENCES cpu.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_grupos_fte_codigo
        UNIQUE (grp_fte_id, grp_codigo),

    CONSTRAINT ck_grupos_codigo_vazio
        CHECK (btrim(grp_codigo) <> '')
);

CREATE INDEX ix_grupos_fte
    ON cpu.grupos (grp_fte_id);


-- ============================================================
-- TABELA: cpu.subgrupos
-- Nível 2 da hierarquia.
--   CDHU: código 'XX.XX', FK sub_grp_id preenchida
--   SINAPI: nome do grupo (ex: 'Acessibilidade'), sub_grp_id NULL
-- ============================================================
CREATE TABLE IF NOT EXISTS cpu.subgrupos (
    sub_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_fte_id         INTEGER NOT NULL,
    sub_grp_id         INTEGER,                -- NULL para SINAPI
    sub_codigo         TEXT    NOT NULL,
    sub_descricao      TEXT    NOT NULL,
    sub_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sub_atualizado_em  TIMESTAMPTZ,
    sub_criado_por     TEXT,
    sub_atualizado_por TEXT,

    CONSTRAINT fk_subgrupos_fte
        FOREIGN KEY (sub_fte_id)
        REFERENCES cpu.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_subgrupos_grp
        FOREIGN KEY (sub_grp_id)
        REFERENCES cpu.grupos (grp_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_subgrupos_fte_codigo
        UNIQUE (sub_fte_id, sub_codigo),

    CONSTRAINT ck_subgrupos_codigo_vazio
        CHECK (btrim(sub_codigo) <> '')
);

CREATE INDEX ix_subgrupos_fte
    ON cpu.subgrupos (sub_fte_id);

CREATE INDEX ix_subgrupos_grp
    ON cpu.subgrupos (sub_grp_id)
    WHERE sub_grp_id IS NOT NULL;


-- ============================================================
-- TABELA: cpu.insumos
-- Identidade dos insumos — o que o insumo É, sem preço.
--
-- ins_tipo_sinapi: classificação exata da fonte.
--   SINAPI verbatim: 'MATERIAL', 'MAO DE OBRA', etc.
--   Outras fontes: mapeado para o vocabulário SINAPI no parser.
-- ins_ti_id: FK para tipos_insumo — agrupamento histograma.
-- ins_ativo: false quando ausente na edição mais recente da
--   fonte. Não exclui o registro — preserva histórico.
-- ============================================================
CREATE TABLE IF NOT EXISTS cpu.insumos (
    ins_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ins_fte_id         INTEGER NOT NULL,
    ins_ti_id          INTEGER,
    ins_codigo         TEXT    NOT NULL,
    ins_descricao      TEXT    NOT NULL,
    ins_unidade        TEXT    NOT NULL,
    ins_tipo_sinapi    TEXT,
    ins_ativo          BOOLEAN NOT NULL DEFAULT TRUE,
    ins_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ins_atualizado_em  TIMESTAMPTZ,
    ins_criado_por     TEXT,
    ins_atualizado_por TEXT,

    CONSTRAINT fk_insumos_fte
        FOREIGN KEY (ins_fte_id)
        REFERENCES cpu.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_insumos_ti
        FOREIGN KEY (ins_ti_id)
        REFERENCES cpu.tipos_insumo (ti_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_insumos_fte_codigo
        UNIQUE (ins_fte_id, ins_codigo),

    CONSTRAINT ck_insumos_codigo_vazio
        CHECK (btrim(ins_codigo) <> ''),

    CONSTRAINT ck_insumos_unidade_vazia
        CHECK (btrim(ins_unidade) <> ''),

    CONSTRAINT ck_insumos_tipo_sinapi
        CHECK (ins_tipo_sinapi IS NULL OR ins_tipo_sinapi IN (
            'MATERIAL',
            'MAO DE OBRA',
            'ENCARGOS COMPLEMENTARES',
            'EQUIPAMENTO (AQUISIÇÃO)',
            'EQUIPAMENTO (LOCAÇÃO)',
            'SERVIÇOS',
            'ESPECIAIS'
        ))
);

CREATE INDEX ix_insumos_fte_ativo
    ON cpu.insumos (ins_fte_id, ins_ativo, ins_codigo);

CREATE INDEX ix_insumos_ti
    ON cpu.insumos (ins_ti_id)
    WHERE ins_ti_id IS NOT NULL;

CREATE INDEX ix_insumos_tipo_sinapi
    ON cpu.insumos (ins_tipo_sinapi)
    WHERE ins_tipo_sinapi IS NOT NULL;


-- ============================================================
-- TABELA: cpu.precos_insumo
-- Preços dos insumos por edição / UF / modalidade.
-- Cada linha é imutável. Re-import da mesma
-- (insumo, edição, uf, modalidade) é upsert idempotente.
--
-- pri_uf:         UF da coleta ('SP', 'RJ', ...)
-- pri_modalidade: 'SD' (sem desoneração) | 'CD' (com)
-- pri_origem:     'C' = coletado | 'CR' = coef. representativo
-- ============================================================
CREATE TABLE IF NOT EXISTS cpu.precos_insumo (
    pri_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pri_ins_id         INTEGER       NOT NULL,
    pri_edi_id         INTEGER       NOT NULL,
    pri_uf             CHAR(2)       NOT NULL DEFAULT 'SP',
    pri_modalidade     CHAR(2)       NOT NULL DEFAULT 'SD',
    pri_valor          NUMERIC(14,4) NOT NULL,
    pri_origem         CHAR(2),
    pri_criado_em      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pri_atualizado_em  TIMESTAMPTZ,
    pri_criado_por     TEXT,
    pri_atualizado_por TEXT,

    CONSTRAINT fk_precos_ins
        FOREIGN KEY (pri_ins_id)
        REFERENCES cpu.insumos (ins_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_precos_edi
        FOREIGN KEY (pri_edi_id)
        REFERENCES cpu.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_precos_ins_edi_uf_mod
        UNIQUE (pri_ins_id, pri_edi_id, pri_uf, pri_modalidade),

    CONSTRAINT ck_precos_valor_nonneg
        CHECK (pri_valor >= 0),

    CONSTRAINT ck_precos_modalidade
        CHECK (pri_modalidade IN ('SD', 'CD')),

    CONSTRAINT ck_precos_origem
        CHECK (pri_origem IS NULL OR pri_origem IN ('C', 'CR'))
);

CREATE INDEX ix_precos_ins_edi
    ON cpu.precos_insumo (pri_ins_id, pri_edi_id, pri_uf, pri_modalidade);

CREATE INDEX ix_precos_edi
    ON cpu.precos_insumo (pri_edi_id);

CREATE INDEX ix_precos_uf
    ON cpu.precos_insumo (pri_uf, pri_edi_id);


-- ============================================================
-- TABELA: cpu.composicoes
-- Cabeçalho das CPUs — VERSIONADO por edição.
-- Cada (cmp_fte_id, cmp_codigo, cmp_edi_id) é uma linha
-- distinta e imutável. Não há UPDATE em dados históricos.
--
-- cmp_situacao: 'COM CUSTO' | 'SEM CUSTO' | 'SUSPENSO' |
--               'EM ESTUDO' (vocabulário SINAPI)
-- cmp_sub_id:   FK para subgrupos (nullable — composições AXYS
--               são livres de subgrupo)
-- cmp_historico_json: array com snapshots de estruturas
--   anteriores. NULL se sem revisão registrada.
-- ============================================================
CREATE TABLE IF NOT EXISTS cpu.composicoes (
    cmp_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cmp_fte_id          INTEGER NOT NULL,
    cmp_edi_id          INTEGER NOT NULL,
    cmp_sub_id          INTEGER,
    cmp_codigo          TEXT    NOT NULL,
    cmp_descricao       TEXT    NOT NULL,
    cmp_unidade         TEXT    NOT NULL,
    cmp_situacao        TEXT,
    cmp_ativa           BOOLEAN NOT NULL DEFAULT TRUE,
    cmp_primeira_pub    DATE,
    cmp_ultima_pub      DATE,
    cmp_ultima_alteracao DATE,
    cmp_historico_json  JSONB,
    cmp_criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cmp_atualizado_em   TIMESTAMPTZ,
    cmp_criado_por      TEXT,
    cmp_atualizado_por  TEXT,

    CONSTRAINT fk_composicoes_fte
        FOREIGN KEY (cmp_fte_id)
        REFERENCES cpu.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_composicoes_edi
        FOREIGN KEY (cmp_edi_id)
        REFERENCES cpu.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_composicoes_sub
        FOREIGN KEY (cmp_sub_id)
        REFERENCES cpu.subgrupos (sub_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_composicoes_fte_codigo_edi
        UNIQUE (cmp_fte_id, cmp_codigo, cmp_edi_id),

    CONSTRAINT ck_composicoes_codigo_vazio
        CHECK (btrim(cmp_codigo) <> ''),

    CONSTRAINT ck_composicoes_unidade_vazia
        CHECK (btrim(cmp_unidade) <> ''),

    CONSTRAINT ck_composicoes_situacao
        CHECK (cmp_situacao IS NULL OR cmp_situacao IN (
            'COM CUSTO', 'SEM CUSTO', 'SUSPENSO', 'EM ESTUDO'
        )),

    CONSTRAINT ck_composicoes_historico_array
        CHECK (cmp_historico_json IS NULL
            OR jsonb_typeof(cmp_historico_json) = 'array')
);

CREATE INDEX ix_composicoes_fte_edi
    ON cpu.composicoes (cmp_fte_id, cmp_edi_id, cmp_codigo);

CREATE INDEX ix_composicoes_fte_codigo
    ON cpu.composicoes (cmp_fte_id, cmp_codigo);

CREATE INDEX ix_composicoes_sub
    ON cpu.composicoes (cmp_sub_id)
    WHERE cmp_sub_id IS NOT NULL;

CREATE INDEX ix_composicoes_situacao
    ON cpu.composicoes (cmp_situacao)
    WHERE cmp_situacao IS NOT NULL;


-- ============================================================
-- TABELA: cpu.composicao_itens
-- Itens de cada composição na sua edição.
-- Filho pode ser insumo ('INSUMO') ou sub-composição ('COMPOSICAO').
-- Vinculado à composição versionada (cmp_id inclui edição).
-- Ciclos proibidos — verificados na camada de aplicação.
-- ============================================================
CREATE TABLE IF NOT EXISTS cpu.composicao_itens (
    ci_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ci_cmp_id          INTEGER       NOT NULL,
    ci_tipo_filho      TEXT          NOT NULL,
    ci_ins_id          INTEGER,
    ci_cmp_filho_id    INTEGER,
    ci_coef            NUMERIC(14,6) NOT NULL,
    ci_situacao        TEXT,
    ci_ordem           SMALLINT      NOT NULL DEFAULT 0,
    ci_criado_em       TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ci_atualizado_em   TIMESTAMPTZ,
    ci_criado_por      TEXT,
    ci_atualizado_por  TEXT,

    CONSTRAINT fk_ci_cmp
        FOREIGN KEY (ci_cmp_id)
        REFERENCES cpu.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT fk_ci_ins
        FOREIGN KEY (ci_ins_id)
        REFERENCES cpu.insumos (ins_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_ci_cmp_filho
        FOREIGN KEY (ci_cmp_filho_id)
        REFERENCES cpu.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_ci_tipo_filho
        CHECK (ci_tipo_filho IN ('INSUMO', 'COMPOSICAO')),

    CONSTRAINT ck_ci_filho_xor
        CHECK (
            (ci_tipo_filho = 'INSUMO'
                AND ci_ins_id IS NOT NULL
                AND ci_cmp_filho_id IS NULL)
            OR
            (ci_tipo_filho = 'COMPOSICAO'
                AND ci_cmp_filho_id IS NOT NULL
                AND ci_ins_id IS NULL)
        ),

    CONSTRAINT ck_ci_coef_positivo
        CHECK (ci_coef > 0),

    CONSTRAINT uq_ci_cmp_ins
        UNIQUE (ci_cmp_id, ci_ins_id),

    CONSTRAINT uq_ci_cmp_filho
        UNIQUE (ci_cmp_id, ci_cmp_filho_id)
);

CREATE INDEX ix_ci_cmp
    ON cpu.composicao_itens (ci_cmp_id, ci_ordem);

CREATE INDEX ix_ci_ins
    ON cpu.composicao_itens (ci_ins_id)
    WHERE ci_ins_id IS NOT NULL;

CREATE INDEX ix_ci_cmp_filho
    ON cpu.composicao_itens (ci_cmp_filho_id)
    WHERE ci_cmp_filho_id IS NOT NULL;


-- ============================================================
-- TABELA: cpu.custos_composicao
-- Custos pré-calculados por composição / edição / UF / modalidade.
-- SINAPI fornece os valores direto nas abas CSD/CCD.
-- Imutável — mesmo regime de precos_insumo.
--
-- cc_pct_sp: % do custo atribuído ao preço de SP por ausência
--   de coleta local no estado. NULL para CDHU.
-- ============================================================
CREATE TABLE IF NOT EXISTS cpu.custos_composicao (
    cc_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cc_cmp_id          INTEGER       NOT NULL,
    cc_edi_id          INTEGER       NOT NULL,
    cc_uf              CHAR(2)       NOT NULL DEFAULT 'SP',
    cc_modalidade      CHAR(2)       NOT NULL DEFAULT 'SD',
    cc_custo           NUMERIC(14,4),
    cc_pct_sp          NUMERIC(8,6),
    cc_criado_em       TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cc_atualizado_em   TIMESTAMPTZ,
    cc_criado_por      TEXT,
    cc_atualizado_por  TEXT,

    CONSTRAINT fk_cc_cmp
        FOREIGN KEY (cc_cmp_id)
        REFERENCES cpu.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT fk_cc_edi
        FOREIGN KEY (cc_edi_id)
        REFERENCES cpu.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_cc_cmp_edi_uf_mod
        UNIQUE (cc_cmp_id, cc_edi_id, cc_uf, cc_modalidade),

    CONSTRAINT ck_cc_modalidade
        CHECK (cc_modalidade IN ('SD', 'CD')),

    CONSTRAINT ck_cc_custo_nonneg
        CHECK (cc_custo IS NULL OR cc_custo >= 0)
);

CREATE INDEX ix_cc_cmp_edi
    ON cpu.custos_composicao (cc_cmp_id, cc_edi_id, cc_uf, cc_modalidade);

CREATE INDEX ix_cc_edi_uf
    ON cpu.custos_composicao (cc_edi_id, cc_uf, cc_modalidade);


-- ============================================================
-- TABELA: cpu.sinapi_manutencoes
-- Log de alterações do SINAPI por boletim mensal.
-- Referência para rastrear o que mudou entre edições.
-- Imutável após import.
-- ============================================================
CREATE TABLE IF NOT EXISTS cpu.sinapi_manutencoes (
    sm_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sm_edi_id       INTEGER NOT NULL,
    sm_tipo         TEXT    NOT NULL,
    sm_codigo       TEXT    NOT NULL,
    sm_descricao    TEXT,
    sm_manutencao   TEXT    NOT NULL,
    sm_importado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sm_edi
        FOREIGN KEY (sm_edi_id)
        REFERENCES cpu.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_sm_tipo
        CHECK (sm_tipo IN ('INSUMO', 'COMPOSICAO'))
);

CREATE INDEX ix_sm_edi
    ON cpu.sinapi_manutencoes (sm_edi_id);

CREATE INDEX ix_sm_codigo
    ON cpu.sinapi_manutencoes (sm_codigo, sm_edi_id);

CREATE INDEX ix_sm_manutencao
    ON cpu.sinapi_manutencoes (sm_manutencao);


-- ============================================================
-- TABELA: cpu.cadernos
-- Caderno de encargos e critérios de medição de cada composição.
-- Documento HTML autocontido gravado no storage
-- (R2 em produção, disco local em dev).
--
-- cad_caminho_atual: chave no storage.
--   Convenção: cadernos/{fte_codigo}/{cmp_codigo}_{YYYY-MM-DD}.html
-- cad_caminhos_anteriores: versões anteriores — array JSONB.
--   [{"data_base": "YYYY-MM-DD", "caminho": "cadernos/..."}]
-- ============================================================
CREATE TABLE IF NOT EXISTS cpu.cadernos (
    cad_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cad_cmp_id              INTEGER NOT NULL,
    cad_caminho_atual       TEXT,
    cad_caminhos_anteriores JSONB,
    cad_referencia          TEXT,
    cad_criado_em           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cad_atualizado_em       TIMESTAMPTZ,
    cad_criado_por          TEXT,
    cad_atualizado_por      TEXT,

    CONSTRAINT fk_cadernos_cmp
        FOREIGN KEY (cad_cmp_id)
        REFERENCES cpu.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT uq_cadernos_cmp
        UNIQUE (cad_cmp_id),

    CONSTRAINT ck_cadernos_anteriores_array
        CHECK (cad_caminhos_anteriores IS NULL
            OR jsonb_typeof(cad_caminhos_anteriores) = 'array')
);

CREATE INDEX ix_cadernos_cmp
    ON cpu.cadernos (cad_cmp_id);


-- ============================================================
-- SCHEMA: orca
-- AGUARDANDO VALIDAÇÃO | SERÁ REAVALIADO APÓS IMPORTS
-- DO SCHEMA CPU E PRIMEIROS TESTES DE CONSULTA
-- ============================================================
--
-- OBRAS (orca.obras)
--   obr_e_paradigma=true → template paramétrico
--   Mudança de edição (data-base): arquiva versão atual
--   (obr_ativa=false, obr_status='ARQUIVADO') e cria nova com
--   obr_versao+1 e obr_versao_anterior_id → anterior.
--   srv_cmp_id aponta para composição NA EDIÇÃO da obra
--   (obr_edi_id); snapshot garantido pelo catálogo versionado.
--
-- TENANCY
--   obr_tenant_uuid = tenant UUID do JWT (TEXT — sem FK externa).
-- ============================================================

CREATE SCHEMA IF NOT EXISTS orca;

GRANT USAGE ON SCHEMA orca TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA orca
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA orca
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";

-- ============================================================
-- TABELA: orca.obras
-- Container principal de toda informação orçamentária.
-- ============================================================
CREATE TABLE IF NOT EXISTS orca.obras (
    obr_id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obr_tenant_uuid        TEXT    NOT NULL,
    obr_versao             INTEGER NOT NULL DEFAULT 1,
    obr_ativa              BOOLEAN NOT NULL DEFAULT TRUE,
    obr_versao_anterior_id INTEGER,
    obr_e_paradigma        BOOLEAN NOT NULL DEFAULT FALSE,
    obr_fte_id             INTEGER NOT NULL,
    obr_edi_id             INTEGER NOT NULL,
    obr_uf                 CHAR(2) NOT NULL DEFAULT 'SP',
    obr_modalidade         CHAR(2) NOT NULL DEFAULT 'SD',
    obr_nome               TEXT    NOT NULL,
    obr_tipologia          TEXT,
    obr_padrao             TEXT,
    obr_area_m2            NUMERIC(10,2),
    obr_pavimentos         INTEGER,
    obr_status             TEXT    NOT NULL DEFAULT 'RASCUNHO',
    obr_criado_em          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    obr_atualizado_em      TIMESTAMPTZ,
    obr_criado_por         TEXT,
    obr_atualizado_por     TEXT,

    CONSTRAINT fk_obras_fte
        FOREIGN KEY (obr_fte_id)
        REFERENCES cpu.fontes (fte_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_obras_edi
        FOREIGN KEY (obr_edi_id)
        REFERENCES cpu.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_obras_versao_anterior
        FOREIGN KEY (obr_versao_anterior_id)
        REFERENCES orca.obras (obr_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_obras_status
        CHECK (obr_status IN ('RASCUNHO', 'ATIVO', 'ARQUIVADO')),

    CONSTRAINT ck_obras_modalidade
        CHECK (obr_modalidade IN ('SD', 'CD')),

    CONSTRAINT ck_obras_versao_positiva
        CHECK (obr_versao >= 1),

    CONSTRAINT ck_obras_area_positiva
        CHECK (obr_area_m2 IS NULL OR obr_area_m2 > 0),

    CONSTRAINT ck_obras_pavimentos_positivos
        CHECK (obr_pavimentos IS NULL OR obr_pavimentos >= 1),

    CONSTRAINT ck_obras_nome_vazio
        CHECK (btrim(obr_nome) <> '')
);

CREATE INDEX ix_obras_tenant_ativa
    ON orca.obras (obr_tenant_uuid, obr_ativa);

CREATE INDEX ix_obras_paradigma
    ON orca.obras (obr_e_paradigma, obr_ativa)
    WHERE obr_e_paradigma = TRUE;

CREATE INDEX ix_obras_edi
    ON orca.obras (obr_edi_id);


-- ============================================================
-- TABELA: orca.obra_bdis
-- BDIs de uma obra. Um marcado como padrão (bdi_padrao).
-- Serviços sem bdi_id explícito usam o BDI padrão da obra.
--
-- Fórmula — Acórdão TCU 2622/2013:
--   BDI = { [(1 + AC + S + R + G) / (1 − DF − L)] − 1 } × 100
--   Todos os termos em fração (0–1); AC/S/R/G no numerador,
--   DF/L no denominador.
--
-- Impostos sobre faturamento (BDI c/ impostos):
--   I = ISS + PIS + COFINS + CSLL + IRPJ (+ CPRB se desonerado)
--
-- bdi_cprb: nullable — CPRB regime desonerado da folha.
-- bdi_taxa: BDI s/ impostos, calculado e persistido.
-- ============================================================
CREATE TABLE IF NOT EXISTS orca.obra_bdis (
    bdi_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bdi_obr_id         INTEGER NOT NULL,
    bdi_rotulo         TEXT    NOT NULL,
    bdi_padrao         BOOLEAN NOT NULL DEFAULT FALSE,
    bdi_ac             NUMERIC(6,2) NOT NULL DEFAULT 0,
    bdi_seguro         NUMERIC(6,2) NOT NULL DEFAULT 0,
    bdi_risco          NUMERIC(6,2) NOT NULL DEFAULT 0,
    bdi_garantia       NUMERIC(6,2) NOT NULL DEFAULT 0,
    bdi_df             NUMERIC(6,2) NOT NULL DEFAULT 0,
    bdi_lucro          NUMERIC(6,2) NOT NULL DEFAULT 0,
    bdi_iss            NUMERIC(6,2) NOT NULL DEFAULT 0,
    bdi_pis            NUMERIC(6,2) NOT NULL DEFAULT 0,
    bdi_cofins         NUMERIC(6,2) NOT NULL DEFAULT 0,
    bdi_csll           NUMERIC(6,2) NOT NULL DEFAULT 0,
    bdi_irpj           NUMERIC(6,2) NOT NULL DEFAULT 0,
    bdi_cprb           NUMERIC(6,2),
    bdi_taxa           NUMERIC(6,2) NOT NULL,
    bdi_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bdi_atualizado_em  TIMESTAMPTZ,
    bdi_criado_por     TEXT,
    bdi_atualizado_por TEXT,

    CONSTRAINT fk_bdis_obr
        FOREIGN KEY (bdi_obr_id)
        REFERENCES orca.obras (obr_id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT ck_bdis_rotulo_vazio
        CHECK (btrim(bdi_rotulo) <> ''),

    CONSTRAINT ck_bdis_taxa_range
        CHECK (bdi_taxa >= 0 AND bdi_taxa <= 100),

    CONSTRAINT ck_bdis_componentes_nonneg
        CHECK (
            bdi_ac       >= 0 AND bdi_ac       <= 100 AND
            bdi_seguro   >= 0 AND bdi_seguro   <= 100 AND
            bdi_risco    >= 0 AND bdi_risco    <= 100 AND
            bdi_garantia >= 0 AND bdi_garantia <= 100 AND
            bdi_df       >= 0 AND bdi_df       <= 100 AND
            bdi_lucro    >= 0 AND bdi_lucro    <= 100 AND
            bdi_iss      >= 0 AND bdi_iss      <= 100 AND
            bdi_pis      >= 0 AND bdi_pis      <= 100 AND
            bdi_cofins   >= 0 AND bdi_cofins   <= 100 AND
            bdi_csll     >= 0 AND bdi_csll     <= 100 AND
            bdi_irpj     >= 0 AND bdi_irpj     <= 100
        ),

    CONSTRAINT ck_bdis_cprb_nonneg
        CHECK (bdi_cprb IS NULL OR (bdi_cprb >= 0 AND bdi_cprb <= 100))
);

CREATE UNIQUE INDEX uix_bdis_obr_padrao
    ON orca.obra_bdis (bdi_obr_id)
    WHERE bdi_padrao = TRUE;

CREATE INDEX ix_bdis_obr
    ON orca.obra_bdis (bdi_obr_id);


-- ============================================================
-- TABELA: orca.servicos
-- Linhas orçamentárias em estrutura hierárquica (self-ref).
--
-- srv_nivel: GRUPO | SUBGRUPO | ITEM
-- Apenas ITEM referencia composição (srv_cmp_id).
-- srv_cmp_id aponta para composição na edição da obra
-- (obr_edi_id do pai) — snapshot implícito.
--
-- srv_custo_unit / srv_custo_total: snapshot do custo no momento
-- do cálculo. Imutável em obras ARQUIVADO.
--
-- Classificação paramétrica (null em obras analíticas):
--   srv_classe_param: SERVICO | AGRUPADOR | IGNORAR
--   srv_tipo_param:   PLACA | UNITARIO | ADMIN | NORMAL
--   srv_coef_rho:     coeficiente ρ (0–1); somente UNITARIO
-- ============================================================
CREATE TABLE IF NOT EXISTS orca.servicos (
    srv_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    srv_obr_id         INTEGER NOT NULL,
    srv_pai_id         INTEGER,
    srv_ordem          INTEGER NOT NULL DEFAULT 0,
    srv_nivel          TEXT    NOT NULL,
    srv_descricao      TEXT    NOT NULL,
    srv_cmp_id         INTEGER,
    srv_qtd            NUMERIC(14,4),
    srv_custo_unit     NUMERIC(14,4),
    srv_custo_total    NUMERIC(14,4),
    srv_bdi_id         INTEGER,
    srv_classe_param   TEXT,
    srv_tipo_param     TEXT,
    srv_coef_rho       NUMERIC(4,3),
    srv_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    srv_atualizado_em  TIMESTAMPTZ,
    srv_criado_por     TEXT,
    srv_atualizado_por TEXT,

    CONSTRAINT fk_servicos_obr
        FOREIGN KEY (srv_obr_id)
        REFERENCES orca.obras (obr_id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT fk_servicos_pai
        FOREIGN KEY (srv_pai_id)
        REFERENCES orca.servicos (srv_id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT fk_servicos_cmp
        FOREIGN KEY (srv_cmp_id)
        REFERENCES cpu.composicoes (cmp_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_servicos_bdi
        FOREIGN KEY (srv_bdi_id)
        REFERENCES orca.obra_bdis (bdi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_servicos_nivel
        CHECK (srv_nivel IN ('GRUPO', 'SUBGRUPO', 'ITEM')),

    CONSTRAINT ck_servicos_classe_param
        CHECK (srv_classe_param IS NULL
            OR srv_classe_param IN ('SERVICO', 'AGRUPADOR', 'IGNORAR')),

    CONSTRAINT ck_servicos_tipo_param
        CHECK (srv_tipo_param IS NULL
            OR srv_tipo_param IN ('PLACA', 'UNITARIO', 'ADMIN', 'NORMAL')),

    CONSTRAINT ck_servicos_coef_rho_range
        CHECK (srv_coef_rho IS NULL
            OR (srv_coef_rho >= 0 AND srv_coef_rho <= 1)),

    CONSTRAINT ck_servicos_qtd_positiva
        CHECK (srv_qtd IS NULL OR srv_qtd > 0),

    CONSTRAINT ck_servicos_descricao_vazia
        CHECK (btrim(srv_descricao) <> '')
);

CREATE INDEX ix_servicos_obr
    ON orca.servicos (srv_obr_id, srv_ordem);

CREATE INDEX ix_servicos_pai
    ON orca.servicos (srv_pai_id)
    WHERE srv_pai_id IS NOT NULL;

CREATE INDEX ix_servicos_cmp
    ON orca.servicos (srv_cmp_id)
    WHERE srv_cmp_id IS NOT NULL;

CREATE INDEX ix_servicos_bdi
    ON orca.servicos (srv_bdi_id)
    WHERE srv_bdi_id IS NOT NULL;


-- ============================================================
-- TABELA: orca.execucoes_parametricas
-- Registro imutável de cada execução do motor paramétrico.
-- ============================================================
CREATE TABLE IF NOT EXISTS orca.execucoes_parametricas (
    exe_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exe_tenant_uuid    TEXT    NOT NULL,
    exe_paradigma_id   INTEGER NOT NULL,
    exe_obra_id        INTEGER NOT NULL,
    exe_edi_id         INTEGER NOT NULL,
    exe_area_m2        NUMERIC(10,2) NOT NULL,
    exe_params_entrada JSONB,
    exe_valor_driver   NUMERIC(14,2),
    exe_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    exe_criado_por     TEXT,

    CONSTRAINT fk_exe_paradigma
        FOREIGN KEY (exe_paradigma_id)
        REFERENCES orca.obras (obr_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_exe_obra
        FOREIGN KEY (exe_obra_id)
        REFERENCES orca.obras (obr_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_exe_edi
        FOREIGN KEY (exe_edi_id)
        REFERENCES cpu.edicoes (edi_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT ck_exe_area_positiva
        CHECK (exe_area_m2 > 0)
);

CREATE INDEX ix_exe_tenant
    ON orca.execucoes_parametricas (exe_tenant_uuid, exe_criado_em DESC);

CREATE INDEX ix_exe_paradigma
    ON orca.execucoes_parametricas (exe_paradigma_id);

CREATE INDEX ix_exe_obra
    ON orca.execucoes_parametricas (exe_obra_id);


-- ============================================================
-- TABELA: orca.cronogramas
-- Cabeçalho do cronograma físico-financeiro.
-- Uma obra pode ter um cronograma por granularidade.
-- ============================================================
CREATE TABLE IF NOT EXISTS orca.cronogramas (
    cro_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cro_obr_id         INTEGER NOT NULL,
    cro_granularidade  TEXT    NOT NULL,
    cro_inicio         DATE    NOT NULL,
    cro_periodos       INTEGER NOT NULL,
    cro_criado_em      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cro_atualizado_em  TIMESTAMPTZ,
    cro_criado_por     TEXT,
    cro_atualizado_por TEXT,

    CONSTRAINT fk_cronogramas_obr
        FOREIGN KEY (cro_obr_id)
        REFERENCES orca.obras (obr_id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT uq_cronogramas_obr_gran
        UNIQUE (cro_obr_id, cro_granularidade),

    CONSTRAINT ck_cronogramas_granularidade
        CHECK (cro_granularidade IN ('SEMANAL', 'MENSAL', 'TRIMESTRAL')),

    CONSTRAINT ck_cronogramas_periodos_positivo
        CHECK (cro_periodos >= 1)
);

CREATE INDEX ix_cronogramas_obr
    ON orca.cronogramas (cro_obr_id);


-- ============================================================
-- TABELA: orca.cronograma_itens
-- Distribuição físico-financeira por serviço por período.
--
-- cri_valor: snapshot persistido; recalculável on-demand.
-- ============================================================
CREATE TABLE IF NOT EXISTS orca.cronograma_itens (
    cri_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cri_cro_id        INTEGER       NOT NULL,
    cri_srv_id        INTEGER       NOT NULL,
    cri_periodo_seq   INTEGER       NOT NULL,
    cri_pct_fisico    NUMERIC(5,2),
    cri_valor         NUMERIC(14,2),
    cri_criado_em     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cri_atualizado_em TIMESTAMPTZ,

    CONSTRAINT fk_cri_cro
        FOREIGN KEY (cri_cro_id)
        REFERENCES orca.cronogramas (cro_id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT fk_cri_srv
        FOREIGN KEY (cri_srv_id)
        REFERENCES orca.servicos (srv_id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT uq_cri_cro_srv_periodo
        UNIQUE (cri_cro_id, cri_srv_id, cri_periodo_seq),

    CONSTRAINT ck_cri_periodo_seq_positivo
        CHECK (cri_periodo_seq >= 1),

    CONSTRAINT ck_cri_pct_fisico_range
        CHECK (cri_pct_fisico IS NULL
            OR (cri_pct_fisico >= 0 AND cri_pct_fisico <= 100)),

    CONSTRAINT ck_cri_valor_nonneg
        CHECK (cri_valor IS NULL OR cri_valor >= 0)
);

CREATE INDEX ix_cri_cro
    ON orca.cronograma_itens (cri_cro_id, cri_periodo_seq);

CREATE INDEX ix_cri_srv
    ON orca.cronograma_itens (cri_srv_id);


-- ============================================================
-- SCHEMA: audit
-- Trilha de auditoria. Append-only — sem UPDATE nem DELETE via app.
--
-- Tabelas ativas:
--   audit.logs_retencao     — políticas de retenção (lookup controlado
--                             pelo gestor tech — users não vêem)
--   audit.criterio_retencao — mapeamento (schema, tabela) → política
--   audit.logs              — histórico de alterações em dados
--   audit.login_logs        — eventos de autenticação e origem
--   audit.api_logs          — chamadas externas à API (writes only)
--
-- Limpeza periódica (dias 5/10/15/20/25 de cada mês, 02h00):
--
--   DELETE FROM audit.logs l
--   USING audit.criterio_retencao cr
--   JOIN  audit.logs_retencao lr ON cr.crit_ret_id = lr.ret_id
--   WHERE cr.crit_schema   = l.log_schema
--     AND cr.crit_tabela   = l.log_tabela
--     AND lr.ret_permanente = false
--     AND l.log_criado_em  < NOW() - (lr.ret_dias || ' days')::INTERVAL;
--
--   Tabelas SEM critério definido → NÃO deletadas (seguro por omissão).
--   Detectar tabelas não configuradas:
--     SELECT DISTINCT log_schema, log_tabela FROM audit.logs l
--     WHERE NOT EXISTS (
--         SELECT 1 FROM audit.criterio_retencao cr
--         WHERE cr.crit_schema = l.log_schema
--           AND cr.crit_tabela = l.log_tabela
--     );
--
-- ── Arquitetura futura: sanitização de dados de tenants ──────
--
-- Distinção importante: limpeza de logs ≠ sanitização de dados.
-- A sanitização afeta dados de negócio (orca.*, etc.) de tenants
-- que encerraram uso. Por isso, o worker deve ser tratado em
-- separado do cleanup de audit.logs.
--
-- Tabelas previstas (a implementar quando orca estiver maduro):
--
--   audit.logs_retencao_by_tenant
--     id, tenant_id, tenant_role
--     → marca tenants que NÃO podem ter dados tocados,
--       independente do critério global de retenção.
--
--   audit.logs_table_arquivar_r2
--     id, schema, tabela
--     → cataloga quais tabelas devem ter seus dados exportados
--       para R2 como CSV antes da sanitização (fallback de controle).
--
-- Worker executar_limpeza() — três passagens:
--   1. retencao_criterios()    → avalia quais tabelas/registros limpar
--   2. retencao_by_tenant()    → exclui UUIDs de tenants protegidos
--   3. gerar_backup_tenants()  → exporta CSV para R2 os registros
--                                 que serão sanitizados
--   DELETE final apenas após o backup confirmado no R2.
--
-- Rationale: tenants de uso único geram orçamentos e não retornam.
-- O banco é sanitizado, mas o dado fica no R2 ad-aeternum como
-- fallback para reinsert controlado se necessário.
-- Tudo na app é auditável — este schema é o lugar canônico para
-- documentar essa intenção.
--
-- Decisões de design:
--   - Retenção determinada no momento da limpeza (não gravada por linha)
--     → política pode ser ajustada retroativamente sem perda silenciosa
--   - Sem FK para tabelas de negócio (sobrevive a soft/hard delete)
--   - audit.logs: full JSON em cadastros, diff parcial em alta frequência
--   - audit.api_logs: apenas writes (POST/PUT/DELETE); GETs ignorados
--   - audit.login_logs: campo origem prevê OAuth futuro (gov.br, Apple…)
-- ============================================================

CREATE SCHEMA IF NOT EXISTS audit;

GRANT USAGE ON SCHEMA audit TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA audit
    GRANT SELECT, INSERT ON TABLES TO "axys_tec";

ALTER DEFAULT PRIVILEGES IN SCHEMA audit
    GRANT USAGE, SELECT ON SEQUENCES TO "axys_tec";


-- ------------------------------------------------------------
-- audit.logs_retencao — políticas de retenção (lookup)
-- Seed inicial em easy_seed.sql.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.logs_retencao (
    ret_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ret_descricao   TEXT    NOT NULL,
    ret_permanente  BOOLEAN NOT NULL DEFAULT false,
    ret_dias        INTEGER NULL,

    CONSTRAINT ck_retencao_permanencia CHECK (
        (ret_permanente = true  AND ret_dias IS NULL)
        OR
        (ret_permanente = false AND ret_dias IS NOT NULL AND ret_dias > 0)
    )
);


-- ------------------------------------------------------------
-- audit.criterio_retencao — mapeamento (schema, tabela) → política
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.criterio_retencao (
    crit_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crit_schema   TEXT    NOT NULL,
    crit_tabela   TEXT    NOT NULL,
    crit_ret_id   INTEGER NOT NULL,

    CONSTRAINT fk_criterio_retencao
        FOREIGN KEY (crit_ret_id)
        REFERENCES audit.logs_retencao (ret_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_criterio_schema_tabela
        UNIQUE (crit_schema, crit_tabela)
);

CREATE INDEX ix_criterio_schema_tabela
    ON audit.criterio_retencao (crit_schema, crit_tabela);


-- ------------------------------------------------------------
-- audit.logs — histórico de alterações em dados
-- Retenção determinada por audit.criterio_retencao no cleanup job.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.logs (
    log_id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- O quê
    log_schema       TEXT          NOT NULL,
    log_tabela       TEXT          NOT NULL,
    log_registro_id  TEXT          NOT NULL,
    log_acao         TEXT          NOT NULL
                     CHECK (log_acao IN ('INSERT', 'UPDATE', 'DELETE')),

    -- Quem / quando
    log_usuario      TEXT          NOT NULL,
    log_ip           TEXT,

    -- Como estava / como ficou
    log_dados_antes  JSONB,
    log_dados_depois JSONB,

    log_criado_em    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_audit_logs_registro
    ON audit.logs (log_tabela, log_registro_id);
CREATE INDEX ix_audit_logs_usuario
    ON audit.logs (log_usuario);
CREATE INDEX ix_audit_logs_criado_em
    ON audit.logs (log_criado_em DESC);


-- ------------------------------------------------------------
-- audit.login_logs — eventos de autenticação e origem
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.login_logs (
    log_id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    log_user_id     TEXT,
    log_email       TEXT,
    log_nome        TEXT,
    log_tenant_id   TEXT,

    log_acao        TEXT         NOT NULL
                    CHECK (log_acao IN ('LOGIN', 'LOGOUT', 'LOGIN_FALHA')),

    log_origem      TEXT         NOT NULL DEFAULT 'LOCAL'
                    CHECK (log_origem IN (
                        'LOCAL',
                        'GOV_BR',
                        'APPLE',
                        'GOOGLE',
                        'API_KEY'
                    )),

    log_ip          TEXT,
    log_user_agent  TEXT,
    log_detalhes    JSONB,

    log_criado_em   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_audit_login_email
    ON audit.login_logs (log_email);
CREATE INDEX ix_audit_login_user_id
    ON audit.login_logs (log_user_id)
    WHERE log_user_id IS NOT NULL;
CREATE INDEX ix_audit_login_criado_em
    ON audit.login_logs (log_criado_em DESC);


-- ------------------------------------------------------------
-- audit.api_logs — chamadas externas à API (writes only)
-- Registra POST/PUT/PATCH/DELETE; GETs ignorados.
-- audit.api_logs captura o contexto HTTP; audit.logs captura o dado.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.api_logs (
    log_id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    log_method      TEXT         NOT NULL
                    CHECK (log_method IN ('POST', 'PUT', 'PATCH', 'DELETE')),
    log_endpoint    TEXT         NOT NULL,
    log_status      SMALLINT     NOT NULL,

    log_cliente     TEXT,
    log_usuario     TEXT,
    log_ip          TEXT,

    log_corpo_req   JSONB,
    log_duracao_ms  INTEGER,

    log_criado_em   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_audit_api_endpoint
    ON audit.api_logs (log_endpoint, log_criado_em DESC);
CREATE INDEX ix_audit_api_cliente
    ON audit.api_logs (log_cliente)
    WHERE log_cliente IS NOT NULL;
CREATE INDEX ix_audit_api_criado_em
    ON audit.api_logs (log_criado_em DESC);
