-- AxysEasy — Responsável Técnico: cadastro do tenant e quem assina cada empreendimento/ativo.
--
-- O QUE CRIA
--   tenant_catalogo.responsaveis_tecnicos   cadastro, reusado pelo tenant inteiro (como unidade e fonte)
--   ativo.empreendimento_responsaveis       quem assina o empreendimento (N:N, com ordem)
--   ativo.ativo_responsaveis                quem assina o ativo (N:N, com ordem)
--   ativo.ativos.atv_rt_herda               TRUE = o ativo usa a equipe do empreendimento
--
-- SEGURO DE APLICAR, e vale dizer por quê:
--   · tudo é criação nova — nenhuma tabela existente muda de forma;
--   · a única coluna acrescentada tem DEFAULT TRUE e NOT NULL, então as linhas existentes já
--     nascem corretas (herdar é o comportamento desejado para quem nunca escolheu nada);
--   · NADA é obrigatório: sem RT, o documento sai sem bloco de assinatura. Aplicar esta migração
--     não altera nenhum documento já emitido.
--   · não exige deploy coordenado: sem o código novo, as tabelas ficam vazias e ninguém as lê.
--
-- POR QUE `ordem` EXISTE. Bloco de assinatura é sequência. Sem a coluna, o Postgres não promete
-- ordem alguma e o mesmo documento sairia com os nomes trocados entre dois renders.
--
-- POR QUE NÃO HÁ user_uuid. O Hub é dono dos usuários e não expõe "listar usuários do tenant".
-- Coluna apontando para o que não se consulta é FK fantasma — entra por ALTER no dia em que o
-- Hub expuser.
--
-- Fonte da verdade: docs/projects/axys-easy/schemas/schema.sql (blocos "RESPONSÁVEL TÉCNICO" e
-- "QUEM ASSINA"). Aplicado em dev em 2026-10-04.

BEGIN;

CREATE TABLE IF NOT EXISTS tenant_catalogo.responsaveis_tecnicos (
    rt_id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rt_tenant_uuid            UUID    NOT NULL,
    rt_nome                   TEXT    NOT NULL,
    rt_formacao               TEXT,
    rt_documento_profissional TEXT,
    rt_ativo                  BOOLEAN NOT NULL DEFAULT TRUE,
    rt_criado_em              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rt_atualizado_em          TIMESTAMPTZ,
    rt_criado_por             TEXT,
    rt_atualizado_por         TEXT,

    CONSTRAINT ck_tcrt_nome CHECK (btrim(rt_nome) <> '')
);

CREATE INDEX IF NOT EXISTS ix_tcrt_tenant
    ON tenant_catalogo.responsaveis_tecnicos (rt_tenant_uuid) WHERE rt_ativo;

ALTER TABLE ativo.ativos
    ADD COLUMN IF NOT EXISTS atv_rt_herda BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS ativo.empreendimento_responsaveis (
    empr_emp_id  INTEGER NOT NULL,
    empr_rt_id   INTEGER NOT NULL,
    empr_ordem   INTEGER NOT NULL DEFAULT 1,

    PRIMARY KEY (empr_emp_id, empr_rt_id),
    CONSTRAINT fk_empr_emp FOREIGN KEY (empr_emp_id)
        REFERENCES ativo.empreendimentos (emp_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_empr_rt  FOREIGN KEY (empr_rt_id)
        REFERENCES tenant_catalogo.responsaveis_tecnicos (rt_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS ativo.ativo_responsaveis (
    atvr_atv_id  INTEGER NOT NULL,
    atvr_rt_id   INTEGER NOT NULL,
    atvr_ordem   INTEGER NOT NULL DEFAULT 1,

    PRIMARY KEY (atvr_atv_id, atvr_rt_id),
    CONSTRAINT fk_atvr_atv FOREIGN KEY (atvr_atv_id)
        REFERENCES ativo.ativos (atv_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_atvr_rt  FOREIGN KEY (atvr_rt_id)
        REFERENCES tenant_catalogo.responsaveis_tecnicos (rt_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

COMMIT;

-- Conferência: deve devolver 3 tabelas e a coluna.
-- SELECT table_schema||'.'||table_name FROM information_schema.tables
--  WHERE (table_schema,table_name) IN (('tenant_catalogo','responsaveis_tecnicos'),
--        ('ativo','empreendimento_responsaveis'),('ativo','ativo_responsaveis'));
-- SELECT column_name FROM information_schema.columns
--  WHERE table_schema='ativo' AND table_name='ativos' AND column_name='atv_rt_herda';
