-- AxysEasy — CONTRATANTE: para quem o orçamento é feito.
--
-- Mora em tenant_catalogo pelo mesmo motivo do RT: é cadastro reusado pelo tenant inteiro — a
-- mesma prefeitura contrata várias obras.
--
-- Vínculo 1:N (FK no empreendimento), NÃO N:N como o RT. A diferença é do domínio: assinam
-- vários, contrata UM. O header mostra uma linha "Contratante:" e o ofício abre com "À {nome}".
-- Consórcio vira tabela de ligação no dia em que aparecer.
--
-- SEGURA: só criação. A coluna nova é nullable — empreendimento sem contratante continua válido,
-- e o documento sai sem a linha.
--
-- ORDEM: indiferente. Nada no código antigo lê estas colunas.
--
-- ROLLBACK:
--   ALTER TABLE ativo.empreendimentos DROP COLUMN IF EXISTS emp_ctr_id;
--   DROP TABLE IF EXISTS tenant_catalogo.contratantes;

BEGIN;

CREATE TABLE IF NOT EXISTS tenant_catalogo.contratantes (
    ctr_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ctr_tenant_uuid   UUID    NOT NULL,
    ctr_nome          TEXT    NOT NULL,
    ctr_documento     TEXT,
    ctr_ativo         BOOLEAN NOT NULL DEFAULT TRUE,
    ctr_criado_em     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ctr_atualizado_em TIMESTAMPTZ,
    ctr_criado_por    TEXT,
    ctr_atualizado_por TEXT,

    CONSTRAINT ck_tctr_nome CHECK (btrim(ctr_nome) <> '')
);

CREATE INDEX IF NOT EXISTS ix_tctr_tenant ON tenant_catalogo.contratantes (ctr_tenant_uuid)
    WHERE ctr_ativo;

ALTER TABLE ativo.empreendimentos
    ADD COLUMN IF NOT EXISTS emp_ctr_id INTEGER
        REFERENCES tenant_catalogo.contratantes (ctr_id)
        ON UPDATE CASCADE ON DELETE RESTRICT;

COMMIT;
